### ISSUE TITLE
Documentation request: what versions of Node are available?

### ISSUE THREAD

**Issue by NickHeiner** [actions/setup-node#100]
[Using NodeJS With Github Actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-nodejs-with-github-actions#specifying-the-nodejs-version) seems like the most relevant docs, but I don't see anything about figuring out which versions of Node `setup-node` will accept.

I'd hope to see functionality like `nvm`'s `ls-remote`.

**Comment by jyasskin** [comment]
Looking at the [source](https://github.com/actions/setup-node/blob/master/src/installer.ts#L86), it appears to fetch the possible versions from https://nodejs.org/dist/index.json and support general semver matching on those versions. 👍  on writing that down, of course.

**Comment by bryanmacfarlane** [comment]
Will cover with this issue: https://github.com/actions/setup-node/issues/164
