### ISSUE TITLE
Request timeout when attempting to download directly from Node

### ISSUE THREAD

**Issue by rwader-swi** [actions/setup-node#1006]
**Description:**
<img width="862" alt="image" src="https://github.com/actions/setup-node/assets/138435075/c4c5e037-eb45-4a66-9ae0-ac16816a044c">

- When it doesn't find the node in cache, it gives request timeout.
- After removing setup-node action, we've observed the `github-scripts@v7` still run, but `upload-artifacts` action sometimes give issue.
- And sometimes there aren't any logs of `setup-node`, whether it is caching node **or caching the action itself**, or attempting to download directly. Hence, we aren't sure how to debug it. Seems like a cache issue to me because it happened after we re-deployed our self-hosted github runners.
- I tried to reproduce the issue by deleting the `node` cache in` /opt/hostedtoolcache` from our self-hosted runner, but in that case it passed 🙂
- Its very random. Please if anyone has any idea, **or whether it's related to our network issue**, then help us ASAP.

**Action version:**
## node version: 20

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Tools version:**
node-version: 20

**Repro steps:**  

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by rwader-swi** [comment]
<img width="921" alt="image" src="https://github.com/actions/setup-node/assets/138435075/767a85e3-c916-4fba-a782-be2f4b1db719">
After tracing your code, the issue seems to have occurred at this step itself. Should I try giving a specific version like 20.x.x instead of just 20?

**Comment by rwader-swi** [comment]
[https://nodejs.org/dist/index.json](https://nodejs.org/dist/index.json)

**Comment by alirezaalavi87** [comment]
I get timeouts no matter what, can't download anything.
```
Attempting to download 14...
Request timeout: /repos/actions/node-versions/git/trees/main
Falling back to download directly from Node
::error::Request timeout: /dist/index.json
```

I can ping `nodejs.org` from the runner's server and `curl https://nodejs.org/dist/index.json` returns correct results so I don't think it is a network issue.

**Comment by rwader-swi** [comment]
> I can ping `nodejs.org` from the runner's server and `curl https://nodejs.org/dist/index.json` returns correct results so I don't think it is a network issue.

Yeah same in my case

**Comment by aparnajyothi-y** [comment]
Hello @rwader-swi, @alirezaalavi87  We have tried to reproduce the issue from our local and setup-action is successfully downloading the node-version: 20 or 14 from the node official website without any timeout issue. Please find the screenshots for reference and share the repro link to further investigate the issue as we are unable to reproduce the error from our end.

**Comment by aparnajyothi-y** [comment]
Hello @rwader-swi, Please share the repro link to investigate the issue further as we are unable to reproduce the issue.

**Comment by oftravesset** [comment]
Hello, if this can help someone, we had the same issue on azure devops pipeline running the agent self-hosted behind a company proxy. We've solved configuring the environment variable HTTPS_PROXY  on the pipeline and solved for us. Maybe is not exactly your case but in case this can help others i post it here.

**Comment by aparnajyothi-y** [comment]
Hello @rwader-swi, we are closing this issue for now due to inactivity. Please feel free to reach out if the issue persists, and we can reopen it.

Hello @alirezaalavi87, thank you for confirming that you are unable to reproduce the issue.
