### ISSUE TITLE
While running setup-node in self-hosted runner, it failed to install/locate yarn

### ISSUE THREAD

**Issue by mdemri** [actions/setup-node#1029]
While running setup-node in self-hosted runner, it failed to install/locate yarn

**Description:**
Run actions/setup-node@v4
  
Attempting to download 20...
Acquiring 20.12.2 - x64 from https://github.com/actions/node-versions/releases/download/20.12.2-[8](https://github.com/org/repo/actions/runs/8956885041/job/24599234441#step:4:8)647736[8](https://github.com/org/repo/actions/runs/8956885041/job/24599234441#step:4:9)79/node-20.12.2-linux-x64.tar.gz
Extracting ...
/usr/bin/tar xz --strip 1 --warning=no-unknown-keyword --overwrite -C /actions-runner/_work/_temp/00200344-76b0-4841-ac[9](https://github.com/org/repo/actions/runs/8956885041/job/24599234441#step:4:10)f-16ae704bf5c1 -f /actions-runner/_work/_temp/85995960-eb88-45f3-a643-16b4368bb374
Adding to the cache ...
Environment details
  node: v20.12.2
  npm: 10.5.0
  yarn: 
Error: Unable to locate executable file: yarn. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

**Action version:**
4.0.1

**Platform:**
- Ubuntu

**Runner type:**
- Self-hosted

**Tools version:**
          node-version: 20
          cache: "yarn"

**Repro steps:**  
Run this step
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
On a self-hosted runner (im using ubuntu:24.04)

**Expected behavior:**
Installation of yarn. availability of yarn command in PATH

**Actual behavior:**
yarn is not being installed, or does not exist in PATH

**Comment by aparnajyothi-y** [comment]
Hello @mdemri, Thank you for creating this issue and we will look into it :)

**Comment by Janrupf** [comment]
Can confirm - this also happens on self-hosted windows runners

**Comment by alexandros-megas** [comment]
+1 I'm running into this issue with the following usage:

```yaml
  - uses: actions/setup-node@v4
    with:
      node-version: 20
```

**Comment by gowridurgad** [comment]
Hi @mdemri, After trying to replicate the issue based on provided workflow, it appears that everything is functioning correctly and we didn't encounter any issues on our end. Here's a screenshot for your reference. Please ensure that Yarn is installed and accessible in the PATH on your self-hosted runner. To help us further investigate the issue, Could you please attach link to the build or public repository to reproduce the issue ?
<img width="1033" alt="Screenshot 2024-07-16 at 10 42 32 AM" src="https://github.com/user-attachments/assets/26d21891-6e10-4307-9002-48fca1eaa042">

**Comment by gowridurgad** [comment]
Hi @mdemri , Just a gentle reminder regarding this issue, If you have any updates or need further assistance, Please let us know.

**Comment by gowridurgad** [comment]
Hi @mdemri , Just a gentle reminder regarding this issue, If you have any updates or need further assistance, Please let us know.

**Comment by gowridurgad** [comment]
Hi @mdemri, 
Due to inactivity, I'm going to close this issue for now. Please feel free to reopen this issue or create a new one if necessary. 
Thank you.

**Comment by ppreziuso-ic** [comment]
I'm having the very same issue. 
I'm following step by step the documentation and when using

```
- name: Setup Node
  uses: actions/setup-node@v4
  with:
    node-version: "22.x"
    cache: "yarn"
```
I get this error:
```
::error::Unable to locate executable file: yarn. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```
I'm trying to test my workflow locally using GitHub Local Actions on VSCode and `nextos/act`.
