### ISSUE TITLE
Add support for cache type `bun`

### ISSUE THREAD

**Issue by koozz** [actions/setup-node#1034]
**Description:**
The setup-node action is a popular tool for setting up Node.js environments in GitHub Actions workflows. Currently, it supports npm, pnpm, and yarn as package managers. However, there’s a need to include support for Bun, a faster JavaScript runner.

**Justification:**
Bun offers performance improvements over traditional JavaScript runners, making it an attractive choice for developers. By adding support for Bun in the `setup-node` action, GitHub Actions workflows can benefit from its speed and efficiency.

**Are you willing to submit a PR?**
I will have a look.

**Comment by aparnajyothi-y** [comment]
Hello @koozz, Thank you for creating this feature request and we will get back to you once we have some feedback on this :)

**Comment by silverwind** [comment]
I think such a cache should likely be part of https://github.com/oven-sh/setup-bun.

**Comment by koozz** [comment]
I reckon this action should cache all node dependencies, right? Since we run this after `setup-node` or `setup-bun`, whether we use npm, pnpm, yarn or bun. It felt the like the right place where this action does 1 thing and does it well (with a post step to store the cache).

**Comment by NoahAndrews** [comment]
> I reckon this action should cache all node dependencies, right? Since we run this after `setup-node` or `setup-bun`, whether we use npm, pnpm, yarn or bun. It felt the like the right place where this action does 1 thing and does it well (with a post step to store the cache).

What action do you think this is the repository for? It doesn't sound like you realize you've submitted a feature request for `setup-node`.
