### ISSUE TITLE
https://1405-out-min2.blogspot.com/

### ISSUE THREAD

**Issue by A1985J09** [actions/setup-node#1051]
Connect directly to my Address and shows me the address wallet 

**Description:**

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by aparnajyothi-y** [comment]
Closed this issue as a spam
