### ISSUE TITLE
fail with global install

### ISSUE THREAD

**Issue by bluelovers** [actions/setup-node#106]
https://github.com/bluelovers/is-req-https/actions/runs/31389139/workflow

when use `npm install -g esm`

it can't found `esm` module when use npx

> Error: Cannot find module 'esm'

**Comment by bryanmacfarlane** [comment]
Does it still fail without setup-node in the scenario?  I'm trying to figure out if it's related to setup-node.  My guess is not but not sure ...

**Comment by bryanmacfarlane** [comment]
Closing out.
