### ISSUE TITLE
Bug reports

### ISSUE THREAD

**Issue by JoftheV** [actions/setup-node#1060]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by HarithaVattikuti** [comment]
Closing as spammy
