### ISSUE TITLE
404 when trying to publish to npm.

### ISSUE THREAD

**Issue by ggsdc** [actions/setup-node#1068]
**Description:**
Same github action triggered by tag creation worked 2 weeks ago, now it fails when trying to publish a new version to npm.

**Action version:**
using v4.

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
node version 21.x

**Repro steps:**  
Here is the github action: https://github.com/baobabsoluciones/mango-ui/blob/master/.github/workflows/mango-ui-deploy-npm.yml
Here is the run that worked 2 weeks ago: https://github.com/baobabsoluciones/mango-ui/actions/runs/9052522117
And here are the two failing runs from yesterday and today: https://github.com/baobabsoluciones/mango-ui/actions/runs/9250954159 and https://github.com/baobabsoluciones/mango-ui/actions/runs/9267599146

**Expected behavior:**
For the workflow to work correctly and a new version to get published

**Actual behavior:**
A 404 error gets raised.

**Comment by HarithaVattikuti** [comment]
Hello @ggsdc 
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback

**Comment by ggsdc** [comment]
Hello @HarithaVattikuti and @KathiravanKrish 

I may have missed your initial reply and I was checking back on this as I had to do a new upload manually of the library in said repository.

Is there any news on this issue or how to fix it?
Is there any class of log that I may be able to download that could give you back more information?

Thank you in advance for your help

**Comment by ggsdc** [comment]
Thank you @KathiravanKrish I would double check the token, as the package is currently registered under our name and we can upoload manually.

**Comment by aparnajyothi-y** [comment]
Hello @ggsdc, a gentle reminder to please check and confirm the npm configuration and verify the availability of the package name on the npm registry. Thank you.

**Comment by qwertycxz** [comment]
Hey, sorry to bother! May I ask you about how do you fix this issue? I am currently experiencing [similar issue](https://github.com/qwertycxz/pm2-logs-attach-input/actions/runs/14951924723) and having no clue. Thank you!
