### ISSUE TITLE
Small error on the README

### ISSUE THREAD

**Issue by kilted-andres** [actions/setup-node#1080]
**Description:**
It seems like someone made the classic confusion between "**admit**" and "**emit**" on [line 24 of the REAME.md](https://github.com/actions/setup-node/blob/eff380dfbcf941bf8832e4acb788cebe13dfd758/README.md?plain=1#L24C15-L24C20)

**Actions to take:**
Change from: 

> It also emits such aliases as lts, latest, nightly and canary builds

to: 

> It also admits aliases such as lts, latest, nightly and canary builds

**Comment by aparnajyothi-y** [comment]
Hi @kilted-andres, Thank you for creating this issue and we will look into it :)

**Comment by kilted-andres** [comment]
Thanks!

**Comment by suyashgaonkar** [comment]
Hello @kilted-andres, we have investigated the bug and have concluded after thorough investigation that the word "admits" seems to be appropiriate on line 24 in the README, considering the way node versions can be mentioned in the workflows. The changes are been done and hence closing this.

**Comment by kilted-andres** [comment]
Awesome, thanks for the update!

Glad I could be a tiny bit of help.
