### ISSUE TITLE
Changing node-version without changing action makes merging impossible (required job pending)

### ISSUE THREAD

**Issue by tommyboylab** [actions/setup-node#1107]
**Description:**
After bumping the node-version used by an action, I find that I'm unable to merge a PR with the changes as the previous action is marked as required but never finished (since it no longer exists)

**Action version:**
v4

**Platform:**
- [ x ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ x ] Hosted
- [ ] Self-hosted

**Tools version:**
Node-version 16 -> 18, 
Bun 1.1.18+5a0b93523

**Repro steps:**  
- Take a previous workflow and bump the node version of the runner
- Create PR to merge changes
- See that jobs pass, but old jobs with old node version are still present and marked as 'required'
<img width="845" alt="346589407-f604adf9-e8f2-455d-8ca8-1023ca7f326a" src="https://github.com/actions/setup-node/assets/44362297/1647842f-1595-43eb-ade3-0fe500d4e2e4">

**Expected behavior:**
Bumping node version should not create duplicate jobs, should replace the old jobs.

**Actual behavior:**
Bumping node version duplicates the jobs, marking old ones (which never run as they don't exist) as required so PR is unable to be merged.

**Comment by priyagupta108** [comment]
Hello @tommyboylab 👋 ,
Thank you for your report. We will investigate the issue and get back to you as soon as we have updates.

**Comment by KathiravanKrish** [comment]
Hi @tommyboylab, 

When you bump the Node.js version in a GitHub Action and find that a required status check from a previous action is preventing you from merging, you can resolve this issue by updating the branch protection rules to reflect the new action. Here’s what you can do:

1. **Update Branch Protection Rules**:

- Go to your repository on GitHub.

- Click on Settings > Branches > Branch protection rules.

- Edit the relevant branch protection rule.

- Update the required status checks to match the new action names and remove the old ones.

2. **Merge the PR:**

- Once the branch protection rules are updated, the required status checks should reflect the new actions.

- Ensure the new actions are passing before attempting to merge the PR.

Additionally, please ensure that you do not include node-version: 16 in your workflow file.

For detailed steps on editing branch protection rules, you can refer to [GitHub's documentation on configuring protected branches](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-protected-branches). This should resolve the issue and allow you to merge the PR.

**Comment by aparnajyothi-y** [comment]
Hello @tommyboylab, We are proceeding to close this issue as we didn't hear anything from a long time and please feel free to reach us in case any clarifications/support needed to reopen this issue. Thank you.
