### ISSUE TITLE
Regression in Node 22.5.0 fixed in 22.5.1

### ISSUE THREAD

**Issue by wolfy1339** [actions/setup-node#1112]
**Description:**
There is a bug in Node v22.5.0 that causes NPM to fail installation of modules.

NodeJS just released a new version containing a fix 
https://github.com/nodejs/node/pull/53935
**Action version:**
v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.

See https://github.com/npm/cli/issues/7657 https://github.com/nodejs/node/issues/53902

**Expected behavior:**
A description of what you expected to happen.

For the new Node release to be available whenever it gets published. https://github.com/nodejs/node/pull/53935

**Actual behavior:**

Node 22.5.0 is broken and 22.5.1 is not available

**Comment by priya-kinthali** [comment]
Hello @wolfy1339,
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by danielhjacobs** [comment]
I believe this action's underlying runner, https://github.com/actions/node-versions, is updated every 12 hours with new releases on an automated schedule: https://github.com/actions/node-versions/blob/main/.github/workflows/get-node-versions.yml. The new PR in that repo will need to be merged: https://github.com/actions/node-versions/pull/182.

**Comment by RobinTail** [comment]
Even with `check-latest: true` it does not fetch 22.5.1 for `22.x`

**Comment by RobinTail** [comment]
That thing https://github.com/actions/node-versions/pull/182 is finally merged.

**Comment by RobinTail** [comment]
Should be fixed now

<img width="309" alt="Screenshot 2024-07-22 at 12 24 34" src="https://github.com/user-attachments/assets/9cc9581b-79c1-43b5-93f8-523748accd9c">
