### ISSUE TITLE
npm ERR! 429 Too Many Requests

### ISSUE THREAD

**Issue by danechitoaie** [actions/setup-node#112]
npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/@babel/plugin-transform-new-target/-/plugin-transform-new-target-7.4.4.tgz

We started getting this error. If I try to re-run the job we get same error but for different package/url.
So looks like NPMJS is throttling the connections from GitHub actions?

**Comment by adaptive** [comment]
try using registry `https://npm.pkg.github.com` or `https://registry.yarnpkg.com`

**Comment by bryanmacfarlane** [comment]
I don't believe this is related to the setup-node code here which does the install of node and puts it in the path.

**Comment by danechitoaie** [comment]
Yes, we can close this. It was that day when whole NPM was down.
