### ISSUE TITLE
Feature request: Support pnpm

### ISSUE THREAD

**Issue by ExE-Boss** [actions/setup-node#113]
[**pnpm**](https://pnpm.js.org) is the third largest package manager for **Node**, which can be detected by checking for the presence of `pnpm‑lock.yaml`.

---

/cc @zkochan

**Comment by bryanmacfarlane** [comment]
The setup tasks are focused and this one sets up node from nodes dist (which comes with npm).  I would recommend creating a `setup-pnpm` action.
