### ISSUE TITLE
actions/setup-node@v4 fails without any logging or error messages

### ISSUE THREAD

**Issue by wuzzeb** [actions/setup-node#1136]
**Description:**

actions/setup-node@v4 started failing today without any errors or debug logging.  I made a simple empty public repository to test it, which is recreating what happens in our main repository.  See 

https://github.com/SeedTactics/setup-node-test
https://github.com/SeedTactics/setup-node-test/actions/runs/10908848118/job/30275746876

**Action version:**
v4

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [X] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**
See
https://github.com/SeedTactics/setup-node-test/blob/main/.github/workflows/test.yml

**Repro steps:**  
https://github.com/SeedTactics/setup-node-test
see https://github.com/SeedTactics/setup-node-test/actions/runs/10908848118/job/30275746876

**Expected behavior:**
Node is installed, or at least some kind of error or log of what is happening

**Actual behavior:**
actions/setup-node@v4 fails with no logs or errors

**Comment by ryanwitt** [comment]
Note that nodejs.org is having an outage, though status.nodejs.org had not been updated as of just before this comment.

**Comment by laser** [comment]
> Note that nodejs.org is having an outage, though status.nodejs.org had not been updated as of just before this comment.

Hrm, still not updated:

https://status.nodejs.org/

**Comment by Nickadiemus** [comment]
Yeah I'm not seeing it updated as well

**Comment by ryanwitt** [comment]
Guessing between the outage and no recent release for this repo that it is not an issue with this project.

**Comment by wuzzeb** [comment]
In that case, wouldn't the action emit an error?  Something like couldn't contact nodejs.org?

**Comment by ryanwitt** [comment]
> In that case, wouldn't the action emit an error message? Something like couldn't contact nodejs.org?

Not if it's a DNS timeout, which this appeared to be. I observed a new error just now, but the action auto-recovered:

```
Attempting to download 21.x...
Not found in manifest. Falling back to download directly from Node
Acquiring 21.7.3 - x64 from https://nodejs.org/dist/v21.7.3/node-v21.7.3-linux-x64.tar.gz
read ECONNRESET
Waiting 16 seconds before trying again
...
```

So see if a retry on the failed job works.

**Comment by laser** [comment]
> So see if a retry on the failed job works.

I just retried the job (after waiting ~45 minutes since the initial failures and subsequent retries) and the issue has resolved itself.

Thanks, all!

**Comment by priyagupta108** [comment]
Hello everyone 👋 ,
Thank you for reporting this issue. The issue was caused by a temporary outage on the Node.js website affecting downloads. According to the [Node.js status page](https://status.nodejs.org/), the issue has now been resolved.
Please try rerunning your workflows. If the problem persists, feel free to reach out to us.
