### ISSUE TITLE
> **Description:**

### ISSUE THREAD

**Issue by OATEF4313** [actions/setup-node#1139]
/              > **Description:**
> 
> ##Oatef4313@gmail.com
>  Osama Atef
> ```
> $ curl -v 'https://golang.org/dl/?mode=json&include=all'
> ...
> < HTTP/2 301
> ...
> < location: https://go.dev/dl/?mode=json&include=all
> ...
> <a href="https://go.dev/dl/?mode=json&amp;include=all">Moved Permanently</a>.
> ```
> 
> **Related issue:**
> 
> None.
> 
> **Check list:**
> 
> * ~[ ] Mark if documentation changes are required.~
> * ~[ ] Mark if tests were added or updated to cover the changes.~
> 
> Since it's only a change in the URL, it seems that no additions to documentation or testing are necessary.

_Originally posted by @krylov-krylov in https://github.com/actions/setup-go/issues/469#issuecomment-2053783535_
          
[Uploading thomas-kurian-ceo-of-google-cloud-at-the-goldman-sachs-communacopia-technology-conference-on-september-10-2024.pdf…]()
[Uploading FDsys_Architecture.pdf…]()
[](url)

**Comment by OATEF4313** [comment]
[Uploading thomas-kurian-ceo-of-google-cloud-at-the-goldman-sachs-communacopia-technology-conference-on-september-10-2024.pdf…]()

**Comment by HarithaVattikuti** [comment]
Closing as spammy
