### ISSUE TITLE
`npm publish` registry URL deprecated: "This endpoint is deprecated. Use https://replicate.npmjs.com instead."

### ISSUE THREAD

**Issue by shgysk8zer0** [actions/setup-node#1141]
**Description:**
`https://registry.npmjs.org` is deprecated (no longer works) for publishing packages, resulting in the following error:

```
npm ERR! error creating tlog entry - (502) Bad Gateway
```

Making a request to the current registry URL gives the following error via an `npm-notice` header: "This endpoint is deprecated. Use https://replicate.npmjs.com instead." This notice is not present in requests for eg `https://registry.npmjs.org/yocto-queue`.

However, updating the registry URL makes installing packages 404:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://replicate.npmjs.com/yocto-queue/-/yocto-queue-0.1.0.tgz - not_found
npm ERR! 404 
npm ERR! 404  'https://registry.npmjs.org/yocto-queue/-/yocto-queue-0.1.0.tgz' is not in this registry.
npm ERR! 404 This package name is not valid, because 
npm ERR! 404  1. name can only contain URL-friendly characters
```

**Action version:**
`uses: actions/setup-node@v4`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

Node v20.9.0, npm 10.1.0

**Repro steps:**  
Trigger a GitHub Actions workflow with a `npm publish --provenance --access public` step

**Expected behavior:**
Packages should install and publish, as they were previously. I've been using this workflow without issue for about a year, and it just stopped working with the errors yesterday afternoon.

**Actual behavior:**
Either there is a Bad Gateway error in publishing with the deprecated registry URL, or there is a Bad Request error installing packages with the updated registry URL. I suspect this may require temporarily supporting a registry for installing and another for publishing.

**Comment by shgysk8zer0** [comment]
Self-comment just to add a bump here... This may be an issue for a minority ATM, but having the correct registry for publishing with `--provenance` is pretty critical to the overall ecosystem, as is dealing with the deprecated endpoint.

**Comment by mahabaleshwars** [comment]
Hi @shgysk8zer0,
Thank you for creating this issue. We will investigate it and provide feedback as soon as we have some updates.

**Comment by shgysk8zer0** [comment]
@mahabaleshwars It may have been only a temporary issue with `registry.npmjs.org`. I'm unsure. I re-ran an old run and it did  successfully publish.

I'll close the issue, however that deprecation warning might still be worth looking into.
