### ISSUE TITLE
Unable to find LTS release 'jod' for Node version 'lts/jod'

### ISSUE THREAD

**Issue by davidglezz** [actions/setup-node#1154]
**Description:**
Latest LTS version is not available.
```
Run actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
Node version file is not JSON file
Resolved .nvmrc as lts/jod
Attempt to resolve LTS alias from manifest...
Error: Unable to find LTS release 'jod' for Node version 'lts/jod'.
```

**Action version:**
Latest - `39370e3970a6d050c480ffad4ff0ed4d3fdee5af`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by ahosgood** [comment]
This is also dependent on https://github.com/actions/node-versions/pull/191 and is a duplicate of #1153

**Comment by aparnajyothi-y** [comment]
Hello @davidglezz, Thank you for creating this issue. This will be fixed once [this PR](https://github.com/actions/node-versions/pull/191) is merged.

**Comment by davidglezz** [comment]
Fixed. thanks!
