### ISSUE TITLE
pnpm Support

### ISSUE THREAD

**Issue by misogihagi** [actions/setup-node#1165]
**Description:**
I'm using pnpm in my project.
setup-node does not work.

> Run actions/setup-node@v4
> Node version file is not JSON file
> Resolved .node-version as 21.6.2
> Attempting to download 21.6.2...
> Not found in manifest. Falling back to download directly from Node
> Acquiring 21.6.2 - x64 from https://nodejs.org/dist/v21.6.2/node-v21.6.2-linux-x64.tar.gz
> Extracting ...
> /usr/bin/tar xz --strip 1 --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/c6e9e174-8852-4a50-b423-4526257ae884 -f /home/runner/work/_temp/e3b0661a-cfe3-408e-b1c4-7e2616add902
> Adding to the cache ...
> Done
> Environment details
> /opt/hostedtoolcache/node/21.6.2/x64/bin/npm config get cache
> /home/runner/.npm
> Error: Dependencies lock file is not found in /home/runner/work/lighthouse-ci-datadog-action/lighthouse-ci-datadog-action. Supported file patterns: package-lock.json,npm-shrinkwrap.json,yarn.lock

**Justification:**
yarn is available. why don't we use also pnpm?

**Comment by priyagupta108** [comment]
Hi, @misogihagi 👋, Thank you for the feature request, we will investigate it and get back to you as soon as we have updates.

**Comment by tatethurston** [comment]
pnpm is already supported. per the project readme, specify `cache`.

**Comment by misogihagi** [comment]
My apologies.
I said something misleading.
Here is my code.
````
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
      - run: pnpm install
````
It doesn't work because pnpm doesn't exist. yarn exists!

Similar to the #530 .

Why does yarn exist in default?

**Comment by o-l-a-v** [comment]
Yarn is in the GitHub runner images, while pnpm is not:

* <https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md>

You could enable corepack or install pnpm with npm or Yarn. Or use this action:

* <https://github.com/pnpm/action-setup>

**Comment by misogihagi** [comment]
Thanks!
It seems to depend on the base image of the github action in question 
I'll close it here.
