### ISSUE TITLE
Type in your language with Ghosts 

### ISSUE THREAD

**Issue by Joker01-tech** [actions/setup-node#1167]
I'm using Gboard to type in English (US) (QWERTY). You can try it at: https://gboard.app.goo.gl?utm_campaign=user_referral&amv=26830000&apn=com.google.android.inputmethod.latin&ibi=com.google.keyboard&isi=1091700242&link=https%3A%2F%2Fdeeplink.com.google.android.inputmethod.latin%2F%3FdeeplinkInfo%3DH4sIAAAAAAAA%252F%252BPi52JNzdMNDRZiKyxPLSqplDg2pdcLAJcbHe4WAAAA&utm_medium=deeplink&utm_source=setting_sharing&ofl=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.google.android.inputmethod.latin

**Comment by priya-kinthali** [comment]
Closing because it seems to be spam
