### ISSUE TITLE
tsc output format changed?

### ISSUE THREAD

**Issue by NicholasBoll** [actions/setup-node#152]
I noticed Typescript errors were no longer being matched correctly. After a bit of research it seems the format has changed? I couldn't find confirmation, but here's a comparison:

Before:
```
src/commandHandler.ts(107,11): error TS2322: Type 'Response<ReposGetCollaboratorPermissionLevelResponse>' is not assignable to type 'Response<CollaboratorPermissionLevel>'.
```

Now:
```
src/commandHandler.ts:107:11 - error TS2322: Type 'Response<ReposGetCollaboratorPermissionLevelResponse>' is not assignable to type 'Response<CollaboratorPermissionLevel>'.
```

It seems a small change to the regex in the tsc.json could be changed to accommodate both patterns.

**Comment by NicholasBoll** [comment]
Perhaps this is a detection of the environment? Locally I get the colon pattern. I think on the CI I get the paren pattern.

The output from the Github CI makes it a bit hard to compare (https://github.com/Workday/canvas-kit/pull/609/checks?check_run_id=636485860):
```
##[error]modules/tooltip/react/lib/Tooltip.tsx(46,3): error TS2322: Type '"label1"' is not assignable to type '"label" | "describe"'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
##[error]Process completed with exit code 1.
```

But the line number wasn't properly extracted:
<img width="809" alt="Screen Shot 2020-05-01 at 1 27 48 PM" src="https://user-images.githubusercontent.com/338257/80835239-998e5100-8baf-11ea-9b9a-fe899a7fa4b5.png">

**Comment by NicholasBoll** [comment]
I figured out why it wasn't able to find the correct line. The Regex matches a group of any of these patterns: `(0)` or `(0,0)` or `(0,0,0)`. All of those are set to the `location` (which doesn't seem to be working) instead of `line` and `column` which does seem to be working.

That seems like a different issue?

**Comment by NicholasBoll** [comment]
I was able to override the matcher here and it worked to put annotations on the correct line: https://github.com/Workday/canvas-kit/pull/609/commits/c1e38bea3332dcda0748a27e8dc83450caaf2fc5

<img width="557" alt="Screen Shot 2020-05-01 at 3 26 07 PM" src="https://user-images.githubusercontent.com/338257/80842931-1de8d000-8bc0-11ea-9f1c-701cc1108a59.png">

**Comment by bryanmacfarlane** [comment]
I'll take a look at how you overrode and see if we can improve our matcher.

**Comment by jmealo** [comment]
@bryanmacfarlane: Trying to use eslint and/or standard with GitHub actions and get annotations (or in a mono-repo, with a non-root .eslintrc or package.json) has been problematic. There's nothing in the market place that works yet**. `setup-node` looks like it should work with eslint but it doesn't. 

** https://github.com/ataylorme/eslint-annotate-action works but it has an issue with phantom lint errors for lines that no longer exist. These persist between branches/pull requests.

**Comment by ockham** [comment]
Seems like this has been fixed by https://github.com/actions/setup-node/pull/125 (available in `actions/setup-node@2.1.5` and later)?

**Comment by bryanmacfarlane** [comment]
@NicholasBoll - can you confirm if latest (2.1.5) addresses the issue?

**Comment by NicholasBoll** [comment]
It looks like it works:

![image](https://user-images.githubusercontent.com/338257/110519908-18ef8980-80cb-11eb-832d-a233d747d97d.png)

From https://github.com/Workday/canvas-kit/pull/994/files
