### ISSUE TITLE
##[error]An action could not be found at the URI 'https://api.github.com/repos/actions/setup-node/tarball/v2-Beta'

### ISSUE THREAD

**Issue by MShahzad-pk** [actions/setup-node#162]
this error occurs while running foll command please help
    - name: Installing Node.js
      uses: actions/setup-node@v2-Beta
      with: 
        node-version: 12

**Comment by ethanchewy** [comment]
Try `actions/setup-node@v2-beta` instead of `actions/setup-node@v2-Beta`

**Comment by bryanmacfarlane** [comment]
yep. casing is v2-beta
