### ISSUE TITLE
Improve documention on version input (semver spec behavior in readme)

### ISSUE THREAD

**Issue by GMartigny** [actions/setup-node#164]
Hi,
As far as I see, there's no way to use the latest node version without manually specifying it.
I want to be able to run my tests in the latest node version without updating it each time a new version came out.
It could be achieved with the keyword `'latest'` or `'node'` in the same way you can do with `NVM`.
Cheers

**Comment by faisaldahdal-arch** [comment]
Agreed, lets do that.
________________________________

**Comment by bryanmacfarlane** [comment]
the version input is a semver version spec.  So 14.x works.  Doesn't * work?
https://jubianchi.github.io/semver-check/#/*/14.0.8

**Comment by GMartigny** [comment]
> Doesn't * work?

[Yes it does](https://github.com/pencil-js/pencil.js/runs/810469707?check_suite_focus=true#step:3:3), thanks for the workaround. Maybe, this solution should be more promoted on the action documentation.
Thanks again

**Comment by bryanmacfarlane** [comment]
@GMartigny - thanks, I'll re-open and morph to a doc issue.   One small note - it's not a workaround ;) the semver spec is a feature and the way we believe it should work.  I'll update the readme.

**Comment by dmitry-shibanov** [comment]
Hello @GMartigny. We added section about [supported version syntax](https://github.com/actions/setup-node#supported-version-syntax) to the docs. I think it should cover the logic about semver notation and getting latest available versions from [node-versions](https://github.com/actions/node-versions).
But I want to notice that according to the [docs](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#check-latest-version), if you use check-latest input, the action firstly will check versions from node-versions repository and if the version is not found it'll fallback to the toolcache. The input `lts/*` will help to grab appropriate LTS version.

**Comment by GMartigny** [comment]
If I understand correctly, `lts/*` is equivalent to `latest`.

**Comment by dmitry-shibanov** [comment]
Hello @GMartigny. The `latest` input can install non `lts` version, which is now 17, and the `lts/*` input will download the `lts` version, which is now 16.
