### ISSUE TITLE
Clarify release stability in tags

### ISSUE THREAD

**Issue by scothis** [actions/setup-node#168]
The releases page labels the `v2.0.0` and `v2.1.0` tags as pre-release and "beta". Because the tag name is also a version number not following semver, Dependabot is picking up these releases and upgrading workflows from stable action releases to pre-releases. The tags should be `v2.0.0-beta` to follow the semver conventions around pre-releases, allowing GitHub's tools to work well with GitHub's tools. Or if these tags are not actually beta, the releases page should be clarified.

This issue isn't limited to the setup-node action, but it's the first actions/* repo where I noticed the issue.

**Comment by ogonkov** [comment]
Got the same problem. Dependabot spamming me because of new beta release.

**Comment by viceice** [comment]
Renovate is hit by this too 😞

**Comment by rarkins** [comment]
Unfortunately `2.1.1` was subsequently *not* defined as pre-release in the **metadata**, while `2.1.2` is. 

![image](https://user-images.githubusercontent.com/6311784/96697007-b56af680-138b-11eb-9517-043a5ee7e1ee.png)
-----
![image](https://user-images.githubusercontent.com/6311784/96696983-ac7a2500-138b-11eb-9e33-8af0ba40a30f.png)
-----
![image](https://user-images.githubusercontent.com/6311784/96696937-a1bf9000-138b-11eb-9a43-3f3dde1dc7b0.png)

There's no way any automated tooling can be expected to handle this gracefully. I suggest to do this:

1. Edit the `2.1.1` release to classify it as pre-release
2. Release a stable 2.x as soon as possible, this will essentially make the problem go away
3. Adopt the semver approach to beta versions for all future actions, as suggested by @scothis above

**Comment by JamieMagee** [comment]
@maxim-lobanov As the person that created the `v2.1.1` release, can you please tag it as pre-release?

**Comment by maxim-lobanov** [comment]
Looks like I don't have permissions to edit release for now.
May be @konradpabjan or @bryanmacfarlane could help?

**Comment by maxim-lobanov** [comment]
I have got permissions and fixed https://github.com/actions/setup-node/releases/tag/v2.1.1 tag

**Comment by hellomykillers** [comment]
I can't go in the cuby whole mama

**Comment by JamieMagee** [comment]
I believe this issue can be closed now as there's since been a stable release of `2.x` ([`v2.1.4`](https://github.com/actions/setup-node/releases/tag/v2.1.4)) and the other releases in the `2.x` series have the pre-release label applied.
