### ISSUE TITLE
An action could not be found at the URI 'https://api.github.com/repos/actions/setup-node/tarball/v2

### ISSUE THREAD

**Issue by vetermanve** [actions/setup-node#191]
Hi, i've tried create action based on first example, but constantly have failed job starting
`An action could not be found at the URI 'https://api.github.com/repos/actions/setup-node/tarball/v2'`

My workflow
```# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
       
      - run: node --versrion | 
          npm --version
```

very generic.

i will try to use @1 version, but overall situation is quite strange - if v2 is not available you probably should remove example which uses v2 action. Or do some other thing.

**Comment by GingerAdonis** [comment]
Yes it's quite problematic. `v2-beta` resolves to an older beta. While `v2` doesn't resolve to anything. I ended up using `v2.1.1` as it's the latest v2 beta. However, I'd rather not include a specific version.

**Comment by maxim-lobanov** [comment]
Hello everyone!
We have recently released stable `actions/setup-node@v2` that points to `v2.1.4` that is marked as stable too.
I am closing this issue but please let me know if you have any concerns.
