### ISSUE TITLE
Unable to find actions actions/setup-node@v2

### ISSUE THREAD

**Issue by antek-drzewiecki** [actions/setup-node#211]
I was trying to upgrade from actions/setup-node@v1 to actions/setup-node@v2.

Following the documentation from the action page i've replaced v1 with v2.
Upon running the action we get the following message.
```
.github#L1

Unable to resolve action `actions/setup-node@v2`, unable to find version `v2`
```

Is it something with the documentation? Is v2 still in beta? Or which tags should we use?

**Comment by stefankip** [comment]
Yeah same problem here. I now use `setup-node@v2.1.2` which works, but would like to use `v2` instead.

**Comment by Roriz** [comment]
![image](https://user-images.githubusercontent.com/1077589/99398468-38b43500-28c3-11eb-8369-b4fe13651c3d.png)

**Comment by JamesIves** [comment]
Generally speaking you probably shouldn't point to a release branch of an action. Use a specific version found on the marketplace, otherwise you'll run the risk of breaking changes affecting your production workflows.

**Comment by stefankip** [comment]
Well I assume no breaking changes will be introduced within a single major version to be honest...

**Comment by JamesIves** [comment]
> Well I assume no breaking changes will be introduced within a single major version to be honest...

I wouldn't assume that as you're simply referencing a branch and not a tagged version. Use a tagged version with Dependabot to keep your workflows up to date.

**Comment by maxim-lobanov** [comment]
Hello everyone!
We have recently released stable `actions/setup-node@v2` that points to `v2.1.4` that is marked as stable too. Also updated README properly.
I am closing this issue but please let me know if you have any concerns.

**Comment by pierregangloff** [comment]
This is still an issue for me

`name: Scala CI

on:
  workflow_dispatch:
  push:
    branches:
    - Development
  pull_request:
    branches:
    - Development

jobs:
  build-job:
    runs-on: ubuntu-latest
    container: alpine:latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Node 15.x
      uses: actions/setup-node@v2
      with:
        node-version: '15'`

Unable to resolve action `actions/setup-node@v2`, unable to find version `v2`

**Comment by Fitmavincent** [comment]
I don't mean to dig grave here, but this issue doesn't seem to be resolved. 

![image](https://user-images.githubusercontent.com/7020812/150661850-295e949a-1caf-4a27-b065-124b671d83e4.png)

```name: Deploy App to Netlify

on:

  push: 
    branches: [ master ]
  pull_request: 
    branches: [ master ]

  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps: 
      - name: Checkout crawler-app
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@2
        with: 
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@1.2
        with: 
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from Github actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
```

**Comment by dmitry-shibanov** [comment]
Hello @Fitmavincent. You specified the wrong version for the setup-node action. It should be `uses: actions/setup-node@2` -> `uses: actions/setup-node@v2`.

**Comment by Fitmavincent** [comment]
> Hello @Fitmavincent. You specified the wrong version for the setup-node action. It should be `uses: actions/setup-node@2` -> `uses: actions/setup-node@v2`.

Thank you very much @dmitry-shibanov.

**Comment by crswll** [comment]
@dmitry-shibanov This has me stumped for a good ten minutes just now hahaha. Thank you!
