### ISSUE TITLE
Why is every version 2.x.x release marked as "beta"?

### ISSUE THREAD

**Issue by JonathanWilbur** [actions/setup-node#217]

**Comment by vweevers** [comment]
The format of the 2.x.x tags seem to indicate they're stable versions. And perhaps, seeing as the beta is several months old now (and working fine in my experience), that is indeed the case now.

If so, is it time to create a `v2` tag? This would allow folks to use `@v2`, reducing noise from dependabot and similar services.

**Comment by staabm** [comment]
its misleading that dependabot is providing update PRs for this beta version:

e.g. https://github.com/redaxo/redaxo/pull/4201

**Comment by anton-yurchenko** [comment]
@staabm, I have raised a ticket to GitHub Support with a request to configure Dependabot in such a way that it will ignore pre-releases of actions, and here is their reply:

> There is an open Dependabot Issue to address this functionality, and I've gone ahead and added your case as a +1 to it. We aren't able to say when this bug will be fixed, but you can keep an eye on the GitHub blog for information on when and if this makes it into the product.

**Comment by maxim-lobanov** [comment]
Hello everyone!
We have recently released stable `actions/setup-node@v2` that points to `v2.1.4` that is marked as stable too.
I am closing this issue but please let me know if you have any concerns.
