### ISSUE TITLE
indeterministic behaviour building nodejs projects

### ISSUE THREAD

**Issue by xh3b4sd** [actions/setup-node#220]
Hello, we are experiencing flapping builds when using the `setup-node` action where occasionally builds fail with "unexpected token" errors. At first the Github Support advised to upgrade from `v1` to `v2`. At first it appeared to have solved the problem, though now we see the same indeterministic behaviour again which is also not reproducible locally. I tried to use different NodeJS versions and enabled the workflow debug logging via the `ACTIONS_STEP_DEBUG=true` secret in our repository, but all with no avail. The Github Support suggested to reach out here and try to gather more information about how to debug this situation further. Example builds are shown below. You see that two builds execute `npm run build` of which one succeeds and one fails, even though both build the same project. 

- https://github.com/venturemark/webclient/pull/92/checks?check_run_id=1606578858
- https://github.com/venturemark/webclient/pull/92/checks?check_run_id=1606578880

**Comment by aminya** [comment]
That is a problem with your build tools. Nodejs has set up the version you requested as expected:
https://github.com/venturemark/webclient/pull/92/checks?check_run_id=1606578880#step:3:19
https://github.com/venturemark/webclient/pull/92/checks?check_run_id=1606578858#step:3:19

**Comment by xh3b4sd** [comment]
Thank you for getting back to me. Do you have a suggestions on how to further debug this particular issue? I am not proficient in the Javascript ecosystem, which is why I am here asking stupid questions. 😬

**Comment by joshmgross** [comment]
👋  Hey @xh3b4sd,

Based on the error:
```
SyntaxError: /home/runner/work/webclient/webclient/node_modules/@venturemark/numnum/dst/index.js: Unexpected token (17:11)
```

The error is coming from your `@venturemark/numnum` package (https://github.com/venturemark/numnum), so I'd recommend checking that or verifying that the minified package is correct.

**Comment by xh3b4sd** [comment]
I solved it myself though I cannot really explain why it was broken. What I did was I removed `rollup` in the build process of `numnum` and only used `tsc` instead to build it. This solved the problem. Though I also do not understand why this happened in the build container when running Github actions and why it was not reproducible for anyone on their local machine.
