### ISSUE TITLE
v2 breaking changes?

### ISSUE THREAD

**Issue by fishcharlie** [actions/setup-node#223]
There is currently no CHANGELOG file for this repo. So it's very difficult to see breaking changes for v2.

I looked through the releases page, and all of the information seems pretty broad and doesn't give a lot of detail into what breaking changes exist in v2 compared to v1.

Therefore, 2 questions:

1. Does this package follow [SEMVER](https://semver.org)?
2. If so, what `incompatible API changes` exist between v1 and v2? ie. what changes do I need to make to my system(s) to update from v1 to v2?

**Comment by janosh** [comment]
One example of breaking changes: global npm installs (see GoogleChrome/lighthouse-ci#520)

**Comment by bryanmacfarlane** [comment]
The versions tags (v2 in this case) following the semver notion that a major version can introduce major / breaking changes.  

In this case, it's covered in the main readme [here](https://github.com/actions/setup-node#v2) and there shouldn't have been breaking changes.  However, it was a big set of changes code wise and implementation wise so we major versioned.

On the linked example, there shouldn't have been changes that would affect `npm install -g` - seems more like a permisions / runner change that would affect permissions.  The only thing that changed between v1 and v2 is how we acquire the targz before extracting.

All that said, a changelog is a good point.  I'll leave this active and mark as a doc issue.

**Comment by dmitry-shibanov** [comment]
Hello @fishcharlie. Sorry for the late response. For now, we provide all necessary information about changes in release description. Does it meet your needs?

**Comment by dmitry-shibanov** [comment]
Hello @fishcharlie. For now I'm closing the issue. If you have any concerns feel free to ping us.

**Comment by Vadorequest** [comment]
Please reopen or add a CHANGELOG.md file, even if it only leads to this issue
Updating deps is a pain, not knowing what we might break by changing actions/setup-node@v2 to actions/setup-node@v3 in our workflows creates too much pressure.
