### ISSUE TITLE
setup-node is overwriting my .npmrc that I'm setting via docker secrets.

### ISSUE THREAD

**Issue by wallentx** [actions/setup-node#242]
I just need setup-node to not try and do certain things, like all of the stuff with .npmrc that it does without any request or input from me. If I set flags for the registry, or the scope, then sure, it should go ahead and try and set those. But I'm running a self-hosted runner and I've already standardized a build workflow that utilizes best practices so that devs don't have to interface with secrets via repo settings and the workflow yaml.

I'm injecting .npmrc on my own, but setup-node blanks it out.

**Comment by dmitry-shibanov** [comment]
Hello @wallentx, just a gentle ping.

**Comment by dmitry-shibanov** [comment]
Hello @wallentx . I'm going to close the issue, because we can not reproduce it from our side. Please provide us with steps to reproduce the issue for further investigation.
