### ISSUE TITLE
Support `latest` as a version alias for the latest Node version

### ISSUE THREAD

**Issue by TomasHubelbauer** [actions/setup-node#257]
#26 discusses supporting several types of aliases. That discussion has been going on for a long time. It seems the main complications revolve around how to deal with `lts`.

For those of us who don't care about `lts` and just want `latest` so that we can test that our work works on latest Node automatically, could we please get support for `latest` first and let #26 focus on the subtleties of `lts` and how to implement that? It seems like these two aliases do not need to be grouped into a single feature release, in fact, it looks, like implementing them separately would simplify things and potentially make it possible to provide `latest` soon.

**Comment by Divlo** [comment]
Good news!
I opened a PR to allow the `current` alias. :+1:
We can maybe support both `current` and `latest` aliases but I find it more convenient to use the `current` keyword as it is how Node.js names their versions.

PR available there: #279

**Comment by panticmilos** [comment]
Hi @zdm,

Yes, this feature is under development.
