### ISSUE TITLE
Cache Size: ~0 MB (22 B)

### ISSUE THREAD

**Issue by michalsanger** [actions/setup-node#281]
I'm trying the new `cache: 'yarn'` input, but for some unknown reason the cache is created empty:
https://github.com/adeira/universe/runs/2972556811?check_suite_focus=true#step:3:19

Any idea what could be the reason or how to fix it? 
Thank you.

**Comment by dmitry-shibanov** [comment]
Hello @michalsanger. Thank you for you report. I think the root cause of the issue that you use `FORCE_COLOR`. Output from `yarn cache dir` gets extra output for color, that is why action can't find proper path and packs empty directory. If you remove `FORCE_COLOR`, action will work as expected.

**Comment by mrtnzlml** [comment]
> Output from yarn cache dir gets extra output for color, that is why action can't find proper path and packs empty directory.

Hi @dmitry-shibanov! Thanks for your suggestion. Would it be possible to improve the handling of such situations and throw an error when the path cannot be resolved? I think it would make more sense instead of trying to cache a directory that doesn't exist. 🤔

**Comment by dmitry-shibanov** [comment]
Hello @mrtnzlml. Thank you for your response. I agree with you that it makes sense to add this check. We'll keep the issue open until we add this check.

**Comment by XhmikosR** [comment]
We are using `FORCE_COLOR: 2` and it seems to work [fine](https://github.com/twbs/bootstrap/runs/3016182819?check_suite_focus=true#step:3:16). That being said, I agree this should be handled in a better way.

**Comment by dmitry-shibanov** [comment]
Hello everyone. We've added check for existing directory in scope of this [pull request](https://github.com/actions/setup-node/pull/278). If directory for cache does not exist, post step will fail.
