### ISSUE TITLE
Custom Cache key

### ISSUE THREAD

**Issue by mbrevda** [actions/setup-node#286]
The new cache option is great, but is also tightly coupled to the lock file hash. While this is a great way to ensure the cache is always a 1:1 match with the lock file, it ultimately makes the case a lot less useful in often updating, multiple branch setups - such as with dependabot. The ability to define a custom cache key would allow for longer term caches which with a wider ranges of package versions cached. To combat snowballing growth of the cache,  the key could be set to include the current month, ensuing the cache is reset one a month.

**Comment by dmitry-shibanov** [comment]
Hello @mbrevda. Thank you for your report. I'll mark your issue as an `enhancement`. We'll investigate your proposal.

**Comment by lharress** [comment]
or even the ability to set custom restore keys for when the primary key is not hit. We use a rolling cache as our fallback when the hash of the lock file does not have a hit. Makes a considerable difference running `instal` from ` few day old cache than starting from scratch.

**Comment by roikoren755** [comment]
We have a different issue that will benefit from this enhancement, or from a separate solution.

We are running a matrix of flows, with the node version changing between each flow.
Because of the way the key is built, the node version has no influence on the cache key, and all of the flows try and upload their node_modules cache using the same key, with only one of them succeeding.

The node_modules to be uploaded are also different between the node versions, with packages running different compilation depending on the version, and the way things are now, that isn't taken into consideration.

Allowing us to provide a custom cache key will solve these issues for us, but a simpler to implement fix for our issue would be to add the node version used to the cache key.

**Comment by dmitry-shibanov** [comment]
Hello everyone. By our investigation we've decided not to add support of custom cache keys. The role of caching for node is to cover the majority of use cases without deep customization. It'll help novice users to setup faster their yml files. If you need more custom logic, the preferred solution will be using the [action/cache](https://github.com/actions/cache) task.


@roikoren755, 
The current implementation of caching with common key will work for your use-case and matrix with different Node.js versions. 
We don’t cache node_modules folder (it could cause a bunch of other problems too). Instead, we cache global npm / yarn cache on machine ($HOME/.npm  or $HOME/.yarn). It means that post_install steps for packages are not cached and cache can be reused by different Node.js versions. It is approach recommended by [actions/cache](https://github.com/actions/cache/blob/main/examples.md#node---npm)

**Comment by mbrevda** [comment]
Is adding another param really that big of a deal?

**Comment by lharress** [comment]
Could we at the very least have the recommended implementation? All the node examples recommend a fallback key with good reason - restoring from something is much faster than restoring from nothing.

https://github.com/actions/cache/blob/main/examples.md#node---npm
https://github.com/actions/cache/blob/main/examples.md#node---yarn

**Comment by maxim-lobanov** [comment]
@mbrevda , [from ADR](https://github.com/actions/setup-node/blob/main/docs/adrs/0000-caching-dependencies.md#goals--anti-goals)
> We don't pursue the goal to provide wide customization of caching in scope of actions/setup-node action. The purpose of this integration is covering ~90% of basic use-cases. If user needs flexible customization, we should advice them to use actions/cache directly.

Customizing of caching key is definitely not basic use-case so we should use `actions/cache` directly for this use-case. We don't want to duplicate functionality of `actions/cache` in scope of `actions/setup-node`. 

@lharress , `restore-keys` doesn't make any sense for setup-node integration of caching.
> `restore-keys` is an ordered list of alternative keys to use for finding the cache if no cache hit occurred for primary-key.

Example in `actions/cache` repo recommends to set `restore-keys` to `${{ runner.os }}-node-`. We never push cache for this key so the cache for this key will always be empty and won't be restored.

**Comment by lharress** [comment]
@maxim-lobanov I do not believe that is the case, if it is then the documentation is misleading.

https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#matching-a-cache-key

>You can provide a list of restore keys to use when there is a cache miss on key. You can create multiple restore keys ordered from the most specific to least specific. The cache action searches for restore-keys in sequential order. When a key doesn't match directly, the action searches for keys prefixed with the restore key. If there are multiple partial matches for a restore key, the action returns the most recently created cache.

Specifically, this piece;
>When a key doesn't match directly, the action searches for keys prefixed with the restore key.

Unless I am misunderstanding, this mens if I have 1 item in the cache with the key `node-cache-one` and then I attempt a restore using the key  `node-cache-two` and a restore key of `node-cache-` it will cause a cache miss, but then when searching for the prefix `node-cache-` it will find `node-cache-one` and restore from there.

**Comment by maxim-lobanov** [comment]
@lharress let me follow up with my team regarding it and return back with answer

**Comment by lharress** [comment]
@maxim-lobanov Any update on this? Could the issue be re-opened while it's being discussed?

**Comment by ngraef** [comment]
Related: #328 requests the addition of a default restore key.

**Comment by dbrugger** [comment]
I would also like this. My use case is when changing the yarn setup from a local repo to a global cache, the cache needs to be busted.
The lock file does not change in this case - does someone know a good way to get it changed without changing packages?
An alternative to a completely custom cache key could be a custom pre- or suffix.

**Comment by ajnozari** [comment]
This is causing an issue in our Multiplatform CICD where all but the last run to finish cannot utilize the cache as it is overwritten.  This causes each run to behave inconsistently.

The lack of this feature confuses me greatly coming from such an amazing action.
