### ISSUE TITLE
Why hasn't version been removed?

### ISSUE THREAD

**Issue by jsoref** [actions/setup-node#298]
https://github.com/actions/setup-node/blob/38d90ce44d5275ad62cc48384b3d8a58c500bb5f/action.yml#L26-L29

2019 was a long time ago...

**Comment by nickofthyme** [comment]
The `deprecationMessage` creates a lot of noice if used on many workflow jobs.

I'm happy to put up a PR to remove this if there is no ulterior reason for keeping it around. Thanks 🙏 

![image](https://user-images.githubusercontent.com/19007109/151068183-774512e9-e1e4-47bd-a662-6ff79bace46d.png)

**Comment by jsoref** [comment]
Your workflows should really be upgraded to not mention that property. I don't think that removing the field from the `action.yml` will improve your log entries.

That said, I'd be happy w/ someone else making the PR (I'm also willing, but I prefer to do work when there's some sign that the repository will accept my PR, and I have no evidence of this).

**Comment by nickofthyme** [comment]
Ugh yeah you are right, I forgot to remove passing the variable in a custom action. Thanks.

Exactly, if they would accept removal I'm happy to do it. TBD...

**Comment by jsoref** [comment]
That said, this Issue was given a tag last month by someone who has committed to this repository in the past month, so maybe it's a _bit_ more alive than when I filed the issue. Wanna make the PR?

**Comment by nickofthyme** [comment]
True, yeah I can get to it in the next few weeks.

**Comment by dmitry-shibanov** [comment]
Hello everyone. The version input was removed in the v3 tag. For now I'm going to close the issue. If you have any concerns feel free to ping us.
