### ISSUE TITLE
Post Node X.X caching skipped upon job failure

### ISSUE THREAD

**Issue by johnameyer** [actions/setup-node#309]
Hi there, really happy to see support for caching in this tool now. However, it came as a surprise to me that the action does not run the post step if the job fails for some other reason ([see example](https://github.com/johnameyer/cards-ts/runs/3238202631?check_suite_focus=true)), which led to a cold cache and re-fetching the next time the action ran. Would it be possible to expose a parameter to run the cleanup step on every job, regardless of final job status or document why this isn't the default behavior?

(I understand that you are trying to keep the scope of the caching functionality small but this seems like a npm-client-ignorant solution and a nice win for speeding up future)

**Comment by maxim-lobanov** [comment]
Hello @johnameyer ,
the main reason why we shouldn't save cache for failed builds - we can't be sure what exactly step fails. If `npm install` / `yarn install` steps fail - saved cache can be broken and can fail further builds.

**Comment by johnameyer** [comment]
It's true that an install step could fail, but (getting back to my request) wouldn't it be possible to pass those step names as an optional parameter to the action where unless those specified steps fail the post step would run? (I know that [it is now possible to grab previous steps' outcome](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#steps-context) but not exactly sure what the wiring would look like for that or if the actions framework would allow for that level of dynamism.

**Comment by fg-j** [comment]
We use the setup node action with caching on a test pull request workflow that we expect will fail frequently. Part of the reason we want dependency caching here is _because_ we want a faster feedback loop for when contributors' PRs are failing! (e.g. https://github.com/paketo-buildpacks/paketo-website/runs/3547938570?check_suite_focus=true)

**Comment by dmitry-shibanov** [comment]
Hello everyone. I'm going to close the issue, because [current behaviour](https://github.com/actions/setup-node/blob/main/action.yml#L38-L39) is expected one. As @maxim-lobanov mentioned we can't be sure what exactly step failed.

**Comment by johnameyer** [comment]
@dmitry-shibanov I understand the current behavior, but I do not understand why we cannot pass in the the install step and check whether that step has failed? As I linked it is possible to see the status of previous steps so we can tell if a certain step failed. This part of the question has not been answered.

**Comment by villelahdenvuo** [comment]
I think it's a good default behavior, but it would be very nice if there was an option to always cache.
