### ISSUE TITLE
Use release notes to communicate maintenance work if needed

### ISSUE THREAD

**Issue by HonkingGoose** [actions/setup-node#312]
I was very confused when I got a update proposal from my "update bot" to bump `actions/setup-node` from `v2.3.0` to `v2.3.1`. The change-logs were not clear enough for me about _why_ you needed to turn this behavior off temporarily. So I tried to get clarification from the maintainers: https://github.com/actions/setup-node/pull/308#issuecomment-892098563.

Turns out this was a "quick-fix" to enable maintenance behind the scenes (https://github.com/actions/setup-node/pull/310). I know maintenance is needed, and that sometimes you need to turn things off to be able to do the work. So this is not a complaint about the maintenance itself, only about the communication about the maintenance.

I'd like to propose you use the [release notes](https://github.com/actions/setup-node/releases) to communicate to the end-users.

A message like this would have made things clear right away:

```markdown
We need to perform some behind-the-scenes maintenance. To do this work we need to disable `feature_name`. 

We will release a newer version of this action that reverts to the old situation once we're done.
```

And then when the maintenance is done:

```markdown
We're done with the maintenance and have enabled `feature_name` again.
Thank you for your patience/understanding.
```

**Comment by dmitry-shibanov** [comment]
Hello @HonkingGoose. Thank you for your report. Sorry for not providing a clear description in release notes. It was a quick maintaining fix, that is why it produced some noise. For now we try to provide clear description. 

For now I'm closing the issue. If you have any concerns feel free to ping us.
