### ISSUE TITLE
`cache: yarn` doesn't work for a self hosted runner

### ISSUE THREAD

**Issue by yhaskell** [actions/setup-node#313]
In the documentation, there is a section called `Caching packages dependencies`, which suggests to use `cache: yarn` for caching yarn dependencies.

On GitHub runners, it works, since GitHub runners have both node and yarn already installed, and therefore there is no problem.
On self-hosted runner, this is not a case.

Which leads us to a catch-22 situation: setup-node action actually expects node to be installed (together with yarn).

Therefore, the action itself fails (since it cannot run yarn during setup).

My proposal is maybe to actually install yarn during the action, at least if we need it for action to success.

Thanks!

**Comment by DirkLachowski** [comment]
If you self-host the runner, why not simply install yarn on it?

**Comment by yhaskell** [comment]
Problem is that yarn is an application that uses node. setup-node installs node. but setup-node cannot install node, because it uses the program that is written in node to do the caching.

**Comment by DirkLachowski** [comment]
Maybe i got you wrong, but if you host your own runner, you can install whatever you want so the software is already there before your action starts. Make a vm with a custom image containing node. Only after that, install the github runner sw.

**Comment by yhaskell** [comment]
So, basically the idea is to not use setup node to set up node on the self hosted runners?

**Comment by BeeJayJayn** [comment]
Okay, do we have a solution for this? 

Sure we can install it on the self-hosted runners, but the whole error is stupid...

**Comment by yhaskell** [comment]
I totally agree.

And I still think that setup-node should install yarn, atleast when cache: yarn is set to be true

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by n0mer** [comment]
@DirkLachowski how would you use multiple versions of node.js? `setup-node` installs node.js, and it should install `yarn` as well

**Comment by dmitry-shibanov** [comment]
Hello everyone! It's an expected behavior. If the runner does not have appropriate tool preinstalled it's expected that caching will fail. Please preinstall yarn to your self-hosted runners by your own.
I'm closing the issue.

**Comment by yhaskell** [comment]
Yes, but the problem is that the tool depends on node, which you're taking care of installing!

**Comment by yhaskell** [comment]
Basically, I have to install node, to be able to install node. That sounds counterintuitive, and wrong

**Comment by paschaldev** [comment]
I came here stuck with this problem in 2023 and it seemed like few people didn't understand what @yhaskell was saying but I do. Still looking for a way out
