### ISSUE TITLE
Is there a way to partially cache dependencies?

### ISSUE THREAD

**Issue by oscard0m** [actions/setup-node#321]
### Context
Tried to add `cache: npm` to TypeScript's workflows but we become with a blocker: **Is it possible to not cache some of the dependencies?**: 

Issue: https://github.com/microsoft/TypeScript/pull/44924
Originally asked [here](https://github.com/microsoft/TypeScript/pull/44897#issuecomment-875156244)

---

I would like to know if there is a way to cache most of the dependencies but to make sure some of them are not being cached with `actions/setup-node` or `actions/cache`. As far as I understand there's not an option with [latest `cache` option ](https://github.com/actions/setup-node/issues/304).

**Comment by dmitry-shibanov** [comment]
Hello @oscard0m. Thank you for your report. The task does not support of caching partially dependencies. Caching in setup-node use global directory from `npm config get cache` to save cache, that is why i think it's not available to skip some dependencies from being cached, because all dependencies are saved in this directory.

**Comment by oscard0m** [comment]
> Hello @oscard0m. Thank you for your report. The task does not support of caching partially dependencies. Caching in setup-node use global directory from `npm config get cache` to save cache, that is why i think it's not available to skip some dependencies from being cached, because all dependencies are saved in this directory.

Thanks for the quick and concise reply @dmitry-shibanov 👏🏽 .

I would like to explore what are the existing possibilities on supporting this. For instance, I was checking [`cacache`](https://www.npmjs.com/package/cacache) lib (the one [used by npm](https://docs.npmjs.com/cli/v7/commands/npm-cache#details)) but, for that, I'm not sure if I should address this under NPM's GitHub or this issue could be a good place to discuss and end up doing a spike for this.

What do you think @dmitry-shibanov

**Comment by maxim-lobanov** [comment]
@oscard0m , unfortunately, we don't have much context with `cacache` tool so probably npm team will have more context.

May be some tricks with `npm uninstall` and removing non-cached dependencies from package-lock.json (or having two package-lock.json files) can help here. But it doesn't look like easy and good solution actually.

Another possible solution is adding the following step after at the end of your workflow (approximate code, I didn't test it but can help to understand the idea):
```yml
- run: |
    cache_path=$(npm config get cache)
    dep_path="$cache_path/dependencyname"
    rm -rf $dep_path
  shell: bash
```

The single concern from my side is that we would like to keep caching functionality in setup-node [as simple as possible](https://github.com/actions/setup-node/blob/main/docs/adrs/0000-caching-dependencies.md#goals--anti-goals).
> We don't pursue the goal to provide wide customization of caching in scope of actions/setup-node action. The purpose of this integration is covering ~90% of basic use-cases. If user needs flexible customization, we should advice them to use actions/cache directly.

**Comment by oscard0m** [comment]
Thanks for getting back to me @maxim-lobanov and thanks for your feedback and suggestion. My next steps will be:
1. To research and maybe open an issue to `npm` team discussing this topic
2. To get back to my TypeScript PR depending on the solution offered by `npm`
3. Depending on the suggested solution by `npm`, maybe it could be interesting to extend it to `actions/cache` (in `actions/setup-node` no since the goal is to keep it simple with the basic use cases).

In the meantime, I'm proceeding to close this issue and refer to it in the steps I previously mentioned.
