### ISSUE TITLE
How is the caching logic supposed to work the first time you use this action?

### ISSUE THREAD

**Issue by tstirrat15** [actions/setup-node#334]
If you've got `cache` defined, it starts by [attempting to restore the cache](https://github.com/actions/setup-node/blob/main/src/main.ts#L55). If the cache doesn't exist (such as on your first usage of `cache`), [it errors out](https://github.com/actions/setup-node/blob/041bafb67276a76a9cc88cd8a4e99165e9eb287d/src/cache-restore.ts#L47). Am I missing something?

**Comment by tstirrat15** [comment]
Possibly related to #329

**Comment by tstirrat15** [comment]
Never mind - not an issue.

For people coming after me, this differs from `setup-ruby` (and presumably from other setup actions) in that it doesn't automatically do the install for you, and it does the cache setting as a post-run hook instead of as a part of the setup step.

For the maintainers: can this be called out in the documentation? This wasn't clear or intuitive.

**Comment by markgoho** [comment]
@tstirrat15 for folks who've previously set up caching node modules via `actions/cache` this is exactly how that worked

you're comparing this to another runtime/action and expecting it to work the same and then asking the maintainers to update documentation to suit that expectation

why would we add documentation that says "if you're familiar with some other runtime and the way it caches dependencies, this is different!"

**Comment by tstirrat15** [comment]
Because [other](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#using-yarn) [CI](https://docs.travis-ci.com/user/caching/#yarn-cache) [providers](https://docs.travis-ci.com/user/languages/python/#pip) [present](https://docs.travis-ci.com/user/caching/#pip-cache) a [unified](https://circleci.com/developer/orbs/orb/circleci/node) [interface](https://circleci.com/developer/orbs/orb/circleci/python#commands-install-packages) for installing and caching packages?

It's not an unreasonable expectation, coming from another CI provider, to expect Github's CI provider to behave similarly.

**Comment by markgoho** [comment]
you made the comparison between how the Node.js action caches dependencies and how the Ruby action caches dependencies and now you're comparing GitHub Actions to CircleCI and Jenkins

would you like to keep moving the goalposts? maybe we should next make comparisons between git and subversion?
