### ISSUE TITLE
Use recommended release strategy

### ISSUE THREAD

**Issue by damccorm** [actions/setup-node#35]
We should be using the release strategy specified by https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations

To get there, we need to:
1) Create a `releases/v1` branch and move the `v1` tag and future releases there
2) Warn that we will deprecate the master branch and that you should attach to `v1` instead. We will support master in a warned but deprecated state for ~1 month.
3) Switch the warning to an error on master. Remove `node_modules` from the master branch. We will stay in this state for ~1 month.
4) Remove the error on master.

During steps 2 and 3, we need to be extra careful to not check the warning/error into the releases branch.

**Comment by bryanmacfarlane** [comment]
We're not doing this.  Instead, we're moving toward ncc and packing.  Will open a separate issue
