### ISSUE TITLE
 Node v17 support

### ISSUE THREAD

**Issue by coderaiser** [actions/setup-node#350]
**Description:**
Please add [node v17](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V17.md) support.

**Justification:**
Justification or a use case for your proposal.

**Are you willing to submit a PR?**

**Comment by dmitry-shibanov** [comment]
Hello @coderaiser. You can use this snippet to set up node 17:
```
- uses: actions/setup-node@v2
  with:
    node-version: 17
```

For now I'm closing the issue. If you have any concerns feel free to ping us.
