### ISSUE TITLE
Action warnings cause an error to be returned

### ISSUE THREAD

**Issue by 0xdeafcafe** [actions/setup-node#354]
**Description:**
A warnings returned while the action is run will cause the workflow to error.

**Action version:**
v2.4.1

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Node 16.13.0 using yarn

**Repro steps:**  
Workflow.yml

```yml
- name: Setup Node.js
  uses: actions/setup-node@v2.4.1
  with:
    node-version: '16'
    cache: 'yarn'
    cache-dependency-path: yarn.lock
```

The repository is also available [here](https://github.com/getbeak/nest).

**Expected behaviour:**
Node gets setup correctly, and the rest of the workflow continues.

**Actual behavior:**
It fails due to a warning about the license field missing in the `package.json`. The exact same config seems to be working fine in [this](https://github.com/getbeak/beak) repo however, which is pretty bizarre.

```
Run actions/setup-node@v2.4.1
  with:
    node-version: 16
    cache: yarn
    cache-dependency-path: yarn.lock
    always-auth: false
    check-latest: false
    token: ***
  env:
    SHA: 08a818
Attempting to download 16...
Acquiring 16.13.0 - x64 from https://github.com/actions/node-versions/releases/download/16.13.0-1386584131/node-16.13.0-linux-x64.tar.gz
Extracting ...
/usr/bin/tar xz --strip 1 --warning=no-unknown-keyword -C /home/runner/work/_temp/25fbe9eb-9f33-4e66-a470-afcca2472a62 -f /home/runner/work/_temp/3bd3f952-6099-4d9e-9a97-db484619b083
Adding to the cache ...
Done
/usr/local/bin/yarn --version
1.22.17
/usr/local/bin/yarn cache dir
warning package.json: No license field
/home/runner/.cache/yarn/v6
Error: warning package.json: No license field
```

**Comment by 0xdeafcafe** [comment]
This issue could be related to https://github.com/actions/setup-node/issues/352, however it was pointed out that may be due to mismatch of the caching logic and npm version.

**Comment by dmitry-shibanov** [comment]
Hello everyone. We released a new [version](https://github.com/actions/setup-node/releases/tag/v2.5.1) to resolve a bug to fail action on the warning. 
For now I'm going to close the issue. If you have any concerns feel free to ping us.
