### ISSUE TITLE
Allow an option to specify specific npm version for runners

### ISSUE THREAD

**Issue by Thatkookooguy** [actions/setup-node#361]
**Description:**
When working on a project, I usually update npm to the latest supported version for the node.js version I use. So the version of node.js and npm might not be the same as the default install.

**Justification:**
Right now, the runner complains about my package-lock.json file not matching the npm version installed on the runner

**Are you willing to submit a PR?**

sure!

**Comment by dmitry-shibanov** [comment]
Hello @Thatkookooguy. Thank you for your report. I think we already have the similar [issue](https://github.com/actions/setup-node/issues/213). Does it reflect your proposal?

**Comment by dmitry-shibanov** [comment]
Hello @Thatkookooguy, just a gentle ping.

**Comment by Thatkookooguy** [comment]
Yes, it's the same issue

**Comment by dmitry-shibanov** [comment]
Hello @Thatkookooguy. Thank you for your answer. I'll close your issue as a duplicate to track it in initial one.
