### ISSUE TITLE
https://github.com/actions/setup-node/issues/365

### ISSUE THREAD

**Issue by Tobats1992** [actions/setup-node#365]
App detection tool
App Monitoring Tool
This page is only used to locate your browser and network information, and does not involve your private information. Please feel free to use it.
This page is only used to locate your browser and network information, and does not involve your privacy information.
Basic information monitoring
Browser language (Language)
en
Device information (userAgent)
Mozilla/5.0 (Linux; Android 9; CPH2083 Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.45 Mobile Safari/537.36 BNC/1.10.0 (Android 2.37.4)
Operating System (Platform)
Android 9
Use the browser (Explore)
WebView
Information of Phone
OPPO CPH2083
Api ws response speed (Api ws response speed)
App_be
372 ms
connection succeeded
 ·
Currently used
App_be
489 ms
connection succeeded
 ·
App_bh
Connection failed
 ·
User IP (IP)
223.25.59.248
User location (Location)
Philippines Makati
Network operator (isp)
Download speed
0.00 Kb/s

**Comment by dmitry-shibanov** [comment]
Hello @Tobats1992. Could you please fill out the issue using the template ?
For now I'm closing the issue, but feel free to ping us as soon as you fill out the issue according to the template.
