### ISSUE TITLE
Version v2 does not support node version files as mentioned in the documentation

### ISSUE THREAD

**Issue by gabriel-kohen-by** [actions/setup-node#369]
**Description:**
When using this command with version v2[ as shown here](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#check-latest-version), I'm getting:
`
Warning: Unexpected input(s) 'node-version-file', valid inputs are ['always-auth', 'node-version', 'architecture', 'check-latest', 'registry-url', 'scope', 'token', 'cache', 'cache-dependency-path', 'version']
`
If specifying a later version such as:
```
      - uses: actions/setup-node@v2.5.0
        with:
          node-version-file: '.nvmrc'
```
It works fine

**Action version:**
v2

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
nvm and node v14

**Repro steps:**  
Use the following:
```
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
```
As specified in the documentation

**Expected behavior:**
The action should be able to use the node version file input.

**Actual behavior:**
v2 warns it knows no such input parameter

We should either update version 2 to include this as documented or change the documentation to indicate a use of other version.

**Comment by havenchyk** [comment]
I think it's only warning, https://github.com/actions/setup-node/blob/d08cf222111d5c1d21b3cd4b958937f818d10d9a/__tests__/installer.test.ts#L580-L602

**Comment by dmitry-shibanov** [comment]
Hello @gabriel-kohen-by. Thank you for your report. We've updated the tag v2 to point to 2.5.0.
For now I'm closing the issue. If you have any concerns feel free to ping us.
