### ISSUE TITLE
Unable to set global npm version, npm v8 is always used...

### ISSUE THREAD

**Issue by busticated** [actions/setup-node#376]
**Description:**
I need to run my action using `npm@6`. Despite installing the correct version globablly, `npm@8` is always used and my action fails. i see a series of warnings in my logs like:

```
my-package: npm WARN EBADENGINE Unsupported engine {
my-package: npm WARN EBADENGINE   package: '@particle/tmp@2.0.1',
my-package: npm WARN EBADENGINE   required: { node: '>=10', npm: '6.x' },
my-package: npm WARN EBADENGINE   current: { node: '12.22.7', npm: '8.1.0' }
my-package: npm WARN EBADENGINE }
```

i first noticed the failure on monday (12/6/2021), the last successful run was ~7days ago (11/30/2021 - [log](https://github.com/particle-iot/cli/runs/4374523491?check_suite_focus=true))

inspecting the logs for both runs, i see `Current runner version: '2.284.0'` (success) vs. `Current runner version: '2.285.1'` (fail). looks like the earliest failure happened under `Current runner version: '2.285.0'` which was released ~8days ago ([info](https://github.com/actions/runner/releases/tag/v2.285.0))

running locally (outside of GH Actions entirely but within a comparable environment), i'm able to reproduce the warnings and subsequent failures by simply using `npm@8`. at no point does my code attempt to install `npm@8`. reverting to `npm@6` and re-running fixes things.

the `Unsupported engine` warnings are triggered by running a tool which itself runs `npm` via child-process in a descendant directory (see [here](https://github.com/oclif/dev-cli/blob/v1.26.8/src/tarballs/build.ts#L67)). this is what my `npm run build` command does under the hood.

interestingly, Node.js `v12.22.7` ships w/ `npm@6.14.15` by default (see ~pg10 [here](https://nodejs.org/en/download/releases/)) so something is explicitly pulling in `npm@8.1.0` _somewhere_

**Action version:**
`v2.5.0`, `v2.4.1`, and `v2.4.0`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
node: `v12.22.7`
npm: `6.14.15` (but `npm@8.1.0` is always used)

**Repro steps:**  
Using an action step like:

```
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: |
          npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Debug
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          echo ":::: NPM SETTINGS"
          npm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
          node --version
          npm --version
          npm whoami
          npm i npm@6 --global
          npm run build
```

(note: using either `ubuntu-18.04` or `ubuntu-latest` yields the same result)

**Expected behavior:**

`npm run build` command succeeds, `npm@6` is used

**Actual behavior:**

`npm run build` fails with the following log output:

```
my-package: npm WARN EBADENGINE Unsupported engine {
my-package: npm WARN EBADENGINE   package: '@particle/tmp@2.0.1',
my-package: npm WARN EBADENGINE   required: { node: '>=10', npm: '6.x' },
my-package: npm WARN EBADENGINE   current: { node: '12.22.7', npm: '8.1.0' }
my-package: npm WARN EBADENGINE }
```

`npm@8` is used despite previously installing `npm@6` via `npm i npm@6 --global` and despite Node.js `v12.22.7` shipping with `npm@6.14.15` by default

**Comment by busticated** [comment]
i should add: this pipeline has been working without issue for _months_. my last successful run was ~7days ago (11/30/2021 - [log](https://github.com/particle-iot/cli/runs/4374523491?check_suite_focus=true)). i noticed things failing starting yesterday (12/6/2021)

**Comment by ethomson** [comment]
> my last successful run was ~7days ago (11/30/2021 - log).

Your repository is private and I cannot see the runs.  When I try to reproduce this, I am running the expected versions of node and npm after running setup-node.

```yaml
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Debug
        env:
          NPM_TOKEN: foobar
        run: |
          echo ":::: NPM SETTINGS"
          node --version
          npm --version
```

shows:

```
:::: NPM SETTINGS
v12.22.7
6.14.15
```

Is this what you're seeing?  Or are you seeing something different from `node --version` and `npm --version`?  Is this only failing in the `npm run build` step or are you seeing odd version numbers _before_ that step?

**Comment by busticated** [comment]
@ethomson thanks for taking a look 🙏 

>  Is this only failing in the npm run build step

correct. i'm running a tool via the `npm run build` command that then builds my source code. the line that is triggering the warnings is [here](https://github.com/oclif/dev-cli/blob/47fb493c523bd417d39cb83aecd4aac1c6bb505b/src/tarballs/build.ts#L67)

> Your repository is private and I cannot see the runs

as you are a Github employee, i'm happy to grant you access. fwiw, we are a Github Enterprise customer ([info](https://github.com/enterprises/particle)). if it's helpful, i can file a ticket.

**Comment by busticated** [comment]
ok, should have done this from the beginning but better late than never. running locally, i'm able to reproduce the warnings and subsequent failures by simply running under `npm@8`.

so the question really boils down to: why would a call to execute `npm` from a node.js script cause the base environment's `npm` instance to be used instead of the one configured via `setup-node`?

**Comment by busticated** [comment]
I should also note that I’m using the setup-node action to control node + npm versions as well

```
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: |
          npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
```

**Comment by dmitry-shibanov** [comment]
Hello @busticated. Thank you for your report. Could you please provide a public repository to reproduce the issue. I've tried from my side, but it works as expected.

**Comment by ethomson** [comment]
> so the question really boils down to: why would a call to execute npm from a node.js script cause the base environment's npm instance to be used instead of the one configured via setup-node?

I don't have an answer for you - I'd love to know if

```
echo ":::: NPM SETTINGS"
node --version
npm --version
```

is producing the expected values?

Expanding on this, I'd love to know what you're seeing here:

```
        run: |
          echo ":::: NPM SETTINGS"
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          node --version
          npm --version
          node -e 'child_process.spawnSync("npm", ["--version"], { stdio: "inherit" });'
          node -e 'child_process.spawnSync("which", ["npm"], { stdio: "inherit" });'
          npm i npm@6 --global
          npm --version
          node -e 'child_process.spawnSync("npm", ["--version"], { stdio: "inherit" });'
          node -e 'child_process.spawnSync("which", ["npm"], { stdio: "inherit" });'
```

For this, I get all the expected outputs:

```
:::: NPM SETTINGS
16
v12.22.7
17
6.14.15
18
6.14.15
19
/opt/hostedtoolcache/node/12.22.7/x64/bin/npm
21
/opt/hostedtoolcache/node/12.22.7/x64/bin/npm -> /opt/hostedtoolcache/node/12.22.7/x64/lib/node_modules/npm/bin/npm-cli.js
22
/opt/hostedtoolcache/node/12.22.7/x64/bin/npx -> /opt/hostedtoolcache/node/12.22.7/x64/lib/node_modules/npm/bin/npx-cli.js
23
+ npm@6.14.15
24
updated 1 package in 15.958s
25
6.14.15
26
6.14.15
27
/opt/hostedtoolcache/node/12.22.7/x64/bin/npm
```

If you're seeing this, too, then I think that your question here is very interesting, indeed:

> so the question really boils down to: why would a call to execute npm from a node.js script cause the base environment's npm instance to be used instead of the one configured via setup-node?

I'd love to know how you're invoking npm from this Node.js script.

**Comment by busticated** [comment]
ok, well adding `sudo -s -E npm i npm@6 --global` just prior to calling `npm run build` fixes things. so, yay? 

i suppose you can close this out - thanks for the help 🙏 👍

**Comment by 6tukat** [comment]
oho tenku

**Comment by 6tukat** [comment]
god blesu evribare

**Comment by dmitry-shibanov** [comment]
Hello everyone. For now I'm closing the issue. If you have any concerns feel free to contact us.
Thank you for the help @ethomson .
