### ISSUE TITLE
Error: getCacheEntry failed: Cache service responded with 500 in new workflow

### ISSUE THREAD

**Issue by dominikg** [actions/setup-node#378]
**Description:**
setup-node fails with an error
```shell
Run actions/setup-node@v2
  with:
    node-version: 16
    cache: pnpm
    cache-dependency-path: **/pnpm-lock.yaml
    always-auth: false
    check-latest: false
    token: ***
Found in cache @ /opt/hostedtoolcache/node/16.13.0/x64
/opt/hostedtoolcache/node/16.13.0/x64/bin/pnpm store path
/home/runner/.pnpm-store/v3
Error: getCacheEntry failed: Cache service responded with 500
```

**Action version:**
setup-node@v2

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
node 14 + 16
pnpm 6.23

**Repro steps:**  
Workflow here https://github.com/svitejs/vite-plugin-env-config/blob/main/.github/workflows/ci.yml

It uses setup-node twice:
- first  to get npm and run `npm i -g pnpm` (instead of using pnpms custom action)
https://github.com/svitejs/vite-plugin-env-config/blob/9fc3bbddc0b93583a3f068e5f0b8a6ecc0275a0a/.github/workflows/ci.yml#L27

- second with pnpm cache option set to use automatic caching
https://github.com/svitejs/vite-plugin-env-config/blob/9fc3bbddc0b93583a3f068e5f0b8a6ecc0275a0a/.github/workflows/ci.yml#L31

**Expected behavior:**

setup succeeds

**Actual behavior:**
setup fails
log shows a 500 error for cache service
https://github.com/svitejs/vite-plugin-env-config/runs/4494014103?check_suite_focus=true#step:5:12

**Additional information**

* The repo is very new and cloned from a template. other repos with a similar setup don't show this behavior
* These are the initial workflow runs, there hasn't been a success. Maybe some initializaion failed?

**Comment by dominikg** [comment]
seems to be related to https://github.com/actions/cache/issues/698

**Comment by goeh** [comment]
Same error here with a new Java+Gradle (ubuntu-latest) workflow I created yesterday.
```
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
```

```
Creating settings.xml with server-id: github
Writing to /home/runner/.m2/settings.xml
Error: getCacheEntry failed: Cache service responded with 500
```

**Comment by gregnrobinson** [comment]
I am also seeing similar behaviour in my workflows...

https://github.community/t/getcacheentry-failed-id-1-innerexception-null-message-database-pool-defaultpartitionpool-is-full-raise-the-maxdatabaselimit-or-use-a-different-pool/217152

https://github.com/gregnrobinson/kube-secrets/runs/4498019768?check_suite_focus=true

**Comment by egonbraun** [comment]
Had a similar issue yesterday with the `setup-python` action, tried again today and it is working fine. It seems like it was a temporary issue. I check GitHub status page and couldn't find any incident related to that though. The only one I found was this: https://www.githubstatus.com/incidents/tc051c121cs7

But it is not related.

**Comment by dominikg** [comment]
workaround is to simply disable cache parameters by commenting them. Will download more dependencies but no more errors)

**Comment by dominikg** [comment]
upstream issue discussion hints that this may be fixed now

https://github.com/actions/cache/issues/698#issuecomment-992130400

still setup-node may want to think about how to handles caching related errors.

**Comment by paulrberg** [comment]
Can confirm that it's fixed now.

**Comment by dmitry-shibanov** [comment]
Hello everyone. Thank you for your report. I'm going to close the issue, because the initial one was resolved. If you have any concerns feel free to ping us.
