### ISSUE TITLE
Workflow fails to publish to GitHub Package Registry if repo owner login casing does not match scope casing

### ISSUE THREAD

**Issue by JamesMGreene** [actions/setup-node#38]
I've been testing out an Action I was building today and having issues when verifying a step to publish the package to the GitHub Package Registry, which instead attempts to publish the package to the original NPM Registry:

https://github.com/JamesMGreene/test-repo/runs/199833215

After trying to track down the issue for longer than I care to mention as I went down a few incorrect rabbit holes, I believe the root cause is pretty simple: my GitHub username has uppercase letters in it but my NPM scoped package name, by necessity for validation, is all lowercased.

This creates a casing mismatch between the `.npmrc` file contents that get generated by the `setup-node@v1` Action and the scope used by `npm publish` in a later Step. Some highlights from the Workflow Run logs:

<img width="1044" alt="Screen Shot 2019-08-21 at 5 43 09 PM" src="https://user-images.githubusercontent.com/417751/63473575-9301e400-c43b-11e9-90e5-d35bc5854c3b.png">

Luckily, the fix for this should also be pretty simple: to lowercase the repo owner's login scope that gets written to the `.npmrc` file. 👌

**Comment by AllanOricil** [comment]
I still have this bug. How did you fix it?

![image](https://user-images.githubusercontent.com/55927613/112751116-2d38ef00-8fc4-11eb-9e2b-7d4545199cfa.png)
