### ISSUE TITLE
ESLint (stylish) pattern matcher not annotating output

### ISSUE THREAD

**Issue by wopian** [actions/setup-node#403]
**Description:**

The default output format of ESLint 8 (stylish) does not appear to match the regex defined in the [pattern matcher](https://github.com/actions/setup-node/blob/main/.github/eslint-stylish.json) as no annotations are created with ESLint errors.

**Action version:**

`setup-node@2.5.1` (via `@2` at time of action run)

**Platform:**
- [x] Ubuntu
- [ ] macOS (untested)
- [ ] Windows (untested)

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

Node: `16`
Yarn: `1.22.17`

**Repro steps:**

1. Fork https://github.com/wopian/setup-node-test
2. Create a new branch with changes that would result in ESLint errors to be printed in terminal
3. Publish branch and open PR
4. Check `Files changed` and note no annotations are printed when action job fails
5. Append `--format=compact` to the `lint` command in `package.json`
6. Check `Files changed` and note annotations are now printed when action job fails

Example pull requests with:
1. Default formatter (stylish, no annotations)
   - https://github.com/wopian/setup-node-test/pull/1/files
2. Compact formatter (annotations created)
   - https://github.com/wopian/setup-node-test/pull/2/files

**Expected behavior:**

Action Annotations to appear in Action log and Files Changed tab of pull requests with the default output format of ESLint 8

**Actual behavior:**

Action Annotations only appear when using the compact output format (`--format=compact`)

---

In case annotations are deleted when Action logs are deleted, screenshots of the two output formats:

<details>
<summary>Files changed with default format, showing no annotations</summary>
<img width="464" alt="Screenshot 2022-01-11 at 15 43 58" src="https://user-images.githubusercontent.com/3440094/148974375-f1ed28e0-aae0-46fa-9283-7ca6ffba9268.png">
</details>

<details>
<summary>Files changed with compact format, showing annotations</summary>
<img width="532" alt="Screenshot 2022-01-11 at 15 42 40" src="https://user-images.githubusercontent.com/3440094/148974184-5ed8f87f-4fc3-45a0-81b6-c4e989666a82.png">
</details>

**Comment by wopian** [comment]
Checking the unescaped regexes in the pattern matcher, it seems to still be correct at matching the error message and file line formats of the default stylish output. 

Is it possible there was a change in how the pattern matcher looping property functions?

**Comment by dmitry-shibanov** [comment]
Hello @wopian. Thank you for your report. We'll investigate the issue.

**Comment by wopian** [comment]
The lack of annotations is due ANSI escape codes when `FORCE_COLOUR` is set.

E.g:

```
[0m  [2m4:1[22m  [31merror[39m  Unexpected var, use let or const instead     [2mno-var[22m[0m
[0m  [2m5:1[22m  [31merror[39m  Delete `··`                                  [2mprettier/prettier[22m[0m
[0m  [2m5:9[22m  [31merror[39m  'result' is assigned a value but never used  [2mno-unused-vars[22m[0m
```

Compared to:

```
4:1  error  Unexpected var, use let or const instead     no-var
5:1  error  Delete `··`                                  prettier/prettier
5:9  error  'result' is assigned a value but never used  no-unused-vars
```

**Comment by gowridurgad** [comment]
Hi @wopian, Sorry for the delayed response, As you have mentioned, the issue appears to be with the upstream pattern matcher itself and not related to setup-node. We will proceed to close this issue for now. If you need further assistance or encounter any related concerns, please feel free to reach out.
