### ISSUE TITLE
Can `node_modules` be cached if a Node.js version is supplied?

### ISSUE THREAD

**Issue by joneshf** [actions/setup-node#406]
**Description:**

As I understand the documentation about caching both in [this repo](https://github.com/actions/setup-node/blob/f099707f6e7a91b89cdebdeca599fc76cc8bf088/docs/advanced-usage.md#caching-packages-dependencies) and in the upstream [`actions/cache` repo](https://github.com/actions/cache/blob/611465405cc89ab98caca2c42504d9289fb5f22e/examples.md#node---npm), the reason `node_modules` is not recommended to cache is because dependencies can break across versions of Node.js.

If the Node.js version changing is the only reason not to cache `node_modules` can this action take into account the [`node-version-file`](https://github.com/actions/setup-node/blob/f099707f6e7a91b89cdebdeca599fc76cc8bf088/docs/advanced-usage.md#node-version-file) (or maybe even the `node-version`)? If it doesn't exist, don't cache the `node_modules` directory. If it does exist, cache the `node_modules` directory but use the value as part of the `primaryKey`: https://github.com/actions/setup-node/blob/f099707f6e7a91b89cdebdeca599fc76cc8bf088/src/cache-restore.ts#L39

Maybe as like:

```TypeScript
const primaryKey = `node-cache-${platform}-${nodeVersionFileHash}-${packageManager}-${fileHash}`;
```

If the Node.js version changes, the cache should be invalidated and everything rebuilt. Which seems to address the concern the `actions/cache` repo points out (as I understand it).

**Justification:**

The current caching strategy doesn't provide a noticeable improvement for non-trivial projects. It'll shave a couple seconds off of a multiple minute build due to needing to download all of the `node_modules` directory. Ideally, by caching `node_modules` when it appears safe to do so, the download of `node_modules` shouldn't need to happen as frequently and caching can save minutes.

**Are you willing to submit a PR?**

Yes!

**Comment by dmitry-shibanov** [comment]
Hello @joneshf. Thank you for your report. For now we're not planing to change caching behaviour for the setup-node action. If you need to cache different path, the recommended [solution](https://github.com/actions/setup-node/blob/main/docs/adrs/0000-caching-dependencies.md#goals--anti-goals) will be using the [actions/cache](https://github.com/actions/cache) action.
For now I'm going to close the feature request.

**Comment by joneshf** [comment]
Understood. Thanks for the explanation.

**Comment by EgonBolton** [comment]
> For now we're not planing to change caching behaviour for the setup-node action.

May I know if that has changed and if not, what is the reason?
I offer to do the PR if it's a time problem :)

**Comment by karlhorky** [comment]
@dmitry-shibanov would also love to see this built in as an option to the `actions/setup-node` action, if there's any room for reconsideration for this feature request after a couple of years 👍
