### ISSUE TITLE
Will the 'v3' tag be created?

### ISSUE THREAD

**Issue by Sparticuz** [actions/setup-node#425]
```
Error: Unable to resolve action `actions/setup-node@v3`, unable to find version `v3`
```

Thank you!

**Comment by Sparticuz** [comment]
As a note, it works when I use `actions/setup-node@v3.0.0`

**Comment by MaksimZhukov** [comment]
Hello @Sparticuz! Thank you for the report!
The `v3` tag has been created, feel free to use it
