### ISSUE TITLE
Package installation fails in most cases

### ISSUE THREAD

**Issue by reichhartd** [actions/setup-node#443]
**Description:**

When a package has been updated, `yarn install --frozen-lockfile --ignore-scripts` fails in most cases.
We receive error messages according to the following pattern:
```
Run yarn install --frozen-lockfile --ignore-scripts
yarn install v1.22.17
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.npmjs.org/csstype/-/csstype-3.0.10.tgz: ENOENT: no such file or directory, open '/home/gharunner/.cache/yarn/v6/npm-csstype-3.0.10-integrity/node_modules/csstype/.yarn-tarball.tgz'".
info If you think this is a bug, please open a bug report with the information provided in "/home/gharunner/runner5/tokenstreet-gha-runner1-5/tokenstreet-app/tokenstreet-app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```
The folders and modules vary each time.

However, the error should never occur because we have never activated caching:
```
env:
    NODE_VERSION: 16
...
            - uses: actions/setup-node@v3.0.0
              with:
                  node-version: ${{ env.NODE_VERSION }}
```

**Action version:**
`v3.0.0`

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Tools version:**

yarn

**Repro steps:**  
Use this action as described above.

**Expected behavior:**
That this action works reliably with and without caching.

**Actual behavior:**
`yarn install --frozen-lockfile --ignore-scripts` fails in the most cases.

**Comment by dmitry-shibanov** [comment]
Hello @reichhartd. Thank you for your report. Could you please provide a public repository to reproduce the issue ? If it's not possible could you please provide package-lock.json ?

**Comment by marko-zivic-93** [comment]
Hello @reichhartd 
Just a friendly reminder. Could you please provide us with a repo or package-lock.json? Thank you in advance!

**Comment by reichhartd** [comment]
Hi @dmitry-shibanov,
Hi @marko-zivic-93,
sorry, it was a stressful week! I will take care of it on Monday.

**Comment by reichhartd** [comment]
Good morning @dmitry-shibanov,
Good morning @marko-zivic-93,

I have created a demo repository: https://github.com/tokenstreet-tech/SetupNodeDemo

There are two open pull requests:

1. https://github.com/tokenstreet-tech/SetupNodeDemo/pull/6
2. https://github.com/tokenstreet-tech/SetupNodeDemo/pull/7

Both of them are failed at the beginning. I repeated number 2 until the workflow succeeded:

Run 1: https://github.com/tokenstreet-tech/SetupNodeDemo/actions/runs/2088376094
Run 2: https://github.com/tokenstreet-tech/SetupNodeDemo/actions/runs/2088411750
Run 3: https://github.com/tokenstreet-tech/SetupNodeDemo/actions/runs/2088416620

How I explain the error so far is that it tries to read the packages from the cache (although it is deactivated), does not find the packages and then fails.
If you then repeat the worfklows, it fetches the packages from the remote repository.

Thank you for your support!
