### ISSUE TITLE
bug repports 456+3

### ISSUE THREAD

**Issue by rudolfkotuc672** [actions/setup-node#449]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by bahagia97** [comment]
> 
> 
> 
> **Description:**
> A clear and concise description of what the bug is.
> 
> **Action version:**
> Specify the action version
> 
> **Platform:**
> - [✓] Ubuntu
> - [✓] macOS
> - [✓] Windows
> 
> **Runner type:**
> - [✓] Hosted
> - [✓] Self-hosted
> 
> **Tools version:**
> 
> 
> **Repro steps:**  
> A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.
> 
> **Expected behavior:**
> A description of what you expected to happen.
> 
> **Actual behavior:**
> A description of what is actually happening.
>

**Comment by marko-zivic-93** [comment]
Please share more information on this issue. 
I will close this issue for now.
