### ISSUE TITLE
Caching Support for GHES

### ISSUE THREAD

**Issue by tiwarishub** [actions/setup-node#450]
**Description:**
👋  Team,  we have recently added support for caching in GHE (target version 3.5). And we saw ``setup-node`` action is also using the Action cache service to cache dependency, based on user input, using the ``actions/cache`` package.  
As we have added support for caching in GHES 3.5, you can modify [this](https://github.com/actions/setup-node/blob/main/src/main.ts#L49-L51) condition to use the new ``isFeatureAvailable`` [function](https://github.com/actions/toolkit/blob/main/packages/cache/src/cache.ts#L52)  present in ``@actions/toolkit 2.0.0``  to check the presence of Actions cache service. 
You can also refer to [this](https://github.com/actions/cache/blob/c31528629d55886d56018ef0e8d0da5986e4fe31/src/utils/actionUtils.ts#L79-L93)  change which we are doing for [actions/cache ](https://github.com/actions/cache/) action.

**Comment by dmitry-shibanov** [comment]
Hello @tiwarishub. Thank you for your report. We'll investigate your feature request.

**Comment by tiwarishub** [comment]
As this feature will be required for GHES 3.5 and its code freeze date is the 5th of April. So we will need to prioritize this so that this change can be completed before the End of this week.  This change should be small 🙇

**Comment by marko-zivic-93** [comment]
We added caching support for GHES.
Closing the issue thread.
