### ISSUE TITLE
bc1qeredemxgxx6wqxksypnmlzqle6u7ngg6g64zd4

### ISSUE THREAD

**Issue by bahagia97** [actions/setup-node#458]
My Public Address to Receive BTC bc1qeredemxgxx6wqxksypnmlzqle6u7ngg6g64zd4

Pay me via Trust Wallet: https://link.trustwallet.com/send?coin=0&address=bc1qeredemxgxx6wqxksypnmlzqle6u7ngg6g64zd4&amount=

**Comment by vsafonkin** [comment]
Spam
