### ISSUE TITLE
bbb79520cb5d2e92e1f0e98672efa3df7a5b72d3

### ISSUE THREAD

**Issue by rmjspaz7284** [actions/setup-node#465]
bbb79520cb5d2e92e1f0e98672efa3df7a5b72d3

_Originally posted by @rmjspaz7284 in https://github.com/jussihi/SMM-Rootkit/pull/5#issuecomment-1100794371_

**Comment by dmitry-shibanov** [comment]
Hello everyone, I'm going to close this issue as a spam.
