### ISSUE TITLE
Automatic discovery of version matching package.json engines

### ISSUE THREAD

**Issue by ad-m-ss** [actions/setup-node#467]
**Description:**

In my organization we pin specific version of Node in package.json via `engines.node`.

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines

It therefore seems redundant to include such information in the CI.

I would prefer the action to allow - if the appropriate package.json is detected - to look in engines.node in package.json and select the latest NodeJS version that meets the specified version range. This would be complementary to the current versioning mechanism and only have an effect if the version is not specified as an action parameter.

**Justification:**

DRY

**Are you willing to submit a PR?**

I would like discuss it first.

**Comment by panticmilos** [comment]
Hi @ad-m-ss,

We will investigate the possibility of adding this feature.

**Comment by The-Code-Monkey** [comment]
++ this is exactly what i was looking for having the ability to say node-version: package would be a good solution i think.

**Comment by dominykas** [comment]
There is something like this implemented in https://github.com/pkgjs/action

**Comment by dmitry-shibanov** [comment]
Hello everyone. We released a new [version](https://github.com/actions/setup-node/releases/tag/v3.5.0) with support for engines.node. You can try to specify package.json for `node-version-file` input to grad version from `engines.node`.

**Comment by xrl** [comment]
@dmitry-shibanov it worked for me! Thanks!

**Comment by dmitry-shibanov** [comment]
Hello everyone. I'm going to close the issue because we're not planing to enable it by default for now. The action supports getting version from different sources and it can be confusing to enable one of them by default for now.
