### ISSUE TITLE
Is it possible ot add "latest" tag

### ISSUE THREAD

**Issue by zdm** [actions/setup-node#471]
**Description:**
Describe your proposal.

Is it possible to add `latest` version tag so it will install latest node release (currently v18.0.0)?

**Justification:**
Justification or a use case for your proposal.

**Are you willing to submit a PR?**

**Comment by panticmilos** [comment]
Hi @zdm,

Adding this feature is in our plans.

That is why I will close this issue now. If you have any questions or concerns, please feel free to leave a comment on this thread or open another issue

**Comment by zdm** [comment]
It should be easy.
We can getlatest version from [https://nodejs.org/dist/index.json](https://nodejs.org/dist/index.json).

Thank you,

**Comment by zdm** [comment]
Maybe it is better to close this issue after this feature will be implemented to get notified?

**Comment by panticmilos** [comment]
Hi @zdm,

I closed this issue since there is already opened [issue](https://github.com/actions/setup-node/issues/257) that is really similar to this one so you can check the following updates on that issue.

Cheers
