### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by robfletch1984** [actions/setup-node#509]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by IvanZosimov** [comment]
Closed, as a spammy issue.
