### ISSUE TITLE
Confusing error message if npm is not on the PATH and no version specified

### ISSUE THREAD

**Issue by rethab** [actions/setup-node#520]
**Description:**

On self-hosted runners where npm and node might not be on the path, the action doesn't throw a helpful error message if no node version is passed.

The error message is:

```
Error: Unable to locate executable file: npm. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

You'd think that this action would setup node if it's not on the PATH, but that only happens if the node-version is specified. If not, this action assumes it is on the PATH.

I think it would be nice if the error message was changed in order to give the user a hint as to what is going, like: "Could not find npm on the PATH. Did you forget to specify the input node-version"?

NB: Same error message as https://github.com/actions/setup-node/issues/504 and I think if the error message was better, that user would have immediately seen what is going on.

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**

**Repro steps:**  

_assume the self-hosted runner doesn't have npm on the PATH_

```yaml
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/setup-node@v3
         with:
           cache: npm
```

**Expected behavior:**

A helpful error message hinting to the user how to resolve it

**Actual behavior:**

A confusing error message

Note that I'd be happy to work on a PR if desired -- please let me know.

**Comment by IvanZosimov** [comment]
Hi, @rethab 👋 ! Thank you for this feature request, we will investigate it 🚀 !

**Comment by IvanZosimov** [comment]
Hi, @rethab 👋 ! I've investigated your request and believe there is no need to change the current error's message because it already contains all needed information: `Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable.` .  

By now I'm going to close this issue, if you have any additions or questions feel free to ping me! 💌

**Comment by rethab** [comment]
Hi @IvanZosimov , thanks for getting back on this and looking at it. This error happens in a very specific scenario, which is a self-hosted runner where you forgot to specify an input. While the error message gives a technical hint on what is going on, my suggestion was to add something along the lines of "did you forget to specify the input node-version?", because that's likely the problem in this case.

**Comment by IvanZosimov** [comment]
Hi, @rethab ! In most cases, a typical user won't meet that error with npm. The thing is here, that If user forgot to specify the version of node.js, our action will use the default (installed on your machine) version. Here two situations are possible:

1) User doesn't have node.js installed on his machine at all and he will get an error like: `node is not recognized as an internal or external command, operable program or batch file.` Here it's completely understandable that something is wrong with the node.js. 
2) User has node.js on his machine - everything works fine.

If a user gets an error related to npm it means that he has already made some modifications with PATH (as node is bundled to node.js by default and in the case of standard installation both node.js and npm get into the PATH), so we can imply that it's possible for him to determine what is wrong.
