### ISSUE TITLE
Corepack Support

### ISSUE THREAD

**Issue by RichiCoder1** [actions/setup-node#531]
**Description:**
Support using https://github.com/nodejs/corepack to manage non-NPM package managers.

Ideally in between installing node and bootstrapping the package manager cache, this action:

* enables corepack (could be a no-op depending on the node version)
* caches/restores the corepack root
* runs `corepack prepare --active`

(after some research, that last one may not necessary but instead makes an implicit step explicit)

At least MVP would only allow getting the version to restore from the root's `packageManager` field.

This behavior could either be trigged by the presence of the `packageManager` field in the root `package.json` (might be suprising), `cache: 'auto'` as possibly envisioned in #306, or `corepack: true` 

**Justification:**
Both pnpm and yarn support corepack, and yarn recommendeds corepack for package manager versioning. Currently using corepack with this action will break when using the `cache` key as this action assumes the appropriate version manager has already been installed. However, you don't necessarily want to bootstrap with corepack until the appropriate node version has been installed and configured.

Related: #530 #182 

**Are you willing to submit a PR?**
Yes

**Comment by dmitry-shibanov** [comment]
Hello @RichiCoder1. Thank you for your feature request. Actually we had similar proposal to [enable corepack](https://github.com/actions/setup-node/issues/480) by default. I think we should reinvestigate adding corepack support. We'll ping you about its results.

**Comment by RichiCoder1** [comment]
@dmitry-shibanov apologies for not seeing that closed ticket! I very much hope ya'll do. While technically experimental, it's being officially recommended and there's no (current) way to use both this action and corepack with some awkward contortions. Looking forward to the outcome!

**Comment by tisonkun** [comment]
I use corepack locally and hope we can integrate it with GitHub Actions :)

**Comment by brcrista** [comment]
If I'm understanding correctly, right now you can run `setup-node`, set up Corepack, and then run the standalone `cache` action.  So is the benefit of this just to be able to do it all inside the `setup-node` action?

**Comment by tisonkun** [comment]
Thank @brcrista ! Could you share a minimal config to achieve this? I may not understand how to set up corepack manually here.

**Comment by brcrista** [comment]
I don't know either, I was just summarizing my understanding from the issue description.

**Comment by RichiCoder1** [comment]
The semi-simple way w/ caching and something like pnpm would be:

```yaml
- run: corepack enable
- uses: actions/setup-node@v3
  with:
    node-version: 16
    cache: pnpm
- run: pnpm i
```

I think that may be faintly fragile as `corepack enable` operates on the built in node and not the potentially installed one. It does however fix an issue where `setup-node` will look for a `pnpm` exe/cache that doesn't exist yet when setting up cache I think.

**Comment by RichiCoder1** [comment]
@brcrista and your understanding is correct. Ideally with some extra smarts enabled by knowing exactly which packageManager is in use.

**Comment by dsame** [comment]
@RichiCoder1 thanks for you notification, it was a good point to review, but we should not go ahead of nodejs team and turn on corepack by default while it is not default for the nodejs itself.
The consequences of having corepack enabled are  risky for some builds and adding new input is not necessary complication of the action and its documentation. 
In the current state of the corepack to have an explicit simple step enabling the feature seems to be optimal solution.

I have to reject the feature request and close the issue, but please feel free to reopen it or create new one in case you still have some problems.

**Comment by jakebailey** [comment]
That's unfortunate; I avoid using the cache feature of the action because I'm nervous of mixing different major npm versions' caches. Having a corepack opt-in would compose well there, but I guess I'll just keep using the 4 steps (!) of setup-node, enable corepack, get cache location, cache, or keep mixing the npm version into the cache key.

**Comment by tisonkun** [comment]
@dsame perhaps you can close this issue as not planned instead of completed?

**Comment by brcrista** [comment]
We can leave this open to see if it continues to attract attention.  We're not going to do anything about it right now for the reasons that @dsame shared.  When Node makes Corepack the default, we can revisit it.

**Comment by RichiCoder1** [comment]
There is the perfectly fine alternative for now to just have core pack be opt in. Let's people use it without conflicting with the action, and makes flipping the switch later easy.

**Comment by simbo** [comment]
I strongly agree with @RichiCoder1 and would even go for a fork of setup-node with corepack support to achieve this goal.

For yarn and pnpm users there seem to be no reliable workflow to use setup-node with proper caching at the moment.

**Comment by simbo** [comment]
Please also keep in mind, that for GitHub Enterprise users there is in most cases neither node preinstalled on runners nor are they able to customize their runners because they are managed by company IT. 

I just made a [PR](https://github.com/BeeeQueue/setup-node/pull/2) to fix the tests for the [PR of BeeeQueue](https://github.com/actions/setup-node/pull/546).

This would add optional corepack support by simply setting `corepack: true` in the action inputs.

The PR adds 3 little lines of code to the `main.ts` of setup-node and one new input which is easy to understand and should not overcomplicate things. The documentation and action manifest update is done and the new code is also covered in tests.

And as a bonus - as corepack is completely optional - this feature is not a breaking change and could be published right away as a minor version update for v3.

In regards to attention on this topic:
- there are currently 2 open PRs who are trying to bring corepack support to setup-node.
- there are 3 open issues regarding corepack support (https://github.com/actions/setup-node/issues/531, https://github.com/actions/setup-node/issues/306, https://github.com/actions/setup-node/issues/182) where 2 of them have ongoing and recent activity.
- and you can be sure there are a lot of yarn and pnpm users out there as well as users of self-hosted runners with GitHub Enterprise who would be very thankful if this feature would be added.

**Comment by tisonkun** [comment]
I notice that I can achieve this mechanism simply with:

```yaml
      - name: Enable Corepack
        run: corepack enable
```

Thus, I'm OK with current status and don't find this issue a blocker to me :)

**Comment by linghengqian** [comment]
- I am surprised that this is actually an issue, corepack is still in the experimental stage and of course needs to be manually enabled.  I myself have been using `corepack enable && corepack prepare pnpm@7.11.0 --activate`. 

- This issue should actually be closed and wait for nodejs to enable corepack by default.

**Comment by wmertens** [comment]
@tisonkun you're not even using setup-node...

Ideally, setup-node optionally supports corepack, since Node optionally supports it. For example:
```
- uses: actions/setup-node@v4
  with:
    node-version: 16
    corepack: true
    cache: true
    install: true
```

This would install Node 16, run `corepack enable`, read the packageManager field, set up the cache for that, and then call the package manager in the correct way for CI (`npm ci`, `pnpm i` etc).

**Comment by SayakMukhopadhyay** [comment]
Hi all. I faced the same issue today and seeing as how #546 is kinda abandoned, I decided to write this feature myself. I am opening up a new PR for the same. All tests are passing in this PR and the option to enable corepack is, well, optional.

@brcrista As mentioned, this PR will add the "option" to enable corepack. As such, I don't see how we will go ahead of the NodeJs team. Yes, it is exeperimental but then again we are asking to enable this option by default. Just allow us to use it if we need it.

**Comment by joequincy** [comment]
I'm also chiming in with interest. For some CI tasks my org has some private runners that my team does not control and which do not have `node` or `yarn` installed by default. Because of this, we cannot use `cache: yarn` within `actions/setup-node` since the action will fail when running `yarn cache dir` to get the cache location. Instead we have to address this chicken/egg problem by manually caching with `actions/cache` like

```yaml
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Setup Yarn
        run: npm i -g yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
```

It would be preferable to instead be able to set up node with caching, and ensure the desired package manager is present just this action, which might look like (to borrow the syntax proposed in #651):

```yaml
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn
          corepack: yarn
```

**Comment by SayakMukhopadhyay** [comment]
@brcrista any chance that the PR #651 gets accepted? If there is a chance, I will fix the PR to handle the latest changes on main. As far as interest goes, imo there is a lot of it in here. This would anyway be an opt-in option so I don't see why there should be an issue with implementing the PR.

**Comment by cowwoc** [comment]
This workaround works for me (using yarn 3.x):

```
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install Yarn
        run: corepack enable |
          corepack prepare yarn@stable --activate

      # Yarn dependencies cannot be cached until yarn is installed
      # WORKAROUND: https://github.com/actions/setup-node/issues/531
      - name: Extract cached dependencies
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Update dependencies
        run: corepack yarn --immutable
```

**Comment by SayakMukhopadhyay** [comment]
> This workaround works for me (using yarn 3.x):
> 
> ```
>       - name: Update dependencies
>         run: corepack yarn --immutable
> ```

Looks interesting. So, if I get it right, the `setup-node` action needs to be invoked twice for the workaround to work. Still the last line seems odd. Is the command to run is `corepack yarn --immutable` or `corepack yarn install --immutable`? In either case, is it necessary to invoke yarn via corepack?

**Comment by cowwoc** [comment]
> if I get it right, the setup-node action needs to be invoked twice for the workaround to work.

Correct.

> Still the last line seems odd. Is the command to run is corepack yarn --immutable or corepack yarn install --immutable? In either case, is it necessary to invoke yarn via corepack?

Per https://yarnpkg.com/getting-started/usage `install` is implied if the command name is omitted.

Looking at https://yarnpkg.com/getting-started/install, you are right, we can invoke `yarn` directly instead of `corepack yarn`. I just tested it and it works.

**Comment by Dr-Electron** [comment]
I started to use corepack nearly everywhere. Would be nice to get direct support in setup-node ❤️

**Comment by styfle** [comment]
Can we get more eyes on #651?

Its not clear why this hasn't been merged.

Perhaps we need a better "experimental" disclaimer in case there are breaking changes in the future? (or is that implied?)

**Comment by IanVS** [comment]
I was really surprised this wasn't already working, or at least supported through an option.  I see a concern above about not making it the default until node.js does, but what is the objection to adding an opt-in option to enable corepack?

**Comment by trusktr** [comment]
Yarn's documentation shows `corepack enable` as the only way to install Yarn other than from git source (`yarn set version from sources`). Seems like this basically is required for Yarn, despite it being experimental. 🐔🥚

**Comment by Methuselah96** [comment]
This is even more important now that Yarn no longer sets `yarnPath` by default in [Yarn 4](https://yarnpkg.com/blog/release/4.0#installing-yarn). When `yarnPath` is set it "just works" since the Yarn Classic binary that comes pre-installed on the GitHub runner images consults the `yarnPath` setting.

**Comment by Mrquinn4** [comment]
Hello my name is Curtis was wondering if you could help me out with a
problem on my code if you would get back in touch withme thank you

**Comment by phiresky** [comment]
Curtis,

Hello yes this is tech support how can we help you?

Regards
Tech Support

**Comment by koistya** [comment]
`actions/setup-node@v3` stopped working today, throwing the following error:

```
error This project's package.json defines "packageManager": "yarn@4.0.2". However the current global version of Yarn is 1.22.21.
```

**Comment by cowwoc** [comment]
@koistya File a separate bug report. This issue is dealing exclusively with corepack support.

**Comment by nikolaik** [comment]
> `actions/setup-node@v3` stopped working today, throwing the following error:
> 
> ```
> Error: This project's package.json defines "packageManager": "yarn@4.0.2".
>        However the current global version of Yarn is 1.22.21.
> ```

Started seeing the same error today with `cache: yarn` too

**Comment by Kubessandra** [comment]
> `actions/setup-node@v3` stopped working today, throwing the following error:
> 
> ```
> Error: This project's package.json defines "packageManager": "yarn@4.0.2".
>        However the current global version of Yarn is 1.22.21.
> ```

Same with `cache: yarn`

**Comment by benquarmby** [comment]
> `actions/setup-node@v3` stopped working today, throwing the following error...

@koistya: Please raise a separate GitHub issue for that error. It is not the same as the important feature request which is the subject of this issue. Please do not overload this discussion any more other than to post a link to that separate error report.

**Comment by janpe** [comment]
> > `actions/setup-node@v3` stopped working today, throwing the following error:
> > ```
> > Error: This project's package.json defines "packageManager": "yarn@4.0.2".
> >        However the current global version of Yarn is 1.22.21.
> > ```
> 
> Started seeing the same error today with `cache: yarn` too

You should be able to fix this by adding the following env to your workflow `SKIP_YARN_COREPACK_CHECK: true`. But it's more of a workaround since having corepack in setup-node would be preferable.

**Comment by naXa777** [comment]
@janpe so what's the correct and direct fix?

**Comment by janpe** [comment]
> @janpe so what's the correct and direct fix?

I don't really have anything to add to my previous comment, but I'll repeat if I was unclear earlier.

So currently you have to add the following to fix your failing workflow

```
env:
  SKIP_YARN_COREPACK_CHECK: true
```

But hopefully in the future we'll see an option like proposed here added to `setup-node`: https://github.com/actions/setup-node/issues/480#issuecomment-1119303515

**Comment by koistya** [comment]
**NOTE**: With this flag `actions/setup-node` will install dependencies using Yarn v1, instead of the version listed in `package.json` (most likely Yarn v4). It's only supposed to be used as a temporary fix.

```
env:
  SKIP_YARN_COREPACK_CHECK: true
```

**Comment by ildella** [comment]
I make it work with actiosn v4 and yarn 4.x. 
The trick should be to run corepack enable before everything else. 

```yaml
    steps:
    - uses: actions/checkout@v4
    - run: corepack enable
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install --immutable
```

The only issue I have is the cache is never found. This is my log

```
actions/setup-node@v4

node: v20.10.0
npm: 10.2.3
yarn: 4.0.2

/usr/local/bin/yarn --version
4.0.2
/usr/local/bin/yarn config get cacheFolder
/home/runner/.yarn/berry/cache
/usr/local/bin/yarn config get enableGlobalCache
true
yarn cache is not found
```

**Comment by styfle** [comment]
We might not need to change `@actions/setup-node` if this other PR gets merged:

- https://github.com/nodejs/node/issues/50963
- https://github.com/nodejs/node/pull/51886

But there is also a scenario where Corepack may stop working with future versions of Node.js if this PR gets merged:

- https://github.com/nodejs/node/pull/51981

Feel free to add 👍 or 👎 to the linked PRs.

**Comment by rt-joe** [comment]
Regarding the PRs listed above about enabling corepack by default or removing corepack, I'm copy and pasting my reply from PR #901 that is complete and ready for review:

> My 2 cents: those do seem far away from reaching social consensus (there's still ongoing debate as of hours ago), let alone from being integrated into node. With the latest active LTS (v20) having maintenance until April 2026 (and v22 active LTS just around the corner), I think corepack with node will be here to stay for a while.

> I don't know if your comment was to imply that this PR should be held off on being merged, but if so, I think it solves a popular usecase for many users that won't go away anytime soon and can be properly addressed if/when the decision to include/exclude corepack in node is finalized.

**Comment by samwightt** [comment]
Kinda shocked that it's 2024 and this doesn't work with `yarn` anymore.

**Comment by linghengqian** [comment]
- According to https://github.com/nodejs/corepack/issues/545 , I believe the mainstream opinion of the nodejs community is actually to stop maintaining corepack and remove corepack from nodejs. Yarn, PNPM or other package managers with similar functions should implement corepack-like functions on their own.

- Long story short, the current issue is trying to introduce a feature that is about to be removed, which is unreasonable. Feel free to check out https://socket.dev/blog/node-js-takes-steps-towards-removing-corepack to see the Node.js PMWG's opinion.

**Comment by karfau** [comment]
Even if corepack is no longer supported:

In order to support properly installing/caching the dependencies when the packageManager field is set in package.json, the package manager with the right version needs to be installed, right?
All information required to do that is already present.

If this action would take care of it,
it would reduce a lot of boilerplate from workflows that is currently required to use this action as soon as this field is configured to something else than the npm version coming with the given node version.

For the node versions that support corepack, it could be as easy as using it, for other node versions, or maybe even in general it would require the action to know about the install steps of the package managers on ubuntu.

So I think the main question is:
Is supporting this feature out of scope for this action or not, independent of whether it is called corepack or not.

**Comment by karfau** [comment]
Has anybody attempted to create a PR for this?

**Comment by trivikr** [comment]
The Node.js team has decided to stop distributing corepack from v25+ onwards in TSC vote https://github.com/nodejs/TSC/pull/1697#issuecomment-2737093616

However, recent updates indicate that the developers will continue to use corepack, but install it from npm instead.
I've summarized some updates in https://github.com/nodejs/corepack/issues/681#issuecomment-2740898841

It would be awesome if setup-node action accepts a configuration, say `corepack: true`, like suggested in PR https://github.com/actions/setup-node/pull/901 which installs the latest version of corepack from npm and enables it.

**Comment by SpecLad** [comment]
I submitted an alternative proposal, which is to add Corepack to the base runner images: actions/runner-images#12310. If that's implemented, then no changes to the action will be required.

**Comment by fulldecent** [comment]
Here is the workaround GitHub Actions workflow I use to workaround how setup-node does not handle corepack.

https://github.com/fulldecent/github-pages-template/blob/e000f740424695642b479074872fc32835aa6be2/.github/workflows/code-lint.yml#L19-L26

This does NOT support caching.

Would love to see others' live workflows that are working around the issue.

**Comment by benquarmby** [comment]
> I submitted an alternative proposal, which is to add Corepack to the base runner images...

> Here is the workaround GitHub Actions workflow I use...

Thanks for the contributions. However, neither of these address the chicken / egg problem for self-hosted runners where we can't assume an existing Node installation. We're starting from a clean slate as explained here: https://github.com/actions/setup-node/issues/182#issuecomment-960665068

In the mean time, I've just gotten used to doing this for every single workflow. It's not great, but it works:

```yaml
steps:
  - name: Install Node.js
    uses: actions/setup-node@v4
    with:
      node-version-file: .nvmrc
  - name: Enable Corepack
    run: corepack enable
  - name: Configure Dependency Cache
    uses: actions/setup-node@v4
    with:
      cache: pnpm
```

**Comment by rt-joe** [comment]
I use the same double setup-node as @benquarmby. Also [previously stated in this thread](https://github.com/actions/setup-node/issues/531#issuecomment-1416814256
) over 2 YEARS ago 😒

The amount of times I've had to put that into a workflow w/ a comment about why it's duplicated with a link to this issue... 🙄

**Comment by vishnup-ditto** [comment]
> > I submitted an alternative proposal, which is to add Corepack to the base runner images...
> 
> > Here is the workaround GitHub Actions workflow I use...
> 
> Thanks for the contributions. However, neither of these address the chicken / egg problem for self-hosted runners where we can't assume an existing Node installation. We're starting from a clean slate as explained here: [#182 (comment)](https://github.com/actions/setup-node/issues/182#issuecomment-960665068)
> 
> In the mean time, I've just gotten used to doing this for every single workflow. It's not great, but it works:
> 
> steps:
>   - name: Install Node.js
>     uses: actions/setup-node@v4
>     with:
>       node-version-file: .nvmrc
>   - name: Enable Corepack
>     run: corepack enable
>   - name: Configure Dependency Cache
>     uses: actions/setup-node@v4
>     with:
>       cache: pnpm

Hi @benquarmby , have you every tried this with yarn as the package manager. I assume the caching mechanism should work but wanted to check

**Comment by benquarmby** [comment]
> ...have you every tried this with yarn as the package manager?

With yarn 1.x, yes. This was working just fine before switching to pnpm. Never tried with yarn berry.

Note that the action is smart enough to only perform the caching steps on the second run. It doesn't try to install Node again.

**Comment by fulldecent** [comment]
FYI: The TSC [has voted](https://github.com/yarnpkg/berry/pull/6924) to change the future of Corepack, starting with Node.js 25.

This may affect how people will install yarn in the future. But also, it may be moot because the system and creators that you depend on (such as GitHub Action runners) may include this for you.

---

FYI: actions/setup-node@5 was release and [has changes last week](https://github.com/actions/setup-node/issues/1357#issuecomment-3323233627) related to Yarn.

---

I think ~going forward~ at the moment this is best practice:

```yarn
- name: Install Node.js
  uses: actions/setup-node@v5
  with:
    node-version-file: .nvmrc
    package-manager-cache: false
- name: Enable Corepack
  run: corepack enable
- name: Configure dependency cache
  uses: actions/setup-node@v5
  with:
    cache: pnpm # or yarn
```

But if you are reading this after 2025-10-15, the [current expected release date](https://github.com/nodejs/Release/blob/main/schedule.json) of Node.js then the corepack command [may stop working](https://github.com/nodejs/TSC/pull/1697#issuecomment-2737093616).

**Comment by hildjj** [comment]
Running setup-node twice can't possibly be the long-term best practice, but that's a problem for the setup-node team to fix.

**Comment by xenoterracide** [comment]
this is all fantastic.... especially the may stop working

```
Run actions/setup-node@v5.0.0
Environment details
/usr/local/bin/yarn --version
1.22.22
/usr/local/bin/yarn cache dir
error This project's package.json defines "packageManager": "yarn@4.10.3". However the current global version of Yarn is 1.22.22.

Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.
Error: error This project's package.json defines "packageManager": "yarn@4.10.3". However the current global version of Yarn is 1.22.22.

Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.
```

**Comment by mrwensveen** [comment]
> this is all fantastic.... especially the may stop working
> 
> ```
> Run actions/setup-node@v5.0.0
> Environment details
> /usr/local/bin/yarn --version
> 1.22.22
> /usr/local/bin/yarn cache dir
> error This project's package.json defines "packageManager": "yarn@4.10.3". However the current global version of Yarn is 1.22.22.

Did you figure out any way to prevent this?

**Comment by fulldecent** [comment]
> this is all fantastic.... especially the may stop working
> 
> ```
> Run actions/setup-node@v5.0.0
> Environment details
> /usr/local/bin/yarn --version
> 1.22.22
> /usr/local/bin/yarn cache dir
> error This project's package.json defines "packageManager": "yarn@4.10.3". However the current global version of Yarn is 1.22.22.
> 
> Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
> Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.
> Error: error This project's package.json defines "packageManager": "yarn@4.10.3". However the current global version of Yarn is 1.22.22.
> 
> Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
> Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.
> ```

It seems that you have cache turned on for the first step. Are you running the action I provided above? If not please minify and provide an action that demonstrates your runs. 

My latest prior note is still working in production builds on GitHub CI today. 

And while I'm downvoted into oblivion, this still appears to be the best practice today WITH THE AVAILABLE TOOLS. And of course we hope the setup-node action will improve and allow a better workflow.

**Comment by rt-joe** [comment]
> And while I'm downvoted into oblivion

The downvotes aren't because of the provided solution's ineffectiveness (it works) but because of setup-node inability to properly address it.

**Comment by oleksandr-danylchenko** [comment]
Thanks, @fulldecent. The following solution worked for my `npm` setup:
```yml
- name: Setup Node.js
  uses: actions/setup-node@v6
  with:
    node-version-file: .nvmrc
    registry-url: "https://registry.npmjs.org"
    scope: "..."

- name: Enable Corepack
  shell: bash
  run: corepack enable npm

- name: Enable NPM cache
  uses: actions/setup-node@v6
  with:
    cache: npm
```

However, what would be the recommended approach for supporting Node 25 in the future? 
It won't supply the `corepack` anymore. So should I explicitly add the `npm i -g corepack` before the `corepack enable npm`?

**Comment by linghengqian** [comment]
I would say that even after all these years, I still oppose adding configuration support for corepack to `actions/setup-node`. Corepack is not actively maintained and is no longer built into NodeJS.

**Comment by trivikr** [comment]
> Corepack is not actively maintained

This statement is incorrect. 
* Contribution graph: https://github.com/nodejs/corepack/graphs/contributors
* A version was published last week https://github.com/nodejs/corepack/releases/tag/v0.35.0
  * It also reduced install size by 43%
* corepack still has 4M weekly downloads and rising https://npmx.dev/package/corepack

**Comment by linghengqian** [comment]
> > Corepack is not actively maintained
> 
> This statement is incorrect.
> 
> * Contribution graph: https://github.com/nodejs/corepack/graphs/contributors
> * A version was published last week https://github.com/nodejs/corepack/releases/tag/v0.35.0
>   
>   * It also reduced install size by 43%
> * corepack still has 4M weekly downloads and rising https://npmx.dev/package/corepack

According to the decision made in https://github.com/pnpm/pnpm/issues/11732#issuecomment-5267508169 , the pnpm community has essentially removed pnpm's support for corepack. I don't see any point in pretending that corepack is still compatible with third-party package managers within its git repository.

**Comment by zkochan** [comment]
Not only the pnpm community. Yarn as well, they have their new official version switcher: https://v6.yarnpkg.com/concepts/switch

Please, do not use corepack to install pnpm.

**Comment by fulldecent** [comment]
Now that actions/setup-node@v7 is released, Yarn works for me (including cache) with @ildella's approach: 

This should solve @xenoterracide's [issue above](https://github.com/actions/setup-node/issues/531#issuecomment-3341718851), and @cowwoc's double setup-node workaround, which was previously best practice.

```yaml
# Update this when Yarn no longer recommends Corepack
# See: https://yarnpkg.com/getting-started/install
- name: Enable Corepack
  run: corepack enable

- name: Setup Node.js
  uses: actions/setup-node@v7
  with:
    node-version-file: .node-version
    cache: yarn
    cache-dependency-path: yarn.lock

- name: Install dependencies
  run: yarn install --immutable
```

I now maintain a repo just for [integration testing how Yarn installs on GitHub Actions](https://github.com/fulldecent/node.js-template).

---

@oleksandr-danylchenko even though Node.js soon (i.e. next LTS) drops support and pnpm/Yarn deprecate corepack, [there is no plan](https://github.com/actions/runner-images/issues?q=corepack) for GitHub runners to drop corepack. It would be responsible if they support corepack at least until actions/setup-node supports all the next generation solutions from these respective package managers.
