### ISSUE TITLE
Disable image cache

### ISSUE THREAD

**Issue by jlarmstrongiv** [actions/setup-node#535]
**Description:**
Is there a way to disable the image cache?  It causes crashes with npm/npx scripts not being found.

**Action version:**
actions/setup-node@v3

**Platform:**
- [x] Ubuntu

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Tools version:**
node-version: lts/gallium
packageManager: npm@8.13.2

**Repro steps:**  
N/A

**Expected behavior:**
Ability to disable all caches

**Actual behavior:**
Unable to find how to disable node cache.

Please note that I am not using `cache: 'npm'`.  I am referring to the image cache.

Any workarounds like clearing a cache path beforehand are welcome.

**Comment by dmitry-shibanov** [comment]
Hello @jlarmstrongiv. Thank you for your report. You can try to use check-latest to download version from [node-version](https://github.com/actions/node-versions). What issue with npm/npx do you have ? Could you please provide public repository to reproduce it ? Npm and npx are added in the PATH.

**Comment by jlarmstrongiv** [comment]
Hi @dmitry-shibanov and @marko-zivic-93 !  Thanks for getting back to me.  After investigating today, it appears that the issue was introduced in npm in 8.13.x.  I have created an issue https://github.com/npm/run-script/issues/91 and pr https://github.com/npm/run-script/pull/92 to resolve it.
