### ISSUE TITLE
post setup-node throws an error - missing pnpm store dir

### ISSUE THREAD

**Issue by dominikg** [actions/setup-node#543]
**Description:**
post setup-node throws an error about a missing store directory for pnpm

**Action version:**
3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

node16, pnpm 7.5.1

**Repro steps:**  
workflow:
https://github.com/sveltejs/vite-plugin-svelte/blob/main/.github/workflows/ci.yml
run with error:
https://github.com/sveltejs/vite-plugin-svelte/runs/7306898304?check_suite_focus=true

**Expected behavior:**

pnpm store is detected correctly and cached in post-action - no error thrown.
Even if the run completed correctly but for whatever reason the pnpm store could not be cached, post should not throw an error, causing a CI fail.

**Actual behavior:**

An error is thrown in post setup-node, failing the run

- [pnpm store is not found initially (ok i guess, it will be populated later)](https://github.com/sveltejs/vite-plugin-svelte/runs/7306898304?check_suite_focus=true#step:5:19)
- [pnpm install fills store](https://github.com/sveltejs/vite-plugin-svelte/runs/7306898304?check_suite_focus=true#step:6:13)
- [post action throws an error that store dir does not exist](https://github.com/sveltejs/vite-plugin-svelte/runs/7306898304?check_suite_focus=true#step:16:6)

**Comment by dmitry-shibanov** [comment]
Hello @dominikg. Thank you for your report. I think it can't save the cache because pnpm store path returns such output:
```
Using hooks from: /home/runner/work/vite-plugin-svelte/vite-plugin-svelte/.pnpmfile.cjs
readPackage hook is declared. Manifests of dependencies might get overridden
/home/runner/.local/share/pnpm/store/v3
```
It gets extra logging that is why the action can't get correct path. As temporary solution could you please create .npmrc file with such content:
```
loglevel=warn # or error
```

**Comment by dominikg** [comment]
hmm, that's very unfortunate and could break a lot of CIs, In fact i wonder why it hasn't caused more trouble until now.

Can confirm that the additional logging appears when updating from pnpm 7.5.0 to 7.5.1 

cc @zkochan

**Comment by dominikg** [comment]
can confirm that `loglevel=warn` in .npmrc avoids the problem

https://github.com/sveltejs/vite-plugin-svelte/runs/7309633235?check_suite_focus=true#step:16:6

**Comment by zkochan** [comment]
`pnpm store path` should only print the path to the store, so it is a bug.

**Comment by dmitry-shibanov** [comment]
Hello everyone. I've merged fix in the main branch. Could you please confirm that it works as expected  for `actions/setup-node@main` ?

**Comment by dmitry-shibanov** [comment]
Hello everyone. We released a new [version](https://github.com/actions/setup-node/releases/tag/v3.4.1) and updated the major tag with fix. Could you please confirm that everything works as expected ?
