### ISSUE TITLE
Throw an exception when `node-version` is lower than "16"

### ISSUE THREAD

**Issue by mbelsky** [actions/setup-node#550]
Hi,

**Description:**
Throw an exception when `node-version` is lower than "16" for `actions/setup-node@v3`.

**Justification:**
I just found that DefinitelyTyped/DefinitelyTyped folks are having these lines in their config:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/66ace08532d370ac54f80bc5a95f0e8902fbefb0/.github/workflows/CI.yml#L13-L15

Their CI is working and I am not sure they know CI runs on [node@16](https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=135995&view=logs&j=8635df7d-ecde-52a7-c7a8-84b998e35690&t=7cc2fdda-53c1-51a9-736b-e7acacffa700&l=22). It is unobvious.

**Potential issues:**
This feature request is a breaking change.

**Are you willing to submit a PR?**
Yes, I'd like to help with this issue.

**Comment by dmitry-shibanov** [comment]
Hello @mbelsky. Thank you for your feature request. I think the action should allow to install lower versions than the current lts because some customers can still use them. For now I'm going to close the feature request.
