### ISSUE TITLE
Add Bun support

### ISSUE THREAD

**Issue by Frank-Mayer** [actions/setup-node#556]
**Description:**
It would be great if [Bun](https://bun.sh) would be supported

**Justification:**
Currently, I only use [Bun](https://bun.sh) on my development machine. My GitHub Actions run on NPM. It would be great if both worked so that tests are more accurate.

**Are you willing to submit a PR?**
rather not

**Comment by Frank-Mayer** [comment]
I know that Bun is not Node. But it would fit the purpose of `setup-node`.

**Comment by dmitry-shibanov** [comment]
Hello @Frank-Mayer. Thank you for your report. We'll investigate the feature request.

**Comment by SimenB** [comment]
Unless `deno` is added, `bun` shouldn't either I think?

**Comment by Frank-Mayer** [comment]
That's a good point, I think

**Comment by dmitry-shibanov** [comment]
Hello everyone. For now I'm going to close this feature request because we're not planing to add support for Bun. The Bun can be installed through one line `curl https://bun.sh/install | bash`. Moreover It does not need Nodejs to work and it's separate JavaScript runtime. You can try to use one of the available community actions to set up Bun. 
- https://github.com/marketplace?type=&verification=&query=bun+

**Comment by emnnipal** [comment]
Hey @dmitry-shibanov, it's been a few months since the release of bun 1.0. Could we take another look at this issue and explore the possibility of adding support for bun, not as a runtime, but as a package manager? Thanks!

**Comment by Mohamedabdurahmanhassan** [comment]
4a936bf13067a88493a4e0a9ff580e7a04e51a9ba20a85a9837990991925efb31efd3d23c3d6b67e3452e6c291a6758276e66e45711e8442bdc2c64d537e99cedd14d691b1847057d248c3d2fb75dd21c494135088617ed0bb0a2a998a435514a0e210e7d35c8323557da5ff5411ab287f8998eaa99781ca9c9940f8b174afa849920e817d55dcbdde87523ddb4a9513ad5880d3208ab9db21e9b231192e90ad2865cdac792e094ce428c77521635e2c29492eef48eded641dc5aeef787a05ef2cd46607025db18ab795ffabc2d80cba6a2811523b07d9fc91d6fe0676ebc9a0915389fd5ca2493219f5ebc92c3818d4c2569f4600209d56ab282aa310bdbc3f6a7042d2db2beaf8d688aba6258a4585be45a495f9d14cfea62db2c0d7eaa334674b1949e9058a374b422782cb502423997c70cbabb21f23d2e174236683dbb876a1029709ecfb7fc57e907a9d83999ea8ab2ab855aabcc1403a7b72e14859415c3b18c4e076936deb41c34e262ab8e03af1ce0c54c8fb5d7c024105f26b28e1fba74521eaa3fb3870f65d3a09423835d4891ecf9123ec989609837ff98b0818092529d678ac536dec9e529f165fdffeef3d0f8efe678d9c1cd32fd67fe8d9322c3bba6838e9bfbcf3c67551fcbd9d64fe3f507825d3e28380e67ea65f296a18b5b371144f2f64a42a635c656ebd8b8c452424cdaee1607c7cd9f9a4b74bd70f97b4a20851ed676df6bf6ee9ebb059df95af727f1aa6f2d90f057a1c98ce89e5cb6e2e4369246390974d7e68e4e848008290769187ad9a55a531dae189fd0d94eed9c0f26b51d1a18d6edf5c7df7fbd3a58714c88382ab3d0e0d7f30e279fa4c03faa0c54239fb8e356969429ec9d5d8d5bb92b8907ad3b858b76863ea00b2811169afdcb334994057d5332b3d327badaa2812a521716fec8c12e9995a9cb285feffc455be56a46945a4a4bbeab5ed34f95c27a9000656a3d2a49a85b091fb9dcbb063f6b66001f8671993edca39208b2a2d6fd5b59cdcf61939053806758c4e48c126243f25daa069364062ad51c6dc5f57617a6e82285aa02911c60d662cedb3adb226a3bb79370cc8ca1ac745ad43285841da9557e34e65807414bd5a1d52308099b9caaf2608d35322e618d39dcbd10f10ab11d96310b281b04a78198e43f58749ea4e03a7ad8ae55668ada3004146875795b58d849fb9d7373a0091f8f5b82423fcbd3c61bcc46b20223739f05f1588672e74bde69bb1a4dff483162f50b2a27e8bd1d39a17870f6881b38012e9be8a9b8dd166c2f3679ca24cd7c4b40181762ec693dd426f01b89edd9b33d915fb8131f62ba3d38261629294eff32295167adeb564d21d0ef2829284734d62adea17066c46d08a7d14dbe07761439e93c7549717eb4924f917e956edcc005eb046b5010d8f5c1e29ad00b6984377321e5f263a2e5b0b9392278f5156cccf5700179330e26c76b9875c62840d0200d567b79502dfd67db696b0d89af23e86c09c893ec8a05965e8da4418aa38e851199e167adeb564d21d0ef2829284734d62adea17066c46d08a7d14dbe07761439e93c7549717eb4924f917e956edcc005eb046b5010d8f5c1e29ad00b6984377321ee0adb882e45469fd9288f18f1aa0ff6961de544473d6fb461e14bee1be7e414276aad83db045867f81b25d18d2bb69ce3b4f5137da6f932e2669dfb3471b70ff9a82a45e5611ad68aa6ce6fcf41171aad8b07d1b7fd3431a102483d830767bcbbaa1554e2f90155bb9bb145b9664d1651b63c1da89c4263d3049b787b2fd227bdf9e0f8329628cfb6ca15229d5ed52b6cb32d8ed4c137320d331a776ab88fd236918c20194f499e495f9b783f44773f56cf914f0d3c48f5170d6d03d4b8d980ca2739d2d9256f6a80e51ed2c1328b14604d2b2b7ea72ac77958012c8aaccea4a649a040216ca9b612d735e7c721c903813f91f90fbb6598d199b40e814a9218ce8fd0a647156f5c13c422533a239de2c3cb9ce0f9ea1d1673a257beaa40aa3e3078417a2a9a67a49bb86e3fe0939c5d225b6cd3622b4a134e29c9591e91e09823296921cbb20abfa75342c8b34807003d5be5ded824783d97f8fac7b5d110b7ea3e4f5fbb7c73f57f0aa6eb73994e76671c8010f3de6072839c180b3ce2cf8ee4a936bf13067a88493a4e0a9ff580e7a04e51a9ba20a85a9837990991925efb31efd3d23c3d6b67e3452e6c291a6758276e66e45711e8442bdc2c64d537e99cedd14d691b1847057d248c3d2fb75dd21c494135088617ed0bb0a2a998a435514a0e210e7d35c8323557da5ff5411ab287f8998eaa99781ca9c9940f8b174afa849920e817d55dcbdde87523ddb4a9513ad5880d3208ab9db21e9b231192e90ad2865cdac792e094ce428c77521635e2c29492eef48eded641dc5aeef787a05ef2cd46607025db18ab795ffabc2d80cba6a2811523b07d9fc91d6fe0676ebc9a0915389fd5ca2493219f5ebc92c3818d4c2569f4600209d56ab282aa310bdbc3f6a7042d2db2beaf8d688aba6258a4585be45a495f9d14cfea62db2c0d7eaa334674b1949e9058a374b422782cb502423997c70cbabb21f23d2e174236683dbb82c3bba6838e9bfbcf3c67551fcbd9d64fe3f507825d3e28380e67ea65f296a18b5b371144f2f64a42a635c656ebd8b8c452424cdaee1607c7cd9f9a4b74bd70ffba74521eaa3fb3870f65d3a09423835d4891ecf9123ec989609837ff98b0818092529d678ac536dec9e529f165fdffeef3d0f8efe678d9c1cd32fd67fe8d93276a1029709ecfb7fc57e907a9d83999ea8ab2ab855aabcc1403a7b72e14859415c3b18c4e076936deb41c34e262ab8e03af1ce0c54c8fb5d7c024105f26b28e197b4a20851ed676df6bf6ee9ebb059df95af727f1aa6f2d90f057a1c98ce89e5cb6e2e4369246390974d7e68e4e848008290769187ad9a55a531dae189fd0d94eed9c0f26b51d1a18d6edf5c7df7fbd3a58714c88382ab3d0e0d7f30e279fa4c03faa0c54239fb8e356969429ec9d5d8d5bb92b8907ad3b858b76863ea00b2811169afdcb334994057d5332b3d327badaa2812a521716fec8c12e9995a9cb285feffc455be56a46945a4a4bbeab5ed34f95c27a9000656a3d2a49a85b091fb9dcbb063f6b66001f8671993edca39208b2a2d6fd5b59cdcf61939053806758c4e48c126243f25daa069364062ad51c6dc5f57617a6e82285aa02911c60d662cedf58749ea4e03a7ad8ae55668ada3004146875795b58d849fb9d7373a0091f8f5b82423fcbd3c61bcc46b20223739f05f1588672e74bde69bb1a4dff483162f50b3adb226a3bb79370cc8ca1ac745ad43285841da9557e34e65807414bd5a1d52308099b9caaf2608d35322e618d39dcbd10f10ab11d96310b281b04a78198e43b2a27e8bd1d39a17870f6881b38012e9be8a9b8dd166c2f3679ca24cd7c4b40181762ec693dd426f01b89edd9b33d915fb8131f62ba3d38261629294eff322955f263a2e5b0b9392278f5156cccf5700179330e26c76b9875c62840d0200d567b79502dfd67db696b0d89af23e86c09c893ec8a05965e8da4418aa38e851199e167adeb564d21d0ef2829284734d62adea17066c46d08a7d14dbe07761439e93c7549717eb4924f917e956edcc005eb046b5010d8f5c1e29ad00b6984377321ee0adb882e45469fd9288f18f1aa0ff6961de544473d6fb461e14bee1be7e414276aad83db045867f81b25d18d2bb69ce3b4f5137da6f932e2669dfb3471b70ff9a82a45e5611ad68aa6ce6fcf41171aad8b07d1b7fd3431a102483d830767bcbbaa1554e2f90155bb9bb145b9664d1651b63c1da89c4263d3049b787b2fd227bdf9e0f8329628cfb6ca15229d5ed52b6cb32d8ed4c137320d331a776ab88fd236918c20194f499e495f9b783f44773f56cf914f0d3c48f5170d6d03d4b8d980ca2739d2d9256f6a80e51ed2c1328b14604d2b2b7ea72ac77958012c8aaccea4a649a040216ca9b612d735e7c721c903813f91f90fbb6598d199b40e814a9218ce8fd0a647156f5c13c422533a239de2c3cb9ce0f9ea1d1673a257beaa40aa3e3078417a2a9a67a49bb86e3fe0939c5d225b6cd3622b4a134e29c9591e91e09823296921cbb20abfa75342c8b34807003d5be5ded824783d97f8fac7b5d110b7ea3e4f5fbb7c73f57f0aa6eb73994e76671c8010f3de6072839c180b3ce2cf8eeabdurahma:
92c0cd10870e63e6edcfeef43ffadf3131f7ab45802547c048498f28d76bdb869c35b43b2da18632c557e1bb5a88161a43b8aa5dbc504de4989e19f03c80bf85

645bf8ac2f255e592f7d535670aafb1558b58ca71db7ef079e685be4170dfb1e0e540c094d74dfc952662444c4bd33a18bc40d8af44e6e9275abf3f8f2058f39

459909da8e067cc7e94470be02e2b2ea168f9a565cd3ab99a89441cc5d2791b9569b712301d2570cd60c6c9efdfe339d4e835ff0fd046e5a0cf005ea36669b7f

db54e1956db34edb80b7105431e8a14f085870855108ebc39169e2962ce50e766741915cea0dcf8db495656b959418c0eeffc6c68d1b16ca37c6279e78c9ca86

1d337e7b48301a7f61613960fa3cce81d6dc11c314153097c6efaeafe60224fd3f6d64ad3327faed0c606d14d476861a2b676d1c8f3e933182e2039cb48dc3e9

4acad07378d67d8c3d142a677b4c7629d5187990dd129b8b5283db9e385cd0a8d2168fad7ffe784ebf47bee73ea9981f208931c9409d50df82c6512d795b7081

80aa0f014418f3d4bde2a5a1111bdebb40dd20a9d86152c6a5d1488d93377d37755964b87f7c6bd41a3c348bd65ba109f990cb775eecfc99183d843d53a72a5d

b709ae3e14a896d19607c4b6764c63d9b92aaf44370578bd7b95f4f2759694fe6fe862e75510a7923f1e41318b5c91b6ad2171b59710a723a8a53a168df00069

8df00ad81a87586b7c0076e2da9fe321168ad572b0ffc8345b3e1ed27b75f015881122527ed03421af36b324d9aa2d4ab58e7c341f106f9d4e87a54f9348ef9c

ea5fd9a8e0df0642bf013df6fb38c92a507908da306b6fe2b072fd6ebaefbf149c1192492b563208ac8b10b9f2dbf04df135c7aed71c38af6581a1e761ceb31c

1f31d85f24127146ca1438839a116075dca44fe9f2a0da3cb6b6f3f4014fa3ddb1698424df6b4f998c8f1e29b07bcc7e34a7c4435599bcb8d89909cf8dc2283a

9383a1db6320720609735b4bee245850dcd8b5ebb7337efc4ca9046df978215961e382a82cb0a27caaf2f88cb4b9b1f8e5832828f083c303afe2914bd1810c6e

MTnuCtbm4vtXbamwspbKH9MdilpNT5mA0450994775e1d252c11f765384b4d3c610339070fe20880cf62d17a58b73bbbdac61f72a9b7476150ec816f65b8357ae398d9697efb3d925a6f9aec775e29a8d5ff6fdf21d81f66f72f20b8f49267b9a999f1126d18b83690037f22211e8d5c0d789d6e19b85847a59bb457252c905cf054187872e16f4c0ddeeadc40257449909fe104b5f89233b468ce74b2edf06656960e997af5378c4233aedb253262753f390fbe1ace074b40afcd847c794b8dbe0a936884126f1f43259f0c9d42caf981c62e5a2b94524ae61ef9b54885b57b5a307cb5e7f7411da35892c3cec0f3b85cefcd01a4f78f213836f24251e56abe620229aa35daec743f1fbfa8ad269dd98643ce0bf1d81f66f72f20b8f49267b9a999f1126d18b83690037f22211e8d5c0d789d6e19b85847a59bb457252c905cf054187872e16f4c0ddeeadc40257449909fe104b

79bd830ad2c0ed745eb38ee5fb5f649447da3c40a9580fbecf3f8f5fbb068a7069a4c7679e6926c803fdaeefd16bf1bd8a397dc01f17bd448acbe33269dfedc1

9c182bb3b56485121710e6df901ad58194a6519342858dc7552977f69c006dbf242055f143df01482f074e3758dded56fa8f2a284b3009d13cb195ff80aaf730esr:g2NgYGZgmMCTIrr4IQOTdUZJSUGxlb5-cpJeYl5yRn6RXk5mXrZ-qmVycpqhcaKuaVqqqa5JWqqZrqVZcppuipGRWVKShZlFqmkqMwtI6UVGuGnM2nsS-M3-2EgwzrkWuuNDze7EDQY3L9-QW5139ArT91sz9i9ldATb4QOywljPRM9Qwakov7w4tSikKDGvuCC_qAQobKxnoOCbX5WZk5OobwpkawCVl1ZYKzjmpRTlZ6YoGBpYK3hrKjgWFOSkhqcmeWeW6Jsam-sZmyloeHuE-ProKORkZqcquKcmZ-drKjhnFOXnpuobGprpGYCgQnhGYk4q0BoDoEVGQIuSMnNSFYIT0xKLMqHmsBYn5xekcpYn5uSkluil53ImZyRm5sVnphT3M3IyMDLwMG7iZLTg-uL3dU6khPMs-VmON8wymZglV7CW7GBZ-jNmbx2jFtMCVruonu9WYbv4bwk-uanHZLFk0aqSP-fdrq4UKMlwYCx-YhGlzvHsOkuHye-D7PP1V2-sthGKFsn6YjFdbkJhji8DNwMTo9wqDpWCmh6xvaoiIZP3s2m9uftva05xfvYyy3rDqZ9t5jNwAQA

**Comment by Frank-Mayer** [comment]
Bun has its own setup action.
https://github.com/oven-sh/setup-bun

**Comment by Mythique** [comment]
It could indeed be great to have the bun package manager and a cache option for bun.

It could be useful for Angular for example. Angular still needs Node, but can use the bun package manager.
