### ISSUE TITLE
[README.md]()

### ISSUE THREAD

**Issue by Draconic115** [actions/setup-node#558]
[README.md]() 

> 93osiaoti*3o5iwueproUFT7jir9ejeha ejeienrbai(394838$+#!"84(@-(#9#63!_8@+4)_9=€[¥×¢÷|[¥×`÷iwjdjdiejthaiIsktoe8q Iej Jair UzuJZahU&TU*R&Hr^H*284

#1152 #345 #1151 #1138

_Originally posted by @Draconic115 in https://github.com/actions/toolkit/issues/1156#issuecomment-1217055956_

**Comment by dmitry-shibanov** [comment]
Hello @Draconic115. Could you please fill the form ? For now I'm going to close the issue as a spam.
