### ISSUE TITLE
Version in `package.json` does not match released version

### ISSUE THREAD

**Issue by mobilutz** [actions/setup-node#568]
**Description:**
Currently the newest version of this action is `3.4.1`

But in the [`package.json`](https://github.com/actions/setup-node/blob/9fc76ff6856cd291b7d7ce307628ba4b8d7bc186/package.json#L3) file it is still 3.1.1

https://github.com/actions/setup-node/blob/9fc76ff6856cd291b7d7ce307628ba4b8d7bc186/package.json#L3

**Action version:**
n/a

**Platform:**
n/a
**Runner type:**
n/a

**Tools version:**
n/a

**Repro steps:**  
n/a

**Expected behavior:**
Version number in `package.json` be the same as release version.

**Actual behavior:**
`package.json` has an old version number in it.

**Comment by panticmilos** [comment]
hi @mobilutz, thank you for the report. We will take a look at it.

**Comment by panticmilos** [comment]
hi @mobilutz, this is resolved, so I am going to close the issue. Thank you again for submitting it
