### ISSUE TITLE
Support Volta for node-version-file

### ISSUE THREAD

**Issue by Vinnl** [actions/setup-node#576]
**Description:**
While `node-version-file` works well for a project like NVM, which specifies the Node version to use in a separate file, [Volta](https://volta.sh/) sets this version in a project's `package.json` by adding the following key:

```json
"volta": {
  "node": "12.20.2",
  "yarn": "1.19.2"
}
```

It would be nice to be able to specify `package.json` as a value for `node-version-file`.

**Justification:**
Volta is a popular alternative for NVM, because it's faster, and because it allows you to specify not just the version of Node, but also of the package manager to use. (In fact, that latter feature can also be used to determine the package manager to use in GH Actions.)

**Are you willing to submit a PR?**

Probably not, unless it's like half an hour work for someone new to the codebase and working on an Action (including review time).

**Comment by dmitry-shibanov** [comment]
Hello @Vinnl. Thank you for your feature request. Actually the support for installing Nodejs with volta was added. We have not released it yet. Could you please try to use the main branch to check it.

**Comment by Vinnl** [comment]
Hi @dmitry-shibanov, that's some proper turnaround time :grin: Unfortunately I'm not quite sure how to run it from a branch; do I just do

```yaml
- uses: actions/setup-node@main
```

?

**Comment by dmitry-shibanov** [comment]
> Hi @dmitry-shibanov, that's some proper turnaround time 😁 Unfortunately I'm not quite sure how to run it from a branch; do I just do
> 
> ```yaml
> - uses: actions/setup-node@main
> ```
> 
> ?

Yes, it is correct.

**Comment by Vinnl** [comment]
@dmitry-shibanov I can confirm that that is working swimmingly - [this run](https://github.com/mozilla/fx-private-relay/actions/runs/3082078789/jobs/4981348980) successfully identified our Node version from the correct `package.json`.

**Comment by dmitry-shibanov** [comment]
Thank you for your response. I'll keep the issue opened until release

**Comment by nickmccurdy** [comment]
Personally I think it would be better if Volta allowed more typical configuration, like `engines.node` and corepack's `packageManager`.

**Comment by dmitry-shibanov** [comment]
Hello everyone. We released a new [version](https://github.com/actions/setup-node/releases/tag/v3.5.0) and updated the major. The Changes should be available. For now I'm going to close the issue.
