### ISSUE TITLE
A good reason not to commit lockfiles(?)

### ISSUE THREAD

**Issue by jpw** [actions/setup-node#581]
**Description:**
Requiring a lockfile is a sensible default, but perhaps it should be a configuration option.

**Justification:**
There seems to be a strong consensus that committing a `package-lock.json` is a good idea _for applications_, for all the reasons you give in your docs.

Opinion varies [1](https://dev.to/gajus/stop-using-package-lock-json-or-yarn-lock-3ddi) [2](https://snyk.io/blog/what-is-package-lock-json/) on whether committing a `package-lock.json` is a good idea _for libraries_.

[The `package-lock.json` cannot be published to npm](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json). Therefore, when a client application of my library runs `npm i`, they install according to the `package.json` in my library and not any lockfile.

If I want to be proactively informed when a new & dubious direct or transitive dependency of my library is going to be breaking the apps of my users, I need to regularly run tests in CI without a lockfile. This is by no means robust as it's very subject to timing, but, better than nothing?

So I suggest that while requiring a lockfile is a sensible default, it should be a configuration option.

I have not thought about this problem for a few years, so apologies if wider changes in the ecosystem have rendered this point moot. I would be interested in your thoughts :)

**Are you willing to submit a PR?**

**Comment by marko-zivic-93** [comment]
Hello @jpw . Thank you for your feedback, we will investigate this and come back to you as soon as possible :)

**Comment by dmitry-shibanov** [comment]
Hello @jpw. Could you please clarify what you want ? For caching we use package-lock.json to generate hash from it. For NPM you can depend on these [file patterns](https://github.com/actions/setup-node/blob/main/src/cache-utils.ts#L16) by default. Besides, you can use [cache-dependency-path](https://github.com/actions/setup-node/blob/main/action.yml#L26-L27) input to specify the path to any file to generate hash. If you speak about removing package-lock.json from `actions/setup-node` we're not planning to do it.

**Comment by jpw** [comment]
Hi @dmitry-shibanov, thanks for looking :)

I am suggesting that `actions/setup-node` should not _require_ a `package-lock.json`, for the reasons outlined in my first comment. 

As a library maintainer, in CI, after setting up node I want to run `npm i` not `npm ci` as a next step, because that is what my users will be doing when they first install my library.

As a library maintainer I do not want deterministic builds. I want my build & tests to run against the published state of the entire dependency tree _at every new time_ the tests run, not at the _one time in the past_ the `package-lock.json` was written. I want to see the reality my users see.

Otherwise, when a package maintainer makes a breaking change semver mistake, or Something Bad happens in the NPM space which causes my users applications to explode, I do not know about it; because my tests all pass just fine because I am testing against a dependency graph that was OK at some point in the past.

IMO it does not make sense for library maintainers to commit a `package-lock.json` to a VCS. In fact it adds overhead and is a maintenance pain for zero benefit. So I don't want to add it just to run CI when it will never be used for anything else.

**Comment by dmitry-shibanov** [comment]
Hello @jpw. If you speak about removing package-lock.json from `actions/setup-node` we won't remove it because the action uses `@vercel/ncc` library to generate [dist](https://github.com/actions/setup-node/tree/main/dist) directory and we need the exact tree that is why in the CI we compare that the committed dist directory is the same as the one generated by CI for this we need package-lock.json. 
If you speak about not requiring package-lock.json for caching functionality you can override it by providing different file through `cache-dependency-path`. 

For now I'm going to close the issue.

**Comment by eddiemonge** [comment]
All the examples for `cache-dependency-path` seem to point to a `package-lock.json` file. Are there examples of using something else?

If npm installs packageA@v1.1.0 or packageB@v1.5.0, any future runs that want to install the same version should pull from the cache, instead of re-downloading them.

**Comment by dmitry-shibanov** [comment]
Hello @eddiemonge. The action uses package-lock.json for npm to generate hash for primary key. You can pass any file to `cache-dependency-path` input to change file for generating hash.
