### ISSUE TITLE
GitHub Actions: Deprecating save-state and set-output commands

### ISSUE THREAD

**Issue by Enase** [actions/setup-node#589]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by daveykane** [comment]
+1

**Comment by giordano** [comment]
Before more people will come here positing "+1", this has been already fixed by #587.  I guess a new release including that PR is needed though.

**Comment by dmitry-shibanov** [comment]
Hello everyone. We've released [a new version 3.5.1](https://github.com/actions/setup-node/releases/tag/v3.5.1) with fix for warnings. For now we didn't update the major tag. Could you please confirm that everything works as expected ?

**Comment by daveykane** [comment]
> Hello everyone. We've released [a new version 3.5.1](https://github.com/actions/setup-node/releases/tag/v3.5.1) with fix for warnings. For now we didn't update the major tag. Could you please confirm that everything works as expected ?

Yes setting to `@v3.5.1` as worked for me, thanks!

**Comment by mgregory73** [comment]
yes 3.5.1 fixed it for me. Thanks!

**Comment by dmitry-shibanov** [comment]
The major tag was updated. I'm going to close the issue.
