### ISSUE TITLE
Bundle distribution to remove 'node_modules' folder in repo

### ISSUE THREAD

**Issue by JimiC** [actions/setup-node#59]
Currently, the repo requires that the `node_modules` folder with production dependencies should be included in `VCS` (`Git`).

This can be eliminated if the distribution code gets bundled.

Please let me know if this idea is of interest. If so I could provide a PR. I'm familiar with [webpack](https://webpack.js.org/) but [roolupjs](https://rollupjs.org/guide/en/) is also a choice.

**Comment by ankri** [comment]
Let's put [ncc](https://github.com/zeit/ncc) on the list, too. I actually prefer it over webpack and rollup because of its zero config approach that even works for TypeScript projects out of the box.

**Comment by JimiC** [comment]
Worth exploring. I'm open to suggestions.

**Comment by JimiC** [comment]
Turns out that `ncc` is built on top of `webpack`. We aren't gaining anything special except the zero-config.

**Comment by bryanmacfarlane** [comment]
We have plans to integrate actions with GPR which will eliminate the need altogether.  Hopefully that will land in the coming months (no exact date yet but high on the backlog).   Action authors are free to bundle - ultimately the runner will execute the entry point of the action with node.

**Comment by JimiC** [comment]
Good to know. Feel free to close the issue if you want.

**Comment by bryanmacfarlane** [comment]
I'm going to close but also know that I'm doing a spike on ncc next week.  I want to at a minimum go through that option and weigh it against the GPR option as we design it.

Thanks for the feedback!

**Comment by bryanmacfarlane** [comment]
OK, I investigated and I'm leaning toward @ankri suggestion of [ncc](https://github.com/zeit/ncc).  It's zero config, works with typescript well (and javascript of course).  In my experiments, I combined with npx and all of the sudden you have pretty close to a tooled solution.

I'm going to re-open

**Comment by dmitry-shibanov** [comment]
Hello everyone. I'm going to close because it looks like it was resolved in this [pull request](https://github.com/actions/setup-node/pull/105). If you have any concerns, feel free to ping us.
