### ISSUE TITLE
Warning in workflow about set-output

### ISSUE THREAD

**Issue by zversal** [actions/setup-node#592]
**Description:**
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
GitHub Action runner - Current runner version: '2.298.2'
Node 16.x
npm - latest
Operating System
Ubuntu
  20.04.5
  LTS

**Repro steps:**  
![image](https://user-images.githubusercontent.com/46523773/195784294-06f69958-774b-4563-84d8-7042588b61d4.png)

**Expected behavior:**
No warnings

**Actual behavior:**
no warnings

**Comment by marko-zivic-93** [comment]
Hello @zversal 
Thank you for your issue. We will investigate it and come back to you as soon as possible :)

**Comment by dmitry-shibanov** [comment]
Hello @zversal. Thank you for your report. We released a new [version](https://github.com/actions/setup-node/releases/tag/v3.5.1) of setup-node and updated the major tag. The issue should be resolved. 
For now I'm going to close the issue. If you have any concerns feel free to ping us.
