### ISSUE TITLE
R CMD check workflow fails on ubuntu due to a syntax error

### ISSUE THREAD

**Issue by mnist91** [actions/setup-node#601]
**Description:**
When running the part to install system dependencies for ubuntu, the workflow fails with the following error:
```
Run while read -r cmd
  while read -r cmd
  do
    eval sudo $cmd
  done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')
  shell: /usr/bin/bash -e {0}
  env:
    R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    RSPM: https://packagemanager.rstudio.com/cran/__linux__/focal/latest
    GITHUB_PAT: ***
    R_LIBS_USER: /home/runner/work/_temp/Library
    TZ: UTC
    _R_CHECK_SYSTEM_CLOCK_: FALSE
    NOT_CRAN: true
/home/runner/work/_temp/e908436e-b782-4233-9475-4ddcc9f55b3c.sh: eval: line 3: syntax error near unexpected token `('
Error in writeLines(remotes::system_requirements("ubuntu", "20.04")) : 
  ignoring SIGPIPE signal
Execution halted
Error: Process completed with exit code 2.
```

**Action version:**
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
The relevant snippet:
```
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')
```
The code used for the specific task is copied from the [examples](https://github.com/r-lib/actions/blob/673b3c925483f67fa939c31748562af36bb4cde2/examples/check-full.yaml#L69)
You can find the used yaml file [here](https://github.com/mnist91/origin/blob/dev/.github/workflows/r-cmd-check-relative.yml) 

it seems to be completely unrelated to the actual R-code because the error stays the same regardless of the R command. However, I could not notice any wrong brackets etc. and carefully copied the snippet from the examples.

**Expected behavior:**
The system dependencies should be installed.

**Actual behavior:**
An error about a syntax issue is thrown.

**Comment by dmitry-shibanov** [comment]
Hello @mnist91. I'm going to close the issue because it's not related to actions/setup-node.
