### ISSUE TITLE
Deprecated set-output command is in use in versions.yml

### ISSUE THREAD

**Issue by willalder** [actions/setup-node#606]
**Description:**
The set-output command has been deprecated, but is still in use on lines 181 and 192 of versions.yml

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Node v14, Yarn v1.22.19

**Repro steps:**  
Run a job that uses setup-node@v3, select your action run, and check the summary.

**Expected behavior:**
A good, clean run with no warnings or errors.

**Actual behavior:**
The annotations for the job run include warnings that the set-output command has been deprecated, and will be disabled soon.

![set_output_warning](https://user-images.githubusercontent.com/114527213/197640652-4907c854-1b44-486f-8590-ceab106e3c54.png)

**Comment by dmitry-shibanov** [comment]
Hello @willalder. Thank you for your report. We created the [pull request](https://github.com/actions/setup-node/pull/607) to get rid of this warnings.

**Comment by willalder** [comment]
Thanks @dmitry-shibanov!  I'll watch for the fix.  Much appreciated.

**Comment by dmitry-shibanov** [comment]
Hello @willalder. We've merged it should work as expected. For now I'm going to close the issue.
