### ISSUE TITLE
Question: What is cached?

### ISSUE THREAD

**Issue by oskarkivra** [actions/setup-node#612]
**Description:**
I think the documentation is a bit unclear for the cache part. It says:

> The action has a built-in functionality for caching and restoring dependencies.

but it also says:

> Note: The action does not cache node_modules

What does it cache?

Can this be clarified or is it just me? 

**Justification:**
I'm a bit confused ;) But it might just be me.

**Are you willing to submit a PR?**
Sure, if needed.

**Comment by dmitry-shibanov** [comment]
Hello @oskarkivra. For now I'm going to close the issue.

**Comment by oskarkivra** [comment]
Yes, @dmitry-shibanov sorry for my late reply.

Thanks for your answer and the links! It is now clear to me.
