### ISSUE TITLE
Extra newline character in version output when reading from a file

### ISSUE THREAD

**Issue by raygesualdo** [actions/setup-node#618]
**Description:**

When reading the version from a file (specifically `.tool-versions` in this case), an extra newline character is included in the step output. When using the output in subsequent steps - for instance, using the version output as part of a cache key - the newline character is included. While this doesn't break the caching step, including the newline character did cause issues with some automated tooling we were building around cache management.

**Action version:**

v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

node: 16.16.0

**Repro steps:**  

I created a repo to repro the issue:

- [repo](https://github.com/raygesualdo/actions-setup-node-repro)
- [actions run](https://github.com/raygesualdo/actions-setup-node-repro/actions/runs/3330953468)

When looking at the actions run summary, one can see the additional `\n` right after the version (`v16.16.0`) in the cache keys.

**Expected behavior:**

The version output should be the exact version string with no additional whitespace.

**Actual behavior:**

The version output includes an additional newline character (`\n`) in the output.

---

The fix _seems_ to be adding a `.trim()` [here](https://github.com/actions/setup-node/blob/16352bb09bc672a073e326c2cc1d3d7d2a3e577e/src/installer.ts#L517) before returning the parsed version. I can create a PR if that path forward is acceptable.

**Comment by dmitry-shibanov** [comment]
Hello @raygesualdo. Thank you for your report. We'll investigate the issue.

**Comment by dsame** [comment]
Hello @raygesualdo i close the issue as solved with PR https://github.com/actions/setup-node/pull/625 but please feel free to reopen this issue or create new one if the problem still exists

**Comment by raygesualdo** [comment]
Thanks @dsame!
