### ISSUE TITLE
Example correction

### ISSUE THREAD

**Issue by Stanzilla** [actions/setup-node#63]
The example suggests that you can use `name: Use Node.js ${{ matrix.node }}` but that does not work and gets turned into `${{ format('Use Node.js {0}', matrix.node) }}` by GitHub

**Comment by bryanmacfarlane** [comment]
I think the example was correct but the issue was service side.  Is this still not working for you?

**Comment by Stanzilla** [comment]
Seems to work now, indeed!

**Comment by bryanmacfarlane** [comment]
Thanks for confirming!
