### ISSUE TITLE
Use package.json instead of package-lock.json

### ISSUE THREAD

**Issue by GEOEGII555** [actions/setup-node#635]
**Description:**
Describe your proposal.
I think it would be nice if this thing would support package.json

**Justification:**
Justification or a use case for your proposal.
So you aren't required to have both package and package-lock files, less data is being uploaded to GitHub

**Are you willing to submit a PR?**

No, I don't know how this thing works, I just use it in my GitHub action.

**Comment by dmitry-shibanov** [comment]
Hello @GEOEGII555. Thank you for your report. We had a discussion about removing package-lock.json and decided to keep it. You can get familiar with it in scope of this [issue](https://github.com/actions/setup-node/issues/581).

For now I'm going to close the issue.
