### ISSUE TITLE
Can't use nightly builds

### ISSUE THREAD

**Issue by MoLow** [actions/setup-node#648]
I am following the guid here https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#nightly-versions 
I recieve this output:
```
Attempting to download v20.0.0-nightly...
Not found in manifest.  Falling back to download directly from Node
Error: Unable to find Node version 'v20.0.0-nightly' for platform linux and architecture x64.
```

how ever, I have forked the repo: https://github.com/MoLow/setup-node and when pointing to my fork it does work

**Comment by dmitry-shibanov** [comment]
Hello @MoLow. Thank you for your report. We didn't release the new version of the action. You can try to use actions/setup-node@main to use nightly builds. I'll ping you when it's ready.

**Comment by MoLow** [comment]
Thanks! that makes sense

**Comment by mk-pmb** [comment]
> Unable to find Node version 'nightly' for platform linux and architecture x64.

Do I understand readme correctly that it should work? Can we re-open this issue then?
