### ISSUE TITLE
How to detect current device is Github Actions Runner ?

### ISSUE THREAD

**Issue by dimaslanjaka** [actions/setup-node#656]
I want to run `git config --global username name` inside nodejs while running inside github actions. How to detect current device is github actions runner ?

is available from `process.env.GITHUB_RUNNER` ?

**Comment by dsame** [comment]
Hello @dimaslanjaka , can you please clarify what exactly do you mean saying "current device"? OS ? Hostname? Architecture?

Also it is not clear how "current device" does relate to `git config --global user.name name`?

As [this build](https://github.com/akv-demo/setup-node-test/actions/runs/3836205854/jobs/6530120338#step:3:10) shows `git config --global user.name name` does not require any "current device" info. Neither [git-config documentation](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration) refers to any devices.

**Comment by dimaslanjaka** [comment]
> Hello @dimaslanjaka , can you please clarify what exactly do you mean saying "current device"? OS ? Hostname? Architecture?
> 
> Also it is not clear how "current device" does relate to `git config --global user.name name`?
> 
> As [this build](https://github.com/akv-demo/setup-node-test/actions/runs/3836205854/jobs/6530120338#step:3:10) shows `git config --global user.name name` does not require any "current device" info. Neither [git-config documentation](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration) refers to any devices.

yes found it 
![image](https://user-images.githubusercontent.com/12471057/210720865-01ee1ece-f38c-4c92-b113-29f4162231b3.png)

can verify with
```js
const isGithubActions = typeof process['GITHUB_WORKFLOW'] !== 'undefined';
```
