### ISSUE TITLE
Add an option to enable "engine-strict"

### ISSUE THREAD

**Issue by szepeviktor** [actions/setup-node#660]
**Description:**
Please add an option - e.g. `engine-strict: true` - to enable engine checking.

**Justification:**
I always have to add an extra CI step to enable engine checking: `npm config set engine-strict true`

**Are you willing to submit a PR?**
Good question 🙃

**Comment by dmitry-shibanov** [comment]
Hello @szepeviktor. Thank you for your suggestion. I think it should not be implemented because the configuration can be applied through one config command. 

For now I'm going to close the issue .

**Comment by szepeviktor** [comment]
Thank you.
