### ISSUE TITLE
Cross-OS Version Cache Pollution

### ISSUE THREAD

**Issue by Kurt-von-Laven** [actions/setup-node#666]
**Description:**
A cache saved on one version of a given OS can be restored on a different version of that OS. Package managers and individual packages typically assume the OS version wasn't swapped out from under them, so this can produce a wide variety of issues. See actions/cache#543 for evidence that this is a real problem with GitHub Actions in general and the officially recommended solution.

**Action version:**
v3.6.0

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Tools version:**
All

**Repro steps:**  

1. Save a cache on ubuntu-20.04, for example.
2. Attempt to restore the cache on ubuntu-22.04.

**Expected behavior:**
The cache misses and is saved again.

**Actual behavior:**
The cache hits and is restored.

**Comment by MaksimZhukov** [comment]
Hello @Kurt-von-Laven ! Thank you for reporting this!
We will take a look.

**Comment by MaksimZhukov** [comment]
Hello @Kurt-von-Laven !
The issue that you attached was posted in the cache action. The cache action provides users with the variety of settings. Using the cache action, users can specify paths to files or directories to cache and restore. Theoretically, it could cause the issue. The setup-node action caches global packages data.
Have you faced the issue when using the setup-node action? Could you please provide us with the public repository where the issue occurs for further investigation?

**Comment by MaksimZhukov** [comment]
@Kurt-von-Laven just a gentle reminder

**Comment by Kurt-von-Laven** [comment]
Thank you for the reminder. We have been unable to use the cache feature of setup-node because of this issue, but the issue is fundamental to any general-purpose cache that assumes validity across OS versions. There are many dependencies in many programming languages that rely on the stability of the underlying OS, particularly native dependencies. We first encountered this issue with a UWP (Universal Windows Platform) app where the NuGet cache had been saved on windows-2019 and restored on windows-2022, but unfortunately that repository is private. If it were generally possible to recycle dependencies across OS versions, why would there need to be different versions of Ubuntu packages (e.g., *-xenial, *-bionic, *-focal, *-jammy) for different releases, for example?

**Comment by MaksimZhukov** [comment]
I conducted the investigation and could not reproduce the issue. We also have not received any reports from customers related to cross-platform cache incompatibility since this feature was introduced to the action.

> We have been unable to use the cache feature of setup-node because of this issue

Am I right that you faced this issue using the setup-node action? Could you please provide us with the steps to reproduce it?

**Comment by MaksimZhukov** [comment]
@Kurt-von-Laven just a gentle reminder
