### ISSUE TITLE
Set a fix token in workflow yaml file, runner doesnt pick up job

### ISSUE THREAD

**Issue by yuuval** [actions/setup-node#667]
**Description:**
I want to create an AWS instance, which deploys my project from GitHub with Nginx. I'm doing this whole process with GitHub Actions. This worked, but I found out that the token expires every 60 minutes. So I added a Secret Variable in Github and added it to the Workflow file:

token: ${{ secrets.TOKEN_NAME }}
Now the workflow isn't working properly. It is running and showing this for hours:

Requested labels: self-hosted
Job defined at: yuuval/react-deploy-aws/.github/workflows/node.js.yml@refs/heads/master
Waiting for a runner to pick up this job...

This happened after I configured the token. I need this token to run a terraform file with its cloud-init, without changing any command.

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

   jobs:
     build: runs-on: self-hosted

strategy:
  matrix:
    node-version: [16.x]
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

steps:
- uses: actions/checkout@v3
- name: Use Node.js ${{ matrix.node-version }}
  uses: actions/setup-node@v3
  with:
    node-version: ${{ matrix.node-version }}
    cache: 'npm'
    token: ${{ secrets.TOKEN_NAME }}
- run: npm ci
- run: npm run build --if-present
**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows
Im on windows.

**Runner type:**
- [ ] Hosted
- [x ] Self-hosted

**Tools version:**

npm
node 16

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.
Add the token to the yaml file

**Expected behavior:**
A description of what you expected to happen.
I want that the token doesnt change its value, so i can create ec2 instances with this gitrepo with terraform and cloudinit

**Actual behavior:**
A description of what is actually happening.
Requested labels: self-hosted
Job defined at: yuuval/react-deploy-aws/.github/workflows/node.js.yml@refs/heads/master
Waiting for a runner to pick up this job...

this is running for hours

**Comment by MaksimZhukov** [comment]
Hello @yuuval ! Thank you for reporting this!
We will investigate the issue.

**Comment by MaksimZhukov** [comment]
Hello @yuuval!
In accordance with the [GitHub documentation](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret), the `GITHUB_TOKEN` expires when a job finishes or after a maximum of 24 hours. Why do you think that it expires every 60 minutes?
If you only need this token to run a terraform file with its cloud-init, you can still use the `GITHUB_TOKEN` for the setup-node action. GitHub token is used to pull node distributions from the [actions/node-versions](https://github.com/actions/node-versions) repository.
By the way, is your self-hosted runner configured and running when you start the workflow?

**Comment by yuuval** [comment]
yes it is, for a while it worked. But now the problem is again here...

**Comment by MaksimZhukov** [comment]
Have you tried updating your workflow to use the `GITHUB_TOKEN` for the setup-node action?

**Comment by MaksimZhukov** [comment]
Hello @yuuval!
Just a gentle reminder

**Comment by MaksimZhukov** [comment]
I am closing the issue due to lack of response. Please contact us if the issue still persists.
