### ISSUE TITLE
iss

### ISSUE THREAD

**Issue by NEA-cloud2** [actions/setup-node#674]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by dmitry-shibanov** [comment]
Hello @NEA-cloud2. For now I'm going to close the issue because it looks like a spam. Feel free to fill in the form and ping us.

**Comment by BRAXYBraxy1** [comment]
Ok

Pada Ahd, 22 Jan 2023, 19:36 Dmitry Shibanov ***@***.***>
menulis:
