### ISSUE TITLE
Setup node 

### ISSUE THREAD

**Issue by Samboski1** [actions/setup-node#691]
[

**Description:**

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by MaksimZhukov** [comment]
Please provide us with the issue description and we will reopen it
