### ISSUE TITLE
Error: Some specified paths were not resolved, unable to cache dependencies

### ISSUE THREAD

**Issue by rajat1saxena** [actions/setup-node#694]
**Description:**
I have a Github action to deploy as Astro site to Github Pages. Recently, it has been failing with the following error.

```
Error: Some specified paths were not resolved, unable to cache dependencies.
```

I think it is coming due to the fact that `setup-node` is trying to locate the cache inside `apps/docs` folder but since it is a monorepo, it is located two levels up.

From the job run, I noticed this:
```
cache-dependency-path: ./apps/docs/yarn.lock
```

There is no yarn.lock inside `apps/docs` since this is a monorepo.

**Action version:**
v3

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

Node 16.19
Yarn 3.2.0

**Repro steps:**  
See the Github job: https://github.com/codelitdev/courselit/actions/runs/4132972124/jobs/7142310620

**Expected behavior:**
It should not throw an error.

**Actual behavior:**
An error is thrown.

**Comment by DakkuaDev** [comment]
It happens to me the same. I am trying to deploy my site with GitHub pages using Astro and GitHub Actions. The Action failed in the same as you. What was the solution to this problem? Thanks

**Comment by Dan-Finan** [comment]
> It happens to me the same. I am trying to deploy my site with GitHub pages using Astro and GitHub Actions. The Action failed in the same as you. What was the solution to this problem? Thanks

Hi @DakkuaDev, did you manage to get around this yet? Struggling with this too!

**Comment by lemilonkh** [comment]
@Dan-Finan in my case the package-lock.json file was in .gitignore, so not part of the repository. The setup-node action was trying to access the package-lock.json file but it wasn't pushed to the repo.

**Comment by thrishank** [comment]
@lemilonkh thanks man your solution worked for me. Remove package-lock.json file from .env guys

**Comment by gfemec** [comment]
Just in case it helps someone else, I was seeing this error because my `cache-dependency-path` was part of a composite action and outside of the `github.workspace` directory. The `hashFiles` function used to hash the lock file [ignores all paths](https://github.com/actions/toolkit/blob/21229dc09e551e6da18e72e4e454ee145709c713/packages/glob/src/internal-hash-files.ts#L23) outside of `github.workspace`.
