### ISSUE TITLE
Why don't reuse the old cache when the lock file is changed?

### ISSUE THREAD

**Issue by islishude** [actions/setup-node#696]
https://github.com/actions/setup-node/blob/ae9f0f7448e93b1be0f44663e79763dbdffcc4da/src/cache-restore.ts#L28-L39

**Comment by MaksimZhukov** [comment]
Hello @islishude!
Please provide us with an appropriate description of the issue and we will reopen it.

**Comment by wmadden** [comment]
Actually @MaksimZhukov, I would love to know the answer to this question too. The OP is asking why the cache key includes the hash of the lockfile.

If I understand correctly, including the lockfile hash in the cache key means that if you update the project dependencies, the cache will be lost, and all dependencies will be downloaded anew. This has the advantage of preventing the cache growing - you cache the dependencies for a single, _exact_ install - at the cost of rebuilding the cache any time the dependencies change.

Am I missing something? Wouldn't it be better to use on only the platform and package manager in the cache key?

**Comment by say8425** [comment]
It looks like similar with my issue.
I change my package manager from yarn berry to pnpm.
After I delete my cache, but it still use yarn cache.
https://github.com/say8425/bump-test/actions/runs/4698463359/jobs/8330840049#step:3:53
