### ISSUE TITLE
How to turn off problem matcher?

### ISSUE THREAD

**Issue by azu** [actions/setup-node#72]
Hi, I want to disable problem matcher like eslint-stylish.json.

https://github.com/actions/setup-node/blob/7a3ce8362699742a34a1590e93c9b75e4d0d6dff/src/setup-node.ts#L29-L35

Because, I've created [textlint](https://github.com/textlint/textlint) that is similar with ESLint and It support same format with eslint-stylish. 

I've noticed that output formatted log in GitHub Actions, problem matcher report it as error.
But, It is just console log for testing and it is not actual error.

![image](https://user-images.githubusercontent.com/19714/67157735-44a19080-f36b-11e9-97c1-8b2bdedbed36.png)
> https://github.com/textlint/textlint/runs/267131582

Is there any chance setup-node provide an option to disable problem matcher?

## Related

- #9 #10 
- [Possible to turn off error matchers? - GitHub Community Forum](https://github.community/t5/GitHub-Actions/Possible-to-turn-off-error-matchers/td-p/31070)

**Comment by xt0rted** [comment]
Try writing out `::remove-matcher owner=eslint-compact::` in a step after `actions/setup-node` (from the [docs](https://github.com/actions/toolkit/blob/master/docs/commands.md#problem-matchers)). If you're adding your own problem matchers then you can use the same names as these and the last ones registered will take priority.

**Comment by azu** [comment]
Thanks!
