### ISSUE TITLE
Formal documentation of the `with` parameters

### ISSUE THREAD

**Issue by silverwind** [actions/setup-node#722]
**Description:**
This action is lacking formal documentation of the `with` options. Existing docs only consists of examples that don't explain the options. For example I can not find what the default value for  `registry-url` is.

**Justification:**
Every action should have formal documentation on its `with` parameters. Take [actions/checkout](https://github.com/actions/checkout#usage) as a example on how to do it right.

**Are you willing to submit a PR?**
No, i don't know the internals of the action well enough.

**Comment by dmitry-shibanov** [comment]
Hello @silverwind. Thank you for your report. We'll take a look on it.

**Comment by dmitry-shibanov** [comment]
Hello @silverwind. We updated documentation in this [pull request](https://github.com/actions/setup-node/pull/734). For now I'm going to close the feature request.
