### ISSUE TITLE
Why not cache nodejs binary? 

### ISSUE THREAD

**Issue by seepine** [actions/setup-node#723]
**Description:**
Why not cache nodejs binary, it takes a lot of time every time!!!
![image](https://user-images.githubusercontent.com/93666053/226860780-1a590df7-19b0-4e88-bb79-6c7f222e8c05.png)
Or maybe provide an option can cache nodejs binary file, give it to the user for selection

**Justification:**
I am sure it is improvement

**Are you willing to submit a PR?**

**Comment by dmitry-shibanov** [comment]
Hello @seepine. Thank you for your feature request. We're not planning to add support for caching node binaries. The initial state for setup-node caching is to cache dependency and metadata. Hosted runners have [preinstalled versions](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#nodejs) of Nodejs in the hosted toolcache directory and it won't take any time to set up this versions. If you want to cache binaries it will be better [actions/cache](https://github.com/actions/cache).

For now I'm going to close the issue.
