### ISSUE TITLE
Please list supported major versions near the top of the README

### ISSUE THREAD

**Issue by verhovsky** [actions/setup-node#724]
**Description:**
I want to know which Node versions I can test with. The only thing that looks like an answer to that question is this part of the README:

> Examples:
>
> * Major versions: 14, 16, 18

and so I assumed for the last few months (until I saw `19` in someone else's Action) that these are the only versions that were supported, because trying to figure out from the code would take a few minutes (I don't know anything about how GitHub Actions are implemented) and trying a version would take even longer and would be a waste of time if it turned out to not be supported.

**Comment by MaksimZhukov** [comment]
Hello @verhovsky!
As mentioned in the README, the action can download Node.js versions from the [dist](https://nodejs.org/dist/) so you can specify any of the versions presented there:
> The action will first check the local cache for a semver match. If unable to find a specific version in the cache, the action will attempt to download a version of Node.js. It will pull LTS versions from [node-versions releases](https://github.com/actions/node-versions/releases) and on miss or failure will fall back to the previous behavior of downloading directly from [node dist](https://nodejs.org/dist/).

You also can specify [canary](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#v8-canary-versions), [nightly](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#nightly-versions) and [rc](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#rc-versions) versions.

I am closing the issue, but feel free to contact us if you have any questions.
