### ISSUE TITLE
Remove `--frozen-lockfile` for pnpm deps installation in document

### ISSUE THREAD

**Issue by SnO2WMaN** [actions/setup-node#725]
**Description:**

In below documents `pnpm install --frozen-lockfile`, but pnpm passes the `--frozen-lockfile` option automatically when it detects that it is running on CI (i.e. on GitHub Actions).

https://github.com/actions/setup-node/blob/a4fcaaf314b117a40d694a35ee36461f8ff3c6e6/docs/advanced-usage.md#L246-L266

I thought it seems that it is better not to pass it explicitly in document, so as not to cause unnecessary confusion.

References
- https://pnpm.io/cli/install#--frozen-lockfile
- https://github.com/watson/ci-info#supported-ci-tools

**Are you willing to submit a PR?**

Yes

**Comment by dmitry-shibanov** [comment]
Hello @SnO2WMaN. Thank you for your suggestion. Do these changes apply to `pnpm 6.10+` versions ?

**Comment by dmitry-shibanov** [comment]
Hello @SnO2WMaN. I'm going to close the feature request because we've updated the documentation in scope of this pull request: https://github.com/actions/setup-node/pull/789
