### ISSUE TITLE
Serial USB Terminal 20230413-211152

### ISSUE THREAD

**Issue by IRI131981** [actions/setup-node#740]
20:55:36.361 USB device detected
20:55:39.688 Connected to CDC device
20:59:59.540 Connection lost
21:00:10.334 USB device detected
21:00:13.605 Connected to CDC device
21:00:33.481 Importing configuration from file:
- imported 2 changed values
- ignored 22 unchanged values
21:01:26.874 Upload 'usb_driver_r13-windows.zip' started
21:01:32.623 Upload canceled
21:01:32.600 Connection lost
21:02:00.660 Connected to CDC device
21:02:05.458 
21:02:41.187 Upload 'android-11-cdd.pdf' started
21:11:27.769 Upload finished
21:11:36.275

**Comment by boy520520456** [comment]
看不懂

**Comment by boy520520456** [comment]
[
/](url)

**Comment by boy520520456** [comment]
我將他們退定了，我知道你不喜歡她們，我就退了她們
