### ISSUE TITLE
Android Studio - Google Търсене

### ISSUE THREAD

**Issue by IRI131981** [actions/setup-node#747]
https://www.google.com/search?hl=bg&sxsrf=APwXEde99KYsTubWsuCTu5P5gfn66a-CZg:1682668377142&si=AMnBZoG3cRyxvViEiVWeqgrn-CuWcnxp6_6_G7EH225wAKYHQgmAvjBd2LCVXd0uXigEwx1meoxqgOBuFB1n1dxYxIi9RSARoTi3Cc_wtOC6csuhxIB7-lNggZmWcOdhwMXVgTkfxxG4g-0Y9CgjkHPtCmsp1RWCkNaqITdHxnvSqX1mHM3OWHCUgyM2gf7kw2SMx-eFfID1zqzT8nxhiMSfY9KuON1l5UOOGPvoZg41jna5M2sujrqlLjEuRPICMXpL8Tjwr4vBjsA9w0r5Kymfe6TKI5m8g0kDcBoOqtVrXD-Jpma1emU%3D&q=Android+Studio&sa=X&ved=2ahUKEwjStJOXjMz-AhWyWaQEHV-HAt8Qs9oBKAJ6BAgdEAY&biw=491&bih=984&dpr=2.2

**Comment by IvanZosimov** [comment]
I'm closing this issue as a spam.
