### ISSUE TITLE
`Unable to find Node version 'lts'`

### ISSUE THREAD

**Issue by tmillr** [actions/setup-node#761]
**Description:**

The docs say:

```yml
    # Version Spec of the version to use in SemVer notation.
    # It also emits such aliases as lts, latest, nightly and canary builds
    # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
    node-version: ''
```

...but when you set node-version to `lts`, the action fails with `Error: Unable to find Node version 'lts' for platform linux and architecture x64`.

<img width="1128" alt="Screenshot 2023-05-25 at 7 58 00 PM" src="https://github.com/actions/setup-node/assets/45028928/65d7496f-94bb-44ee-a7f9-02ef2ec7dd41">

---

**Action version:**

`actions/setup-node@v3`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**

https://github.com/projekt0n/github-nvim-theme/blob/20a949da713b58f28ba6af153a7d1691933ac942/.github/workflows/update-colors.yml

**Expected behavior:**

Download/use the current lts version of node.

**Actual behavior:**

_See above_

---

Is this a bug? Is there an alternative way to achieve specifying the current lts (such that it will dynamically track/obtain whatever the current lts version is at runtime)?

Maybe my memory is simply failing me, but I could have sworn this used to work.

Thank you

**Comment by tmillr** [comment]
Oh, I apologize, it seems the issue is that `lts` is an invalid alias (it's supposed to be `lts/*`). Maybe this could be added to the README? E.g. something like:

```diff
 - uses: actions/setup-node@v3
   with:
     # Version Spec of the version to use in SemVer notation.
-    # It also emits such aliases as lts, latest, nightly and canary builds
-    # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
+    # lts, latest, nightly and canary build aliases are allowed.
+    # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, lts/*, 16-nightly, latest, node
     node-version: ''
```

**Comment by dusan-trickovic** [comment]
Hello, @tmillr ! Thank you for creating the issue! We will take a look at it and see what can be done :)

**Comment by dusan-trickovic** [comment]
Hello again, @tmillr ! I would like to tell you that the suggestion you made with your last comment in regards to editing the README, although good, we think would be somewhat unnecessary, as there is already something along those lines explained in [this section](https://github.com/actions/setup-node#supported-version-syntax) - specifically, the `NVM LTS syntax:` section.

We hope this answered your question. I will close this issue now, but in case you have encountered any additional obstacle while using our software that you would like us to investigate, please feel free to create a new issue at any time :) 

Thank you for your input and cooperation!

**Comment by tmillr** [comment]
> Hello again, @tmillr ! I would like to tell you that the suggestion you made with your last comment in regards to editing the README, although good, we think would be somewhat unnecessary, as there is already something along those lines explained in [this section](https://github.com/actions/setup-node#supported-version-syntax) - specifically, the `NVM LTS syntax:` section.
> 
> We hope this answered your question. I will close this issue now, but in case you have encountered any additional obstacle while using our software that you would like us to investigate, please feel free to create a new issue at any time :)
> 
> Thank you for your input and cooperation!

Thank you, but I disagree. Let me explain.

1. I'm not the only one having the same issue. Just since opening this, at least one other person has stumbled upon this footgun.
2. It's a 5 min or less fix (unless there's a build process or something that I am not aware of).

Yes, technically it is documented clearly (further down the README), but in-practice, developers who have used this action before in the past are not going to read much of the README if at all (rather they are probably going to be relying on either: their memory, the yaml, or just the very top of the README which displays the yaml). The wording in the yaml is confusing: `It also emits such aliases as lts`? Does that not sound like it is saying that `lts` is a valid alias?

But that's all I am going to say about. You guys can choose to improve it or not, but I do acknowledge that it is a small issue and not a major one.

Thank you for the swift and friendly support.

**Comment by T3rm1** [comment]
The readme is just wrong. It says you can use `lts`. But you can't. So fix this. It doesn't matter if there are examples somewhere further down that add an explanation how to actually use it correctly.

**Comment by wozzo** [comment]
@dusan-trickovic It seems several people are hitting this, and since there's a PR to add a clarifying note what's the harm in updating it so that others don't have to go through the pain of searching through issues/docs etc?

**Comment by BenjaminNolan** [comment]
+1 for clarifying the README comment, as it currently still reads as if `node-version: lts` is intended to be used the same as `latest` and `nightly`, when it is not.

**Comment by zeeshanpolaris** [comment]
I just ran in to this issue and I suggest updating README asap.
