### ISSUE TITLE
why check `yarn.lock` if exists in setup node step?

### ISSUE THREAD

**Issue by HomyeeKing** [actions/setup-node#762]
**Description:**
why need `yarn.lock` in this step?
![image](https://github.com/actions/setup-node/assets/49113249/712e0af6-a3a5-40e2-a2bb-02920e4d9d34)

**Action version:**
actions/setup-node@v3

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

 node: v18.16.0
  npm: 9.5.1
  yarn: 1.22.19
**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.
https://github.com/HomyeeKing/gito/actions/runs/5127932734/jobs/9224109716
**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by dusan-trickovic** [comment]
Hello, @HomyeeKing ! Thank you for creating the issue, we will take a look at it :)

**Comment by nikolai-laevskii** [comment]
Hello! Thanks for the feedback. It seems like `yarn.lock` is required because in your current worklfow yarn is selected for caching options. `yarn.lock` file is used as hash in this case.

https://github.com/HomyeeKing/gito/actions/runs/5127932734/workflow#L54

**Comment by HomyeeKing** [comment]
how to specify the `yarn.lock` path if it's a monorepo? I've tried `default-> working-directory`, not works
