### ISSUE TITLE
Downloading from nodejs.org failing

### ISSUE THREAD

**Issue by paglias** [actions/setup-node#77]
I'm not sure this is the best repo to report the issue, if it's the wrong place please close this :)

We've been using Github Actions successfully for a few days but starting today all our builds have started to fail at the `setup-node` step with this error:

```

4m 57s
##[error]Node run failed with exit code 1
Run actions/setup-node@v1
  with:
    node-version: 12.x
    always-auth: false
/bin/tar xzC /home/runner/work/_temp/83341e1a-c86d-4ddb-9963-ef01607f6e1e -f /home/runner/work/_temp/58fc8365-fe95-474e-ad3c-c5511594abdd

gzip: stdin: unexpected end of file
/bin/tar: Unexpected EOF in archive
/bin/tar: Unexpected EOF in archive
/bin/tar: Error is not recoverable: exiting now
##[error]The process '/bin/tar' failed with exit code 2
##[error]Node run failed with exit code 1
```

Attaching a screenshot for more clarity
<img width="1114" alt="Schermata 2019-10-23 alle 16 22 25" src="https://user-images.githubusercontent.com/589911/67403285-faf6b700-f5b1-11e9-98fe-fa0c96a59aec.png">

You can see an example of a failed build here https://github.com/HabitRPG/habitica/pull/11474/checks?check_run_id=271716057.

The code of the workflow is the standard one that can be seen in the official docs

```
steps:
.....
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
....
```

**Comment by rashedmyt** [comment]
I am also having the same issue

**Comment by chingc** [comment]
I'm also having the same problem.  One thing I noticed on my CircleCI builds is nvm is failing to download nodejs.  The download is so slow that it will timeout, then the installation fails due to an incomplete download.

I'm think it might be a similar problem affecting this action.  If it's the same issue, it would be nice if there was some kind of automatic resume so it doesn't keep trying to download from the beginning.

**Comment by abatilo** [comment]
I'm having the same problem!

**Comment by dijam** [comment]
I retied couple of times. Waited 10 min, a cup of coffee, tried again and it worked.

**Comment by vibou** [comment]
Same here ! What's going on !

**Comment by timofeee** [comment]
Just experimenting right now with Actions, good to know it's not something I messed up

**Comment by nicubarbaros** [comment]
Same here! AAF

**Comment by andrew-boyd** [comment]
Possibly related to widespread DNS issues from AWS?

**Comment by simon300000** [comment]
Having problem with node 12 ubuntu-latest

**Comment by nicubarbaros** [comment]
Suddenly completed after rerunning the same action couple of times

**Comment by vibou** [comment]
Did you run the action with the re-run check or you trigger the workflow with an event ?

**Comment by panva** [comment]
<img width="813" alt="Screenshot 2019-10-23 18 00 21" src="https://user-images.githubusercontent.com/241506/67412145-08ff0480-f5bf-11e9-80ae-e3f2b90a3086.png">

dtto, only a different error.

**Comment by dmail** [comment]
I encountered a 500 error once too, maybe unrelated.

**Comment by panva** [comment]
> I encountered a 500 error once too, maybe unrelated.

saw that too

**Comment by tunnckoCore** [comment]
Nope. It's because of the action, I'm sure.

**Comment by simon300000** [comment]
I just noticed node published v13 yesterday, might it be related?

**Comment by panva** [comment]
> I just noticed node published v13 yesterday, might it be related?

No, i had node 13 builds running fine 7 hours ago.

**Comment by chingc** [comment]
It's a download issue.  Node is failing to download which causes `tar` or `7z` to fail when trying to extract.

See this issue: https://github.com/nodejs/build/issues/1993

**Comment by wildone** [comment]
You need to manually pass the env to your install/publish steps due to the fact https://github.com/actions/setup-node/issues/78

**Comment by nicubarbaros** [comment]
> Did you run the action with the re-run check or you trigger the workflow with an event ?

Rerun check

**Comment by tunnckoCore** [comment]
It's working for couple of hours already.

**Comment by rigobcastro** [comment]
Same issue here

![image](https://user-images.githubusercontent.com/1006483/67498323-db5c9e80-f644-11e9-8055-48c2c448a5ce.png)

**Comment by edward-soetiono-asto** [comment]
lost so many hours from this error

any alternative?

**Comment by tunnckoCore** [comment]
as I understand it's upstream, so...

**Comment by bryanmacfarlane** [comment]
UPDATE:

Yes, it's external and nodejs downloads (not a CDN) is having.  This action just downloads from their endpoint.

https://github.com/nodejs/build/issues/1993

We do have a workitem to cache the latest of each major version on our hosted images and this action checks that cache first (resolved the semver you supply against the cache and if not there queries the cloud).

Downside is you may not get absolute latest (image gen'd yesterday, patch released today).  but we have a plan for that as well - an option in the action to always query for cloud first.  

You could also fall back on failure the only issue with that takes a long time every invocation when an issue like this is happening and it's a fresh machine every time.

Thoughts?

**Comment by chingc** [comment]
@bryanmacfarlane I think adding automatic resume to interrupted downloads would be great too.  From what I can tell, the file IS being downloaded but it's so slow it can't finish before timing out.

**Comment by blane1988** [comment]
Same. The past hour has seen many failures for the Node action. Some jobs it will work, but most don't.

**Comment by Avinger27** [comment]
Running into this today. is anyone still facing this issue?

**Comment by blane1988** [comment]
@Avinger27 It is running fine for me. Are you still facing the issue?

**Comment by daiky00** [comment]
I just ran into this issue today

**Comment by Etherdaemon** [comment]
Facing this issue today on Azure DevOps - I've had 1 build go past the nodeTool install successfully out of 8 so far.

**Comment by ssannidhi-palo** [comment]
Facing this issue today on github actions, with ubuntu-18.04 and node 12.14

  test:
    runs-on: ubuntu-18.04
    name: Run unit & integration tests
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.14

![image](https://user-images.githubusercontent.com/54425886/75125800-f7a34180-56f1-11ea-93e1-9d94ed8b7d4d.png)

**Comment by kitmoovup** [comment]
Same issue.

**Comment by adjikpo** [comment]
<img width="1050" alt="Capture d’écran 2020-02-24 à 23 36 34" src="https://user-images.githubusercontent.com/44362825/75197437-8fd71000-575e-11ea-8476-ebd867a69ef9.png">


my yaml:
`name: Lint Dockerfile
on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Dockerfile
        uses: actions/checkout@v1
      - name: Dockder
        run: curl -sSL https://get.docker.com  | sh
      - name: Hadolint 
        run: docker run --rm -i hadolint/hadolint:latest-debian < Dockerfile`

**Comment by Duchynko** [comment]
We had the same problem recently. It took 9 minutes for the action to finish.

![image](https://user-images.githubusercontent.com/31277153/78559560-dc5d4300-7814-11ea-82bf-8a1745ee9868.png)

```yaml
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    env:
      CI: 1

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
```

**Comment by Kostanos** [comment]
the similar issue maybe?
![image](https://user-images.githubusercontent.com/1136702/82230892-0423e880-9935-11ea-9e0a-03e800518d55.png)

**Comment by gustavlindstroms** [comment]
My issue might be realated

![image](https://user-images.githubusercontent.com/44166712/91657348-94d79c00-eac0-11ea-85ac-2da5c4494154.png)

**Comment by dmitry-shibanov** [comment]
Hello everyone. We released tag v2 for setup-node. It should resolve some issues related downloading. For details you can take a look on this [comment](https://github.com/actions/setup-node/issues/160#issuecomment-642739512) and issue.
For now I'm closing the issue. If you have any concerns feel free to ping us.
