### ISSUE TITLE
This also needs to the change to `action.yml` here: https://github.com/actions/setup-python/pull/443/files

### ISSUE THREAD

**Issue by Anglemmj7** [actions/setup-node#777]
This also needs to the change to `action.yml` here: https://github.com/actions/setup-python/pull/443/files

On GHES, this will start using `GITHUB_TOKEN` ([the default value for the `token` input](https://github.com/actions/setup-node/blob/788c6ccbd0d6bddb637da16397c675d9e1c6f93c/action.yml#L23)) to make calls to github.com.  But, the GHES token isn't valid on github.com.

_Originally posted by @brcrista in https://github.com/actions/setup-node/pull/595#pullrequestreview-1151529649_

**Comment by dusan-trickovic** [comment]
Closing because it seems to be spam
