### ISSUE TITLE
Node distribution 

### ISSUE THREAD

**Issue by Anglemmj7** [actions/setup-node#778]
> Node distributions are now available from https://github.com/actions/node-versions for reliability since the releases are backed by a CDN. That repo offers a versions-manifest.json which abstracts away the location of each version. Therefore in the future it could move from releases to some other CDN or endpoint. This set of changes queries the versions-manifest against the node version semver spec provided by the workflow to resolved to latest for that spec. If not found in the versions-manifest, it falls back to the node dist ( https://nodejs.org/dist/index.json )

_Originally posted by @Anglemmj7 in https://github.com/actions/setup-node/issues/147#issuecomment-1585586203_

**Comment by dusan-trickovic** [comment]
Closing because it seems to be spam
