### ISSUE TITLE
Please remove core.exportVariable('NODE_AUTH_TOKEN', 'XXXXX-XXXXX-XXXXX-XXXXX');

### ISSUE THREAD

**Issue by wildone** [actions/setup-node#78]
Please remove export debug variable that overrides existing variables.
This call just kills the existing NODE_AUTH_TOKEN that passed!

**Comment by bryanmacfarlane** [comment]
Should we only set if it's not set?

**Comment by maxim-lobanov** [comment]
Hello everyone!
We have merged https://github.com/actions/setup-node/pull/205 with fix and released `v2.1.4` with this fix.
Also released stable `actions/setup-node@v2` that points to 2.1.4.
I am going to close this issue for now but please let us know if you have any concerns or you still experience any issues.
