### ISSUE TITLE
Unable to reuse cached tools on arch armv7 (Raspberry)

### ISSUE THREAD

**Issue by louislam** [actions/setup-node#793]
**Description:**

On armv7, setup-node will download Node.js from official and extract to `_work/_tool/node/18.16.1/armv7l`.

However, setup-node is searching for the cache in `_work/_tool/node/18.16.1/arm` instead of `_work/_tool/node/18.16.1/armv7l`. As a result, it can never hit the cache.

My current workaround:
Manually rename the directory from `armv7l` to `arm`, `setup-node` will be able to use cached tool in the next run.

Log: https://github.com/louislam/uptime-kuma/actions/runs/5456311185/jobs/9928952991?pr=3354

The image shows that the directory name do not match.
<img src="https://github.com/actions/setup-node/assets/1336778/0ba649dc-53e5-4bcd-a1e8-7c2e1c3b2068" width="600">

**Action version:**
4.305.0

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows
- [x] Raspbian Buster (Similar to Debian) (Raspberry Pi400) (Arch: armv7)

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
- Node.js 14, 18
- npm

**Repro steps:**  

Option 1:
In case you don't have such hardware. You can fork this pr and create pr on my repo if you want to test: https://github.com/louislam/uptime-kuma/pull/3354/. The job `armv7-simple-test (ARMv7, 16)` is always reproducible. 

Option 2:
- Any workflow file, example: https://github.com/louislam/uptime-kuma/blob/98b16739d0aecd08cb7f150bb9aac7a11b39bd8d/.github/workflows/auto-test.yml
- Setup a action runner on Raspberry Pi (armv7)
- Run it several times, non-first runs should keep downloading Node.js.

**Expected behavior:**
Node.js could be reuse in the next run.

**Actual behavior:**
Node.js will be downloaded for every run, the cached tool is never used.

**Comment by dusan-trickovic** [comment]
Hello @louislam ! Thank you for creating the issue and the PR :) We will investigate them and see what can be done

**Comment by dmitry-shibanov** [comment]
Hello @louislam. The [pull request](https://github.com/actions/setup-node/pull/794) was merged. Could you please try to use `actions/setup-node@main` to confirm that it works as expected?

For now I'm going to reopen the issue because I'd like to close when the new version of setup-node is released.

**Comment by louislam** [comment]
@dmitry-shibanov I can confirm it is fixed, it is now looking for `armv7l` instead of `arm`. Thank you.


![image](https://github.com/actions/setup-node/assets/1336778/da972c8b-cb4f-4da5-906b-de2871131336)



Full Log:
https://github.com/louislam/uptime-kuma/actions/runs/5532726517/jobs/10095225803?pr=3354

**Comment by louislam** [comment]
Tested 3.8.0 and double confirmed that it has been fixed.
