### ISSUE TITLE
v3.7.0 is a breaking change

### ISSUE THREAD

**Issue by eddiemonge** [actions/setup-node#814]
Version 3.7.0 is a breaking change. Does this project follow semver? If not, I'll pin my project to use 3.6.0 until 3.7.0 is fixed (see https://github.com/actions/setup-node/issues/797#issuecomment-1640885997).

If this was not meant to be a breaking change, I suggest unpublishing version 3.7.0 or doing a patch version to revert functionality

**Comment by dmitry-shibanov** [comment]
Hello @eddiemonge. Thank you for your report. I think it is not a breaking change because regarding to the thread it didn't work as expected initially because of parsing logic that is why on the post step the action was getting different value.

**Comment by eddiemonge** [comment]
Changing the default or expected value from null to string would seem to me to be breaking. One day my gh actions worked, and the next, they didn't, without my code changing. I would consider that a breaking change, since it had been that way all of 3.x

**Comment by dmitry-shibanov** [comment]
Could you please describe your case with changing value from null to string? Do you mean post input or what ?

**Comment by dmitry-shibanov** [comment]
Hello @eddiemonge. Could you please try to use changes changes from the main branch ?

**Comment by dmitry-shibanov** [comment]
Hello @eddiemonge. The [new versions of setup-node](https://github.com/actions/setup-node/releases/tag/v3.8.0) was released. For now I'm going to close the issue.
