### ISSUE TITLE
Make it possible for "version" changes in package-lock.json not bust the cache

### ISSUE THREAD

**Issue by mpereira** [actions/setup-node#832]
Hi,

When I release new versions of "app", I bump the "version" field in the package-lock.json file. For example, from `0.0.1` to `0.0.2`.

Even when there's no changes in the "packages" or "dependencies" keys, this is sufficient to bust the setup-node cache, because it hashes the entire package-lock.json file.

Would it be possible to somehow support this workflow? Maybe only bust the cache when the "packages" or "dependencies" contents change? 

**package-lock.json**
```json
{
  "name": "app",
  "version": "0.0.1",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    <...>
  },
  "dependencies": {
    <...>
  }
}
```

**Comment by dmitry-shibanov** [comment]
Hello @mpereira. Thank you for your feature request. We'll take a look on it.

**Comment by dmitry-shibanov** [comment]
Hello @mpereira. For now I'm going to close the feature request because we're not planing to implement it. The hash for primary key is generated from package-lock.json by default. We can't verify if the only version was changed. If you have any concerns feel free to ping us.
