### ISSUE TITLE
Cannot deploy to npm registry with scoped package

### ISSUE THREAD

**Issue by samuelmanzanera** [actions/setup-node#874]
**Description:**
I can't deploy to NPM using Github Action when I used a scoped package.

**Action version:**
Specify the action version: v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

npm: 8.19.4
node v16.20.2

**Repro steps:**  

Here the link of the Github Action workflow which failed: 

https://github.com/archethic-foundation/libjs/actions/runs/6571556524/job/17850963499

**Expected behavior:**
I expect the publishing to work, as it's working locally without Github Action.

**Actual behavior:**
It seems the NPM package doesn't find the package with the scope.

**Comment by nikolai-laevskii** [comment]
Thank you for reporting the issue! We will investigate it and come back to you with the details!

**Comment by dmitry-shibanov** [comment]
Hello @samuelmanzanera. Sorry for the late response. Could you please try to use [scope input](https://github.com/actions/setup-node/blob/main/action.yml#L19-L20).

**Comment by samuelmanzanera** [comment]
> Hello @samuelmanzanera. Sorry for the late response. Could you please try to use [scope input](https://github.com/actions/setup-node/blob/main/action.yml#L19-L20).

Thanks for the reply and sorry for the delay.

I did try this strategy but it doesn's ended well.

You can see the result of the github action: https://github.com/archethic-foundation/libjs/actions/runs/8138807417/job/22240484834

And the commit about the changes in the .yaml: https://github.com/archethic-foundation/libjs/commit/7c2484b73791c874518f3d8031ab52b8ab811cd4

Is it only working with Github package registry ?

**Comment by samuelmanzanera** [comment]
> > Hello @samuelmanzanera. Sorry for the late response. Could you please try to use [scope input](https://github.com/actions/setup-node/blob/main/action.yml#L19-L20).
> 
> Thanks for the reply and sorry for the delay.
> 
> I did try this strategy but it doesn's ended well.
> 
> You can see the result of the github action: https://github.com/archethic-foundation/libjs/actions/runs/8138807417/job/22240484834
> 
> And the commit about the changes in the .yaml: [archethic-foundation/libjs@7c2484b](https://github.com/archethic-foundation/libjs/commit/7c2484b73791c874518f3d8031ab52b8ab811cd4)
> 
> Is it only working with Github package registry ?

Any idea or news about this subject ?

**Comment by gowridurgad** [comment]
Hi @samuelmanzanera, we are able to successfully publish the scoped package to the npm registry using GitHub Actions. Please find the attached screenshot for your reference:
These are some troubleshooting steps to help resolve the issue.

- **Permission Issues:** Might not have the necessary permissions to publish the package.
- **NPM Authentication:** There might be an authentication issue with npm, such as incorrect tokens or expired credentials.
- **Scoped Package Configuration:** The package scope might not be correctly defined in the package.json file.
- **Two-Factor Authentication (2FA):** If your npm account has two-factor authentication (2FA) enabled, ensure you are using an automation token that bypasses the OTP requirement.
- **Package Access:** Ensure that the package you are trying to publish is not already taken on the npm registry. Scoped packages should be unique within the scope.
- **Ensure Correct Scope:** Verify the scope in your package.json matches your NPM user or organization:
                                  {
                                       "name": "@your-username/your-package",
                                       "version": "1.0.0"
                                      // other fields
                                  }

I hope this helps! Let us know if you need any further assistance.

**Comment by gowridurgad** [comment]
Hi @samuelmanzanera, Just a gentle reminder regarding this issue, If you have any updates or need further assistance, Please let us know.

**Comment by gowridurgad** [comment]
Hi @samuelmanzanera, Just a gentle reminder regarding this issue, If you have any updates or need further assistance, Please let us know.

**Comment by gowridurgad** [comment]
Hi @samuelmanzanera, Due to inactivity, I'm going to close this issue for now. Please feel free to reopen this issue or create a new one if necessary. Thank you.
