### ISSUE TITLE
The e2e-cache tests are failing on Yarn 1 (Node 14)

### ISSUE THREAD

**Issue by trivikr** [actions/setup-node#881]
**Description:**

The e2e-cache tests are failing on Yarn 1 (Node 14)

**Action version:**
N/A, the issue is in CI

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted

**Tools version:**
Yarn 1

**Repro steps:**  
https://github.com/actions/setup-node/actions/workflows/e2e-cache.yml?query=is%3Afailure

**Expected behavior:**
Yarn 1 (Node 14) to be either successful, or removed.

**Actual behavior:**
Failing with the following error:

```console
yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
error @azure/core-util@1.[6](https://github.com/actions/setup-node/actions/runs/6630653626/job/18027423341?pr=880#step:8:7).1: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.21.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by nikolai-laevskii** [comment]
Thank you for the issue! We'll look into it and come back with the details

**Comment by trivikr** [comment]
> We'll look into it and come back with the details

I've posted a fix at https://github.com/actions/setup-node/pull/882

**Comment by maoryadin** [comment]
I have also yarn 1.22.21, and also for me it happens: .nvmrc is v21.5.0 and it install 20.8.1:
The engine "node" is incompatible with this module. Expected version ">= 21.1.0". Got "20.8.1"
@trivikr
