### ISSUE TITLE
How is yarn getting installed?

### ISSUE THREAD

**Issue by BrandonLWhite** [actions/setup-node#89]
I cannot determine by what mechanism yarn is getting installed by this action.  I was hoping to find something explicit in the code that is downloading and installing it, but I found no mention of yarn.

Could you please clarify how setup-node is ensuring that yarn gets installed?

**Comment by phartenfeller** [comment]
Yarn is automatically preinstalled with hosted runners. [(docs)](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners)

**Comment by RammusXu** [comment]
> Yarn is automatically preinstalled with hosted runners. [(docs)](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners)

How if I run on self-hosted runner? Should I install yarn in my runner?

**Comment by phartenfeller** [comment]
> What if I run on self-hosted runner? Should I install yarn in my runner?

Yes, only the runner gets installed.

You can simply install it on the machine and the runner can access it. You don't have to do it in the workflow itself.

**Comment by bryanmacfarlane** [comment]
questions answered ☝️
