### ISSUE TITLE
Update/Add node-versions linux-arm64

### ISSUE THREAD

**Issue by kevcube** [actions/setup-node#890]
### Tool name

https://github.com/actions/node-versions

### Tool license

idk

### Add or update?

- [ ] Add
- [X] Update

### Desired version

linux-arm64

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by shamil-mubarakshin** [comment]
Hi @dmitry-shibanov, could you have a look please?

**Comment by mikhailkoliada** [comment]
@dmitry-shibanov could you take a look please?

**Comment by dmitry-shibanov** [comment]
Hello @kevcube. Thank you for your report. We upload to node-versions lts Node.js versions supported by hosted runners. For now we do not have Linux with arm64 that is why we're not going to upload Node.js versions with arm64 architecture.

For now I'm going to close the issue.
