### ISSUE TITLE
@aaemnnosttv @dmitry-shibanov @masoudahg000 @masoudahgl @masley100 @masoudahg0000 @masoudleyli

### ISSUE THREAD

**Issue by Masoudleyli** [actions/setup-node#897]
@aaemnnosttv @dmitry-shibanov @masoudahg000 @masoudahgl @masley100 @masoudahg0000

_Originally posted by @Masoudleyli in https://github.com/actions/setup-node/pull/646#pullrequestreview-1733504124_

**Comment by MaksimZhukov** [comment]
I am closing the issue as spam
