### ISSUE TITLE
Ability to use buildjet/cache instead of actions/cache

### ISSUE THREAD

**Issue by divmgl** [actions/setup-node#909]
**Description:**
We use Buildjet which has significantly faster runners than the GitHub Actions ones. We currently use `actions/setup-node` which does a lot of the heavy lifting to setup Node and a cache for our package manager, `pnpm`.

It'd be nice if we could use [`buildjet/cache`](https://buildjet.com/for-github-actions/blog/launch-buildjet-cache) instead of `actions/cache` which is a drop-in replacement.

**Justification:**
I want to use `buildjet/cache` instead of `actions/cache`.

**Are you willing to submit a PR?**
Unfortunately I don't currently have time to devote to this.

**Comment by marko-zivic-93** [comment]
Hello @divmgl 
Thank you for creating this feature request. We will investigate it and come back to you as soon as possible.

**Comment by dmitry-shibanov** [comment]
Hello @divmgl. The action does not use `actions/cache`. The setup-node uses [toolkit/cache](https://github.com/actions/toolkit/tree/main/packages/cache) to implement logic regarding to caching. Besides, If you use actions/setup-node or any other actions on GitHub hosted runners the same runners will be used. 

For now I'm going to close the feature request.
