### ISSUE TITLE
action.yml

### ISSUE THREAD

**Issue by Kopipa** [actions/setup-node#910]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by marko-zivic-93** [comment]
Hello @Kopipa 
I will close this issue. If you think this is a mistake please feel free to re-open it.
