### ISSUE TITLE
npm auth doesn't work with .npmrc placed in repo

### ISSUE THREAD

**Issue by jeetiss** [actions/setup-node#92]
npm auth doesn't work with `.npmrc` in repo

without `.npmrc` everything works fine, but I wanna use `.npmrc` in my repo 

### Repo:
https://github.com/jeetiss/try-shipjs/

### Failed auth:
https://github.com/jeetiss/try-shipjs/commit/984794dddaf7ea4ac5e05894a0067a6df7b03c0c/checks?check_suite_id=338218393#step:6:49

### - .npmrc
https://github.com/jeetiss/try-shipjs/commit/ea5696a8f7ac23c7027f22debb884fa1f75b0c97

### Auth works:
https://github.com/jeetiss/try-shipjs/commit/052af5771ec0637952ea575f4230f662672935ed/checks?check_suite_id=339088221#step:6:48

**Comment by jeetiss** [comment]
related to #87

**Comment by dmitry-shibanov** [comment]
Hello @jeetiss.
For now I'm closing the issue, because it looks like the issue with `shipjs`. If you have any concerns feel free to contact us.
