### ISSUE TITLE
Unable to set up Node 18 using self-hosted runners

### ISSUE THREAD

**Issue by prateekg17** [actions/setup-node#933]
**Description:**
Unable to set up Node 18 using self-hosted runners, we get a timeout while trying to download Node 18.19.0 from [](https://github.com/actions/node-versions/releases/download/18.19.0-7042590257/node-18.19.0-linux-x64.tar.gz)
github.com is set up for egress for the self-hosted runner

**Action version:**
v3

**Platform:**
- [ ] Ubuntu

**Runner type:**
- [ ] Self-hosted

**Tools version:**
node version = v18.19.0

**Repro steps:**  
- Use self-hosted runner with a Linux machine which has the configuration [self-hosted, linux, X64]
- Configure github.com as egress for the self-hosted runner to allow it connect with github for Node dependencies.
- Define a workflow which makes use of self-hosted runner, checks out the code and then uses the set up node action
- We are using the basic action i.e.
![image](https://github.com/actions/setup-node/assets/122030949/e3e05237-9ddb-4be4-a5c4-e0106df39afc)

**Expected behavior:**
Node is set up and we are able to progres further.

**Actual behavior:**
We receive a timeout error after retrying for 3 times. The following error is received:
```
Acquiring 18.19.0 - x64 from https://github.com/actions/node-versions/releases/download/18.19.0-7042590257/node-18.19.0-linux-x64.tar.gz
##[debug]Downloading https://github.com/actions/node-versions/releases/download/18.19.0-7042590257/node-18.19.0-linux-x64.tar.gz
##[debug]Destination /_work/selfhosted-dev-runner-*************_temp/************************
##[debug]set auth
Request timeout: /github-production-release-asset-2e65be/255649393/c5b966e9-33ce-4377-ba6e-ceae6db76f90?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=***********************%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240105T123409Z&X-Amz-Expires=300&X-Amz-Signature=*********************************&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=**************&response-content-disposition=attachment%3B%20filename%3Dnode-18.19.0-linux-x64.tar.gz&response-content-type=application%2Foctet-stream
Waiting 13 seconds before trying again

Falling back to download directly from Node
Error: Client network socket disconnected before secure TLS connection was established
```

It might be a trivial issue but I'm unable to figure out what might be restricting the runner to download it if egress is already set up. Any help is appreciated.

**Comment by HarithaVattikuti** [comment]
Hello @prateekg17
Thank you for creating this issue. We will investigate it and come back to you as soon as we have some feedback.

**Comment by aparnajyothi-y** [comment]
Hello @prateekg17, Apologies for the delay in response.

We have tested the same in our local and node 18 set up is successful without any errors. Please find the screenshot for reference.
<img width="1011" alt="image" src="https://github.com/actions/setup-node/assets/147696841/c06cddc6-2101-4edf-bdcf-5c7bf4b2e9a7">

Please let us know if you are still facing the same issue. Thank you.

**Comment by aparnajyothi-y** [comment]
Hello @prateekg17, Please let us know if you are still facing the same issue. Thank you.

**Comment by prateekg17** [comment]
We can close this as we are not facing this issue anymore. Thank you.
