### ISSUE TITLE
Multiple node-version-file (string[])

### ISSUE THREAD

**Issue by y-nk** [actions/setup-node#938]
**Description:**

The idea would be to propose having an array of string when it comes to `node-version-file` so that it would have fallbacks if the file was not found

**Justification:**
Like many i'm using this action in a monorepo, where sometimes services/packages are not on par. Some have a `.node-version` file, some a `.nvmrc` file, and some a `package.json` file. I wished we could provide the 3 so that the first found gets picked.

**Are you willing to submit a PR?**
Yes, I could work on it.

**Comment by y-nk** [comment]
I'm thinking there will be an issue with having an array/list as param with the toolkit (https://github.com/actions/toolkit/issues/184).

**Comment by aparnajyothi-y** [comment]
Hello @y-nk ,
Thank you for creating this issue, we will investigate it and come back to you as soon as we have some feedback.

**Comment by greyaxie** [comment]
hello

**Comment by mk-pmb** [comment]
As far as I know, GitHub actions definitions do not allow string[] as inputs, so we'd have to serialize the list. I've posted a similar suggestion [over here in issue 939](https://github.com/actions/setup-node/issues/939#issuecomment-2162667149).

**Comment by y-nk** [comment]
@mk-pmb i'm good with that. i'll close this and we can continue arguing about it (while nothing is decided or done) in #939
