### ISSUE TITLE
engines support

### ISSUE THREAD

**Issue by sakulstra** [actions/setup-node#94]
Hello,
It would be great if setup-node would automatically pick the correct version specified in our package.json engines property.

We're using github actions for 7 packages now and while all have an .nvmrc & specified [engines](https://docs.npmjs.com/files/package.json#engines) still have to use the workaround provided in: https://github.com/actions/setup-node/issues/32#issuecomment-525791142

Related to: #32, #26

**Comment by bryanmacfarlane** [comment]
Will track the work with #32.  If there's anything in addition to what's in that issue, can you add a comment to that one?  I would like to capture all the similar work in one place.  Thanks!
