### ISSUE TITLE
`lts/*` installs old LTS version intermittently

### ISSUE THREAD

**Issue by karlhorky** [actions/setup-node#940]
**Description:**

Using the following configuration installs Node.js 20.10.0, an old version. [Node.js 20.11.0](https://nodejs.org/en/blog/release/v20.11.0) has been out since 10 Jan 2024.

```
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          check-latest: true
```

The output looks like this:

```
Run actions/setup-node@v4
  with:
    node-version: lts/*
    always-auth: false
    check-latest: true
    token: ***
Attempt to resolve LTS alias from manifest...
Found in cache @ /opt/hostedtoolcache/node/20.10.0/x64
Environment details
  node: v20.10.0
  npm: 10.2.3
  yarn: 1.22.21
```

**Action version:**

actions/setup-node@v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

Node.js lts/*

```
  node: v20.10.0
  npm: 10.2.3
  yarn: 1.22.21
```

**Repro steps:**  

Use the configuration above and observe the output above

**Expected behavior:**

Node.js latest LTS (20.11.0) is installed

**Actual behavior:**

Node.js older LTS (20.10.0) is installed

cc @MaksimZhukov @dmitry-shibanov @dusan-trickovic

**Comment by karlhorky** [comment]
Looks like the manifest might be here (maybe this should be linked in the output of `actions/setup-node` for easier debugging, if this will continue to be potentially problematic in future?):

- https://github.com/actions/node-versions/blob/main/versions-manifest.json

I opened a PR there as well, in case that's a better place to discuss:

- https://github.com/actions/node-versions/pull/162

**Comment by HarithaVattikuti** [comment]
Hello @karlhorky 
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by HarithaVattikuti** [comment]
Hello @karlhorky 
The latest version 20.11.0 is merged in node-versions repository. Could you please confirm if the latest version is reflecting at your end. 
If you have any concerns please feel free to ping us.

**Comment by karlhorky** [comment]
@HarithaVattikuti I just tried re-running my job and it's still on Node.js `20.10.0`

```
Attempt to resolve LTS alias from manifest...
Found in cache @ /opt/hostedtoolcache/node/20.10.0/x64
```

**Comment by karlhorky** [comment]
Is there any way I can manually clear the manifest cache on GitHub Actions?

I know that you can clear other named caches, but these are unrelated to the manifest cache, from what I can tell.

**Comment by HarithaVattikuti** [comment]
Hello karlhorky, We have tried to reproduce the issue and unable to do so. Below is the screenshot of the same.

<img width="496" alt="Screenshot 2024-01-25 at 4 28 52 PM" src="https://github.com/actions/setup-node/assets/73516759/4908d108-1cf0-4fb3-befd-6107e3797e74">



 

Please share a sample repo with minimum code to reproduce the issue.
Feel free to reach out to us in case of any issues

**Comment by karlhorky** [comment]
@HarithaVattikuti now it's working, thanks!

```
Attempt to resolve LTS alias from manifest...
Found in cache @ /opt/hostedtoolcache/node/20.11.0/x64
```

Maybe I tried it before the change was fully rolled out.

**Comment by karlhorky** [comment]
Interesting, this is still intermittently failing on some of our repositories:

```
Attempt to resolve LTS alias from manifest...
Found in cache @ /Users/runner/hostedtoolcache/node/20.10.0/x64
```

https://github.com/upleveled/hotline-bling-codealong/actions/runs/7667389682/job/20897108024?pr=164

---

@HarithaVattikuti maybe there's a problem with the caches?

Reopening for visibility.

**Comment by HarithaVattikuti** [comment]
Hello @karlhorky,
According to your repository set up-node is run on different OS. The hostedtoolcache will reflect the latest node version from the OS image. For Ex: In MacOS-12 Image Cached Tool of node is 20.11.0 but in MacOS-13 Image cached Tool of node is still 20.10.0. 
https://github.com/actions/runner-images/blob/macOS-12/20240119.1/images/macos/macos-13-Readme.md#cached-tools
https://github.com/actions/runner-images/blob/macOS-12/20240119.1/images/macos/macos-12-Readme.md#cached-tools
Please use the related OS image for latest node version 20.11.0.
Closing this issue as it is not part of our scope.
Feel Free to reach out to us in case of any issues.

**Comment by karlhorky** [comment]
Oh wow, that's a surprising detail 🤔

To me, it seems like Node.js `lts/*` should be the latest Node.js LTS, not an older cached version.

If it would be possible to fix that and return the latest LTS, I'm sure that would be widely appreciated and reduce confusion.

**Comment by karlhorky** [comment]
Update: this continues to be a problem with Node.js v20.12.0 - the `lts/*` specifier does not install `20.12.0`, which has been out for over 5 days now:

```yml
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
```

Logs for [the workflow run](https://github.com/upleveled/preflight-test-project-next-js-passing/actions/runs/8507621988/job/23299779905?pr=152):

```
Run actions/setup-node@v4
  
Attempt to resolve LTS alias from manifest...
Found in cache @ /opt/hostedtoolcache/node/20.11.1/x64
Environment details
/home/runner/setup-pnpm/node_modules/.bin/pnpm store path --silent
/home/runner/setup-pnpm/node_modules/.bin/store/v3
Received 0 of 177801572 (0.0%), 0.0 MBs/sec
Received 125829120 of 177801572 (70.8%), 60.0 MBs/sec
Cache Size: ~170 MB (177801572 B)
/usr/bin/tar -xf /home/runner/work/_temp/36665e6f-3c08-4aa9-a645-44132e6[14](https://github.com/upleveled/preflight-test-project-next-js-passing/actions/runs/8507621988/job/23299779905?pr=152#step:7:14)367/cache.tzst -P -C /home/runner/work/preflight-test-project-next-js-passing/preflight-test-project-next-js-passing --use-compress-program unzstd
Received 17780[15](https://github.com/upleveled/preflight-test-project-next-js-passing/actions/runs/8507621988/job/23299779905?pr=152#step:7:16)72 of 177801572 (100.0%), 56.5 MBs/sec
Cache restored successfully
Cache restored from key: node-cache-Linux-pnpm-4ef79db9b37b4913d3034ac221942fa51b304d30abec481a5894d6356c04e3e6
```

**Comment by karlhorky** [comment]
@HarithaVattikuti can you reopen this issue please? 

Or if not, I'll create a new issue.

**Comment by karlhorky** [comment]
@aparnajyothi-y if you are taking this over, could you reopen this issue?

**Comment by aparnajyothi-y** [comment]
Hello @karlhorky, I have tried to run the same job to use lts* in my local and it is downloading the latest version 20.12.0. 
If a previous LTS version was cached in the runner, actions/setup-node might reuse the cached version instead of fetching the latest one. As a workaround, we need to explicitly setting the cache input to 'none' in the actions/setup-node step of your job. This will prevent actions/setup-node from using a cached version of Node.js.
     - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
        node-version: 'lts/*'
        cache: 'none'

If we want to keep the caching but ensure that always using the latest LTS version then add a step to your workflow that updates Node.js to the latest LTS version after setting it up
               
        - name: Setup Node.js
                  uses: actions/setup-node@v4
                  with:
                      node-version: 'lts/*'

       - name: Update to latest LTS version
          run: |
            npm install -g n
            sudo n lts
            echo ""NODE_PATH=$(npm root --quiet -g)"" >> $GITHUB_ENV.

**Comment by karlhorky** [comment]
@aparnajyothi-y what I think should be supported (and would be the behavior that users would expect and want):

1. `lts/*` retrieves the latest Node.js version
2. The cache is used when it is available
3. The cache is evicted \*without user intervention\* when any new LTS version is released (from my understanding, this is probably where `setup-node` could be fixed)
4. No additional configuration such as `cache: 'none'` is required
5. No additional obscure steps (such as installing a Node.js version manager) are required

**Comment by aparnajyothi-y** [comment]
Hello @karlhorky, We have furthermore investigated and found that the action itself doesn't control the cache, it's managed by the runner environment. Automatic cache eviction may need changes on the runner's side as setup-node uses the caching facilities provided by the runner environment, you can refer here. Automatic cache eviction is a potential feature where old or unused cached dependencies would be automatically removed. This ensures that the cache does not keep growing indefinitely and consume all available storage.
Using cache when available is actually a part of the Setup-action's functionality. The action will check if the required Node.js version is in the cache and use it if it's available. By caching these dependencies, subsequent runs of the workflow can be faster as they can reuse the cached dependencies instead of downloading them again.
Please let us know in case of any further clarification.

**Comment by karlhorky** [comment]
Ok, so if I'm understanding what you're saying, this bug should be reported somewhere else?

Where exactly can this be reported so that the behavior is [automatic upgrades of the cache on new LTS versions](https://github.com/actions/setup-node/issues/940#issuecomment-2034170680)?

**Comment by karlhorky** [comment]
I'm not sure I'm understanding what you're saying, but maybe you're saying this bug should be also reported somewhere else?

Where exactly can this be reported also for the runners so that the behavior is [automatic cache evictions (or cache upgrades) on new LTS versions](https://github.com/actions/setup-node/issues/940#issuecomment-2034170680)?

I and others think that the current behavior is broken, so it should be fixed.

I assume it may not be the runner's responsibility to know about new LTS versions of Node.js (that seems like responsibility of `actions/setup-node`) - it may actually be a split responsibility: both `actions/setup-node` and also in the runner environments:

1. To me, it seems that logically, the place that would be related to "performing some action when a new LTS version is released" would be `actions/setup-node` (this current repo)
2. But in this case, the action needs to evict the cache, where you mentioned the management is the responsibility of the runner

So, if this mental model is correct, there may need to be a "cache eviction API" exposed by the runner, in order for `actions/setup-node` to be able to evict the cache on new LTS versions.

**Comment by aparnajyothi-y** [comment]
Hello @karlhorky, As we have mentioned in the above comment, this feature might be shared between the actions/setup-node and the GitHub Actions runner. The actions/setup-node should ideally handle actions related to the release of new LTS versions, while cache management is typically handled by the runner. 
If we got ""cache eviction API"" support in the runner, that would allow actions like actions/setup-node to evict the cache when new LTS versions are released, ensuring that the cache is always up-to-date.
Please let us know in case of any clarification is needed from setup-node. Thank you.

**Comment by karlhorky** [comment]
Ok great, are you a part of the GitHub Actions team?

Can you reach out to someone internal on the runner side to convey the need for a Cache Eviction API to allow for the `actions/setup-node` LTS version identifier `lts/*` to use the latest LTS release without user interaction?

I see that the following people are maintainers / contributors on the public GitHub repos, but I have no visibility / connections beyond that:

- https://github.com/actions/runner
  - @TingluoHuang @luketomlinson @nikola-jokic
- https://github.com/actions/runner-images
  - @Alexey-Ayupov @mikhailkoliada @erik-bershel @MaksimZhukov

**Comment by aparnajyothi-y** [comment]
Hello @karlhorky, We are discussing with the runner-images about the possibility of the cache eviction feature from the runner-images . Please raise an issue in the runner-images repository to request support for this feature as discussed in the above comment and we can add the facility for cache eviction for LTS versions from setup-actions once we receive that feature from runner-images.
Please feel free to reach us in case of any further clarifications.

**Comment by karlhorky** [comment]
Done, request open here:

- https://github.com/actions/runner-images/issues/10311

**Comment by karlhorky** [comment]
Ok, I'm not sure of the implementation details or inner workings.

But maybe we can agree that `node-version: 'lts/*'` retrieving an old version is not only a bad UX, but also sometimes a security risk.

**Comment by aparnajyothi-y** [comment]
Hello @karlhorky, As @mikhailkoliada mentioned, cache eviction should not be handled on the runner side; instead, cache management should be performed through the task itself. The latest Node.js version, 20.15.1, is available with runner images on both Ubuntu 20 and 22 runners. We are looking for version 20.11.0, which is outdated and Installing the required version at runtime through the workflow is the best workaround.

We are proceeding to close this issue as it is confirmed that cache eviction is not possible through runner-images. Please feel free to reach out if you have any concerns or need further information.

**Comment by karlhorky** [comment]
> We are proceeding to close this issue as it is confirmed that cache eviction is not possible through runner-images

Where is this confirmed? I opened this issue and it's now been assigned:

- https://github.com/actions/runner-images/issues/10311

This issue should stay open, because there is still an active bug in `actions/setup-node` - the following config will intermittently lead to old, stale LTS versions being used:

```yaml
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
```

This is an unexpected and broken behavior for users, and can lead to security problems. Please reconsider leaving this issue open.

**Comment by karlhorky** [comment]
Maybe it should just be publicly recommended to avoid using `actions/setup-node` because of this problem.

Eg. if it's impossible for the teams at GitHub to write code to retrieve the latest LTS version when a new one is released, maybe users should be suggested to switch to third party alternatives from the community like https://github.com/dcodeIO/setup-node-nvm ([GitHub Marketplace](https://github.com/marketplace/actions/set-up-node-using-nvm))

```yaml
uses: dcodeIO/setup-node-nvm@master
with:
  node-version: lts/*
```

Which would work reliably, unlike `actions/setup-node`.

**Comment by karlhorky** [comment]
@aparnajyothi-y Since it appears that this issue is closed now as a "won't fix", I opened a PR to add a warning to the readme about NVM syntax here, and steer users away from `actions/setup-node` if they use this syntax:

- https://github.com/actions/setup-node/pull/1114

**Comment by karlhorky** [comment]
I opened a PR to add a warning to the readme about NVM syntax here, and steer users away from `actions/setup-node` if they use this syntax:

- https://github.com/actions/setup-node/pull/1114

**Comment by karlhorky** [comment]
@aparnajyothi-y I'm not sure why this issue is closed now.

Can you reopen and leave open until it's resolved?

If you close the issue, users will be unable to find this problem, which is still an open, unresolved problem in `actions/setup-node`.

**Comment by karlhorky** [comment]
## Workaround

Full replacement for broken `actions/setup-node` version resolution, with `nvm`:

```yaml
      # Use nvm because actions/setup-node does not install latest versions
      # https://github.com/actions/setup-node/issues/940
      - name: Install latest LTS with nvm
        run: |
          nvm install 'lts/*'
          rm /usr/local/bin/node
          ln -s $(which node) /usr/local/bin/node
        shell: bash -l {0}
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
```

Also posted on `github-tricks`: https://github.com/karlhorky/github-tricks/blob/main/readme.md#github-actions-correct-broken-actionssetup-node-version-resolution

**Comment by aparnajyothi-y** [comment]
Hello @karlhorky , Thank for your proposals and apologies for the delay in response.
When setup-node action was implemented initially, we designed it to optimize workflow duration to speed up customers' workflows and reduce VM cost for customers. It is why `check-latest` is disabled by default and action fallbacks to cached version of Node.js on VM. It allows to speed up workflows by 10-15 seconds. Usually, VM cache is up-to-date and it can be 5-6 days old in worst case which is acceptable for the most of customers.

If some customers need to always use the freshest version of Node.js, ""check-latest"" flag is intended for it. If ""check-latest: true"" is passed, action will ignore VM cache and always download latest version.
So, using `version: lts/*` with `check-latest: true` will give you exact behaviour which you expect. We have pretty good documentation in repo to explain this behavior: https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#check-latest-version
We don't have plans to set `check-latest: true` by default because it will cause increasing action execution duration for all customers because Node.js will always download on-flight.

**Comment by karlhorky** [comment]
> When setup-node action was implemented initially, we designed it to optimize workflow duration to speed up customers' workflows and reduce VM cost for customers

This is good. Speed and reduction of cost / resource usage is great.

> Usually, VM cache is up-to-date and it can be 5-6 days old in worst case which is acceptable for the most of customers.

For the "which is acceptable for most of customers" assertion, where do you get the data from? Have you spoken with a high number of customers who use a version specifier like `lts/*` and asked whether they think it's ok that it downloads old versions? Or is it just an assumption that you and the team have? Have you considered security releases of Node.js too, where it is often important to upgrade faster?

My assumption would be the opposite - `lts/*` and other version specifiers downloading old versions because of caching for multiple days is confusing, buggy, broken behavior that will lead users to waste time debugging.

I could imagine a short delay would be acceptable (between 1-3 hours after release), but even that is able to be mitigated with a proper cache design.

> If some customers need to always use the freshest version of Node.js, ""check-latest"" flag is intended for it. If ""check-latest: true"" is passed, action will ignore VM cache and always download latest version.
> So, using `version: lts/*` with `check-latest: true` will give you exact behaviour which you expect.

First of all, if you read the original post again, I used `check-latest: true` and this was failing to retrieve the latest version. So this feature is also broken (or at least it was, when I reported the issue).

Also, this is \*not\* the behavior I'm looking for, nor should it be the solution proposed to customers, let me demonstrate:

### 1. `actions/setup-node@v4` with `node-version: 'lts/*'`

- 👍 Uses the cache every time - performant
- 👎 The cache can be multiple days stale, leading to old versions

### 2. `actions/setup-node@v4` with `node-version: 'lts/*'` and `check-latest: true`

- 👎 Uses no cache every time - slow
- 👍 The cache is always fresh

Neither of those options are good.

I'm proposing a 3rd option, which is in my opinion how the caching should have been designed from the start.

### 3. `actions/setup-node@v4` with `node-version: 'lts/*'` (new default behavior)

- 👍 Uses the cache every time - performant
- 👍 The cache is invalidated remotely, when a new Node.js version is released, leading to fresh versions

There should be no `check-latest` option.

**Comment by karlhorky** [comment]
Actually, maybe there's even more to be improved here, if `actions/setup-node` changed its design from the manifest + hosted tool cache to the built-in `nvm`:

> It is why `check-latest` is disabled by default and action fallbacks to cached version of Node.js on VM. It allows to speed up workflows by 10-15 seconds

It only takes 3 additional seconds to [download a fresh copy of Node.js via `nvm`](https://github.com/actions/setup-node/issues/940#issuecomment-2285962305):

## `actions/setup-node@v4` with manifest + hosted tool cache

8 seconds total

![Screenshot 2024-08-22 at 07 52 07](https://github.com/user-attachments/assets/06865907-15ab-4c45-88f6-c9be57574b0f)

## `nvm` with no Node.js cache

11 seconds total

![Screenshot 2024-08-22 at 07 59 20](https://github.com/user-attachments/assets/ea5127a3-b928-4c85-b89a-cedc39514ff7)

Don't be confused by `actions/cache` - in both cases this is used for pnpm store cache - unrelated to the Node.js cache.

So an alternative would be that `actions/setup-node` could probably be faster by using `nvm` in some way.

**Comment by karlhorky** [comment]
@aparnajyothi-y can you reopen this issue?

It is still a problem - and can be considered a security problem ⚠️:

1. Node.js v22.13.1 (released 21 Jan 2025) contains [security updates](https://nodejs.org/en/blog/vulnerability/january-2025-security-releases)
2. Today (25 Jan 2025) I received Node.js v22.13.0 when using the `lts/*` alias, not containing these security updates (see logs below)

```
Run actions/setup-node@v4
  with:
    node-version: lts/*
    always-auth: false
    check-latest: false
    token: ***
  ...
Attempt to resolve LTS alias from manifest...
Found in cache @ /opt/hostedtoolcache/node/22.13.0/x64
Environment details
  node: v22.13.0
  npm: 10.9.2
  yarn: 1.22.22
```

Or if it's preferred, I can open a new issue, containing a distilled version of the messages above.

**Comment by karlhorky** [comment]
Opened a new issue:

- #1207

**Comment by karlhorky** [comment]
## Workaround: switch to `nvm`

Full replacement for broken `actions/setup-node` version resolution, with `nvm`:

```yaml
# Use nvm because actions/setup-node does not install latest versions
# https://github.com/actions/setup-node/issues/940
- name: Install latest LTS with nvm
  run: |
    nvm install 'lts/*'
    echo "$(dirname $(nvm which node))" >> $GITHUB_PATH
  shell: bash -l {0}
```

If you also need pnpm caching (replacement for the `cache` setting of `actions/setup-node`), config for `actions/cache`:

```yaml
- name: Get pnpm store directory
  shell: bash
  run: |
    echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
- uses: actions/cache@v4
  name: Setup pnpm cache
  with:
    path: ${{ env.STORE_PATH }}
    key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
    restore-keys: |
      ${{ runner.os }}-pnpm-store-
```

Also posted on `github-tricks`: https://github.com/karlhorky/github-tricks/blob/main/readme.md#github-actions-correct-broken-actionssetup-node-version-resolution
