### ISSUE TITLE
Node versions question

### ISSUE THREAD

**Issue by BlueskyFR** [actions/setup-node#961]
Hi,

The README doesn't specify how I may target automatically the latest LTS, how may I do that?

Thanks!

**Comment by HarithaVattikuti** [comment]
Hello @BlueskyFR
Thank you for creating this issue.

Please use below code for fetching the latest LTS version:
```
       - uses: actions/setup-node@v4
         with:
          node-version: 'lts/*'

```
Feel Free to reach out to us in case of any issues.

**Comment by BlueskyFR** [comment]
Thanks! Are you sure though? I think I saw another issue in which it was reported that this expression doesn't do that.

**Comment by priyagupta108** [comment]
Hello @BlueskyFR, 
The `actions/setup-node` action is designed to use the latest LTS Node.js version when `'lts/*'` is specified. This is validated by the action's official test suites and source code.
If you have seen a specific issue where this was not working as expected, could you please provide more details or a link to that issue for a more accurate response?

**Comment by priyagupta108** [comment]
Hello @BlueskyFR 👋 , just following up. Do you have any updates or queries related to the latest LTS Node.js version setup?

**Comment by priyagupta108** [comment]
Hello @BlueskyFR, 
Due to inactivity, I'm going to close this issue for now. If you have any further  questions, please feel free to reopen this issue or create a new one. Thank you :)
