### ISSUE TITLE
Question on Changing Version#

### ISSUE THREAD

**Issue by sameerseekala1** [actions/setup-node#968]
Hi,

This is question on changing the node version without modifying the workflow.

Can we store version# in repo variable and access it in the workflow like below? If not is there a way to pass node version to the workflow dynamically? Because it is tedious to update all the workflows in all branches whenever the version changes.

name: Setup Node
uses: actions/setup-node@${{ vars.NODEVERSION }} 

Please suggest.

**Comment by aparnajyothi-y** [comment]
Hi @sameerseekala1, Thank you for creating this issue and we will look into it :)

**Comment by silent-sour** [comment]
This is already part of the existing API.

The @ on the action is the tagged version of the action to use. The node version is set in a with parameter.

Syntax:

- uses: action/setup-node@v4
  with:
    node-version: ${{ vars.NODEVERSION }}

**Comment by aparnajyothi-y** [comment]
Hello @sameerseekala1, Thank you for creating the issue once again.
Yes, we can set up a dynamic version number for the Node.js setup in your GitHub Actions workflows. However, it isn't done via vars, but with env  or secrets. Below is the reference syntax

name: Setup Node
env:
  NODE_VERSION: 14.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

The Node_Version environment variable is defined at the workflow level and can be accessed in the node-version input of the actions/setup-node action. To store the node version outside of the workflow file, replace env.NODE_VERSION with secrets.NODE_VERSION.

Please let us know in case of any further concerns :)

**Comment by sameerseekala1** [comment]
@aparnajyothi-y Thanks for your response. Does it work for 'uses' attribute as well like below?

    - name: Setup Node.js
      uses: actions/setup-node@${{ secrets.SETUP_VERSION }}
      with:
        node-version: ${{ secrets.NODE_VERSION }}

**Comment by aparnajyothi-y** [comment]
Hello @sameerseekala1, you cannot directly use secrets in the 'uses' field. Instead, secrets are typically used within the 'env' or 'with' sections of a job step. The 'uses' field is reserved for specifying an action to execute as a part of your job step. The value for 'uses' should be the designated action's name. Feel free to reach out if you have any more questions.

**Comment by aparnajyothi-y** [comment]
Hello @sameerseekala1, Please confirm the above information clarified your question. Thank you in advance.

**Comment by sameerseekala1** [comment]
Yes @aparnajyothi-y thanks for clarifying.

**Comment by aparnajyothi-y** [comment]
Thank you @sameerseekala1 for the confirmation and proceeding to close this issue.
