### ISSUE TITLE
TSC problem matcher doesn't handle line & column in errors

### ISSUE THREAD

**Issue by xt0rted** [actions/setup-node#97]
I have a build at https://github.com/xt0rted/slash-command-action/pull/71 that's failing and the typescript problem matcher is picking up the error, but it's not associating the annotation with the correct line as seen [here](https://github.com/xt0rted/slash-command-action/pull/71/files). This looks to be due to line value also containing the column (`107,11`).

This can be seen using https://regex101.com/ with the values:

```regex
^(?:\s+\d+\>)?([^\s].*)\((\d+|\d+,\d+|\d+,\d+,\d+,\d+)\)\s*:\s+(error|warning|info)\s+(\w{1,2}\d+)\s*:\s*(.*)$
```

```terminal
src/commandHandler.ts(107,11): error TS2322: Type 'Response<ReposGetCollaboratorPermissionLevelResponse>' is not assignable to type 'Response<CollaboratorPermissionLevel>'.
```

**Comment by xt0rted** [comment]
I just ran into this again. Is it intentional that the line/column numbers aren't being included in the annotation?

**Comment by billyvg** [comment]
It looks like `location` is not a valid configuration item: https://github.com/actions/runner/blob/6c70d53eead402ba5d53676d6ed649a04e219c9b/src/Runner.Worker/IssueMatcher.cs#L153

**Comment by bryanmacfarlane** [comment]
will track work to add line and column
