### ISSUE TITLE
why you dont tell me the truet

### ISSUE THREAD

**Issue by greyaxie** [actions/setup-node#982]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by greyaxie** [comment]
> 
> 
> 
> **Description:**
> A clear and concise description of what the bug is.
> 
> **Action version:**
> Specify the action version
> 
> **Platform:**
> - [x] Ubuntu
> - [ ] macOS
> - [ ] Windows
> 
> **Runner type:**
> - [ ] Hosted
> - [ ] Self-hosted
> 
> **Tools version:**
> 
> 
> **Repro steps:**  
> A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.
> 
> **Expected behavior:**
> A description of what you expected to happen.
> 
> **Actual behavior:**
> A description of what is actually happening.

why

**Comment by greyaxie** [comment]
can you give me

**Comment by aparnajyothi-y** [comment]
Closed this issue as a spam
