### ISSUE TITLE
bug: setup-node@v4 fails with HTML content?

### ISSUE THREAD

**Issue by SgtPooki** [actions/setup-node#986]
**Description:**
setup-node@v4 fails with HTML page I can't figure out the source for.

**Action version:**
setup-node@v4

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

from https://github.com/ipfs/helia-verified-fetch/actions/runs/8381845262/job/22954396334#step:3:3
```
node-version: lts/*
always-auth: false
check-latest: false
token: ***
```

**Repro steps:**  
No repro steps, but I thought this odd enough to report: 
https://github.com/ipfs/helia-verified-fetch/actions/runs/8381845262/job/22954396334#step:3:3

**Expected behavior:**
If a failure happens, we should see the failure message instead of an unknown HTML page

**Actual behavior:**

setup-node@v4 fails after "Attempt to resolve LTS alias from manifest..." message. see https://github.com/ipfs/helia-verified-fetch/actions/runs/8381845262/job/22954396334#step:3:8 and below screenshot.

![image](https://github.com/actions/setup-node/assets/1173416/227c8428-04e1-49ab-b378-ddd67f6ed515)

workflow source: https://github.com/ipfs/helia-verified-fetch/blob/8715740e8d39fdd7ae7321464c45e0b0e4466756/.github/workflows/js-test-and-release.yml#L22

reusable workflow source: https://github.com/ipdxco/unified-github-workflows/blob/main/.github/workflows/js-test-and-release.yml

A recent change from `pl-strflt/uci` repo to `ipdxco/unified-github-workflows` could be the culprit?

**Comment by aparnajyothi-y** [comment]
Hello @SgtPooki, Thank you for creating this issue and we will look into it :)

**Comment by gowridurgad** [comment]
Hi @SgtPooki

**Comment by SgtPooki** [comment]
I havent seen this error since either, and dont have a minimal repro available. It was just an odd error that shouldnt have happened that i wanted to make sure you were aware of.

Im fine for this to be closed if you all have confirmed things are working as expected
