### ISSUE TITLE
Ethwork

### ISSUE THREAD

**Issue by yksnyn** [actions/setup-node#988]
インターフェース名です。 rmnet1
リンクスのアドレスです。
10.187.215.75
ルートです。
0.0.0.0/0 -> 0.0.0.0 rmnet1 mtu 1500
10.187.215.75/32 -> 0.0.0.0 rmnet1 mtu 0インターフェース名です。 rmnet2
リンクスのアドレスです。
240a:2:4861:93f5::1
ルートです。
::/0 -> :: rmnet2 mtu 1500
240a:2:4861:93f5::/64 -> :: rmnet2 mtu 0

**Comment by aparnajyothi-y** [comment]
988
